### ISSUE TITLE
Въпрос относно първата лекция.

### ISSUE THREAD

**Issue by Alexander-Kostov** [luchob/softuni-feb2023#10]
В следния мапинг от първата лекция:

@GetMapping("/{id}")
    public ResponseEntity<BookDTO> getBookById(@PathVariable("id") Long id) {
        Optional<BookDTO> book = this.bookService.getBookById(id);

        return book
                .map(ResponseEntity::ok)
                .orElseGet(() -> ResponseEntity.notFound().build());
    }

Когато връщаме ResponseEntity::ok, това ли е метода, в който ще се осъществи проверка дали дадената книга съществува или не. Разбирам какво прави цялото нещо абстрактно, но в конкретика не съм точно сигурен, къде точно се разбира книгата дали е Null или не.

**Comment by luchob** [comment]
Здравей!

Самия book не е instance на `Book`, а е `Optional<Book>`. Класът `Optional` е част от Java и ни дава възможност да работим малко по-елегантно с референции, които може да са `null` и е в основата на твоя въпрос.  Представи си следния тривиален клас:

```
class User {
  private final String name;

  public User(String name) {
    this.name = name;
  }

  public String getName() {
    return name;
  }
}
```

И един тестов клас с метод:

```
public class Test {

  private static User mapToUser(String userName) {
    return new User(userName);
  }

}
```

Да видим как работи кодът:

```
public static void main(String[] args) {

    String userName = null;

    Optional<String> userNameOpt = Optional.ofNullable(userName);

    User user = userNameOpt.
        map(Test::mapToUser).
        orElseGet(() -> new User("anonymous"));

    System.out.println(user.getName());
  }
``` 

Това нещо ще изпише `anonymous`. Т.е. тъй като `userNameOpt` e празно се изпълнява `() -> new User("anonymous")`. Този пък код:

```
public static void main(String[] args) {

    String userName = "Pesho";

    Optional<String> userNameOpt = Optional.ofNullable(userName);

    User user = userNameOpt.
        map(Test::mapToUser).
        orElseGet(() -> new User("anonymous"));

    System.out.println(user.getName());
  }
``` 

ще изпише `Pesho`. Тъй като `userNameOpt` не е празно ще изпълни `Test::mapToUser`. 

Отговорът на твоя въпрос е: репозиторито ще провери. Ако има книга, ще върне пълен `Optional`. В противен случай празен.

Поздрави,
Л.
