### ISSUE TITLE
Проблем със сървиз, който е инжектнат

### ISSUE THREAD

**Issue by lamenco** [luchob/softuni-feb2023#100]
Здравей, може ли да ми каже, защо  когато се опитам да направя edit още при Get-a ми връша " this.windowService" is null" 
Инжектнал съм го, а и при други функционалности не ми е Null.
И може ли  съвете след като го оправя как да завърша PatchMapping. Просто да си взема ордъра от репозиторито и да му сетна новите стойности от Дто-то ли?
Благодаря!

**Comment by lamenco** [comment]
Извинявай оставям и линк към репото

  https://github.com/lamenco/window-azure

**Comment by luchob** [comment]
Здравей! 

:-) За null прочети тук -> https://github.com/luchob/softuni-feb2023/issues/95#issuecomment-1487426555

_Просто да си взема ордъра от репозиторито и да му сетна новите стойности от Дто-то ли?_

Ми да, тези които са инициализирани отиват в ентитито и ги записваш. Това е.

Поздарви,
Л.
