### ISSUE TITLE
моля за помощ отново този път с интегрейшън тест

### ISSUE THREAD

**Issue by ViliIlieva** [luchob/softuni-feb2023#101]
https://github.com/ViliIlieva/MyKnitShop

Този път се хванах да правя май най дългия интегрейшън тест, писах четох грешки и чистих проблемите им, но сега не ми дава конкретна грешка и не зная къде точно греша. Ако може да погледнеш. 
OrderControllerIT   testCartPatch() само разбирам че е неуспешен теста

**Comment by luchob** [comment]
Здравей!

Не съм съгласен, че не ти дава конкретна грешка. Лог:

```
MockHttpServletResponse:
           Status = 403
    Error message = Forbidden
```

Тъй като останалите настройки са ОК, това означава че си забравила да изпратиш csrf тоукън в заявката. Ето така:
```
    @Test
    @WithMockUser(username = "client", roles = {"CLIENT"})
    void testCartPatch() throws Exception {
        when(userService.orderProducts(makeOrderDTO, principal)).thenReturn(1L);

        mockMvc.perform(patch("/cart").with(csrf()))
                .andExpect(status().is2xxSuccessful())
                .andExpect(redirectedUrl("/order/details/1"));
    }
``` 

Оттам нататък грешките отново са конкретни :-)

Поздрави,
Л.

**Comment by ViliIlieva** [comment]
Хахаха, благодаря, значи борбата продължава
