### ISSUE TITLE
Проблем с implement на edit product service

### ISSUE THREAD

**Issue by Alexanski13** [luchob/softuni-feb2023#102]
Здравей отново  Лъчо!

От последните 2 дена се мъча да накарам update buttonа да го свържа с логика за editvane на existing продукт ако може да ми дадеш насоки как да го направя точно.

**Comment by luchob** [comment]
Здравей!

Колегата се е справил. Поразходи се тук -> https://github.com/luchob/softuni-feb2023/issues/63#issuecomment-1476504303 и там ще намериш идеи. Надявам се реализирани :-)

Поздрави,
Л.
