### ISSUE TITLE
Моля за помощ с тест който ме връща на .stream.reduce като проблем

### ISSUE THREAD

**Issue by ViliIlieva** [luchob/softuni-feb2023#103]
https://github.com/ViliIlieva/MyKnitShop
опитах по доста начини но все безуспешни, дори бях премахнала .stream метода и минавах през всеки продукт по отделно и пак ме върна на същото място че не може да направи sum
В OrderControllerIT  в testCartPatch() ако може да го погледнеш

![image](https://user-images.githubusercontent.com/100292906/228630039-e2ebde14-73de-460b-aeb4-687cd88174ae.png)

**Comment by ViliIlieva** [comment]
отказвма се за сега от този тест, ще опитам с други, тотално се изгубих, дори вече имам чувството че не зная как да го направя

**Comment by luchob** [comment]
Здравей!

Само да отбележа, че това е интегрейшън тест доколкото виждам, а не мокито тест. В интегрейшън тестовете не ползваме мокове обикновено, а ако го правим то е по по-особен начин с `@MockBean` анотацията.

Поздрави,
Л.
