### ISSUE TITLE
Въпрос по проекта

### ISSUE THREAD

**Issue by StefanPYordanov** [luchob/softuni-feb2023#105]
Здравейте,
Съжалявам за безпокойството, но може ли са погледнете защо при опит за постване на коментар ми дава Forbidden, при положение, че съм логнат с потребител, също и при логнат потребител при отиване на ендпойнт /profile, не успявам да напълня данните за потребителя. Може да използвате admin с парола admin12345 .
Поздрави,
Стефан

https://github.com/StefanPYordanov/BookLibrary

**Comment by luchob** [comment]
Здравей!

На въприс 1. Защото екшъна на формата е грешен:
```
                <form  id="commentForm" method="POST"
                      action="/">
```

Т.е. събмитва се към / където няма никой.

**Comment by luchob** [comment]
Въпрос 2:

Не можеш защото при теб е приблизително така:

```
<div class="card-body text-center" th:object="${user}">
 </div>

<p class="text-muted mb-0" th:text="*{username}">JohnatanSmith10</p>
```

А трябваше да е приблизително ето така:

```
<div class="card-body text-center" th:object="${user}">
   <p class="text-muted mb-0" th:text="*{username}">JohnatanSmith10</p>
 </div>
```

Или по-просто изречено: елементът, който съдържа `*{username}` трябва да е дете на елемента, който съдържа `th:object`. `th:object` означава, че можеш да използваш синтаксиса `*` във всичките му child елементи.

Поздрави,
Л.
