### ISSUE TITLE
Login не работи

### ISSUE THREAD

**Issue by AngelJava123** [luchob/softuni-feb2023#106]
Здравей Лъчо,

Може ли да ми погледнеш проекта и да ми кажеш каква е причината Login да не работи, винаги показва Bad Credentials и стои на страницата без да се случва нищо?

Благодаря предварително.

Поздрави,
Ангел

**Comment by luchob** [comment]
Здрасти!

Свалих проекта в tar.gz. Между другото липсват методите в някои репозиторита като:   
```
VehicleColor findByPaint(String paint);
``` 
И още 2. Написах си ги. След това  - премахни анотацията `@Sevice` в `CarsDealershipUserDetailsService`, Spring се обърква при наличието на 2 бийна въпреки че единия е `@Primary`. Допускам и че логването е с email. В такъв случай, работи - тествах регистрация и логина е успешен.

Поздрави,
Л.
