### ISSUE TITLE
Integration test and "this.mockMvc" is null

### ISSUE THREAD

**Issue by PlamenPeev** [luchob/softuni-feb2023#107]
Здравей Лъчо,
Опитвам се да направя тест на RegistrationController-a  и следвам стъпките, които показа. Сложил съм анотациите @SpringBootTest и @AutoConfigureMockMvc на тестовия контролер и вътре съм дал @Autowired на private MockMvc mockMvc, но въпреки това теста не минава и ми изписва следната грешка: "java.lang.NullPointerException: Cannot invoke "org.springframework.test.web.servlet.MockMvc.perform(org.springframework.test.web.servlet.RequestBuilder)" because "this.mockMvc" is null".  Ще бъда благодарен за някакви насоки.

**Comment by luchob** [comment]
Здрасти! 

Това ли е проекта? -> https://github.com/PlamenPeev/adorablePet

Не виждам mockMvc тук...

Поздрави,
Л.

**Comment by PlamenPeev** [comment]
Ееее .... вчера не съм направил commit  към github, довечера ще го заредя.

**Comment by PlamenPeev** [comment]
Готово!

**Comment by luchob** [comment]
Супер !

Опитай да смениш следния импорт (Junit 4):

```
import org.junit.Test; 
``` 

С ето този (Junit 5):

```
import org.junit.jupiter.api.Test;
```

:-)

Поздрави,
Л.

**Comment by PlamenPeev** [comment]
Много благодаря! Поздравявам те за воденето на курса и за всичко което ни показа по това време.
