### ISSUE TITLE
Interceptor problem

### ISSUE THREAD

**Issue by ZhuliyanRusev** [luchob/softuni-feb2023#108]
Здравейте, господин Балев, не мога да имплементирам Интерсептора в проекта си в UserController и няма кой да ми помогне, затова се обръщам към Вас оттук, понеже не намерих никакви Ваши контакти. Бих искал подкрепата Ви!

**Comment by luchob** [comment]
Здравей!

Може ли малко подробности? Предполагам, [това е контролера](https://github.com/ZhuliyanRusev/GameTaste/blob/main/src/main/java/com/example/gametaste/web/UserController.java). В проекта не виждам интерсептор. Забравил си да го комитнеш или още не е написан? Какво очакваш да прави този интерсептор (в уеб слоя)?

Поздрави,
Л.

**Comment by ZhuliyanRusev** [comment]
Здравейте, господин Балев! Интерсептора го къмитнах днес, по спомен е в папката security, кръстил съм го или LoggingInterceptor или UserInterceptor. Не знам обаче дали е правилно да го имплементирам в UserController и какво точно трябва да прави.

**Comment by luchob** [comment]
Здравей! 

Трябва да решиш какво искаш точно да прави този интерсептор. Давам ти примери:

- искам да засича за колко време минава някое извикване в контролерите
- да прави статистика за броя на някакви заявки
- да се използва за интернационализация
- и т.н. 

На лекцията дадохме един друг пример - black list на user по IP. Ето го и примера с код:

https://github.com/luchob/softuni-feb2023/tree/main/blacklist

Има го в лекциите, може да се изгледа пак. Плюс няколкото думи за интерсептор, каква е идеята, къде стои на пътя на HTTP заявката и т.н. 

Просто въведение -> https://www.baeldung.com/spring-mvc-handlerinterceptor

Плюс разбира се, нашите лекции.


Поздрави,
Л.
