### ISSUE TITLE
Моля за помощ

### ISSUE THREAD

**Issue by lamenco** [luchob/softuni-feb2023#11]
Здравей, би ли ми помогнал къде греша -> https://github.com/lamenco/Window-Shopper изтегледет PVC9.rar
При вас интересептора работи а при мен не, дали може да ми кажете къде да погледна, единствено ми се променя e
 "??fragment_language_en_US??" и дори не знам защо не пише Language или Език.

И втория ми проблем, бихте ли ми казали къде греша при теста testDelete-> "/cart/deleteWindow/{id}", гледам внимателно клипа ви от миналото издрание и не разбирам защо ми излиза грешка ->
detached entity passed to persist: com.example.demo.models.entity.User

Благодаря!

**Comment by luchob** [comment]
Здравей, да започнем оттам че файловете с месиджите са леко повредени. Това не се забелязва на пръв поглед, но ако ги отвориш с hex  редактор например, ще видиш че отпред има т.нар. BOM ([Byte order mask](https://en.wikipedia.org/wiki/Byte_order_mark)) който в UTF-8 се репрезентира от последователността `0хEF 0хBB 0хBF`. Ето:

<img width="499" alt="Screenshot 2023-02-25 at 18 13 22" src="https://user-images.githubusercontent.com/10339738/221367499-b0ad8b29-716f-46c8-8468-3764f6fd34d8.png">

Тези символи не се виждат, трябва да ги махнеш. Най-безболезнено ще стане ако създадеш файловете наново в IntelliJ, увериш се че са UTF и просто копираш съдържанието на старите файлове вътре.

Тъй като си инструктирал ресурс бъндъла да ползва UTF-8, а BOM в UTF-8 не значи нищо, той го взема като част от ключа и един вид си повредил ключа който стои на първия ред. Ако искаш опитай и размести ключовете в properties файла преди да го оправиш и ще видиш че винаги първия ключ е прецакан :-)

Погледни дали като сменяш езика в дропдауна се презарежда страницата. Виж в нетуърк таба. При мен всичко си работи съвсем нормално, когато веднъж изтрия BOM-а.

**Comment by luchob** [comment]
Другият проблем е много по-труден за разясняване. Корени се някъде тук :-)

```
@BeforeEach
    void setUp(){
        testUser = testDataUtils.createTestUser("pesho");
        testOffer = testDataUtils.createTestOffer(testUser);
    }
```

Какви може да са стейтовете на едно ентити:

- transient - няма ID, създаден е с new
- managed - има ID и е свързан с хибернейт сесия
- detached - има ID и не е свързан с хибернейт сесия

Тук user-a ти става detached:
```
testUser = testDataUtils.createTestUser("pesho");
```

Т.е. създаден е, но вече транзакцията е приключила и няма никой. Не можеш да пуснеш save с detached entity в релация. Един начин да оправиш това е да осигуриш въпросната сесия използвайки `@Transactional` анотация. Напр:

```
@Transactional
@BeforeEach
    void setUp(){
        testUser = testDataUtils.createTestUser("pesho");
        testOffer = testDataUtils.createTestOffer(testUser);
    }
```
