### ISSUE TITLE
Проблем с достъпа до css,js и други файлове

### ISSUE THREAD

**Issue by Alexander-Kostov** [luchob/softuni-feb2023#110]
Привет!

link: https://github.com/Alexander-Kostov/EStore-Project

Затормозих се с един случай, и знам, че бъркам някъде, но вече не знам къде. Имам страница с продукти, където всеки продукт има име и картинка, и името е линк към друга страница - детайлите на продукта, която започнах да правя. Идеята ми беше да изпращам обекта по ИД, и всяка страница с детайлите на продукта да визуализира идващия продукт. Обаче, поради някаква причина не ми зарежда css-а, js скриптове и подобни. В network таб-а видях, че има заявки с код 404, което още повече ме обърка. Моля за асистенция, че съм ударил на греда :D

**Comment by luchob** [comment]
Здравей! 

Ще помагам, но бих искал да си пусна проекта при мен. Но за съжаление липсват много неща и не мога да го пусна за да видя какво точно става.

<img width="520" alt="Screenshot 2023-03-31 at 12 44 41" src="https://user-images.githubusercontent.com/10339738/229086402-cfc114ea-bba5-4f43-b4d1-a5f89654d08f.png">

Може ли да го оправиш първо, до състояние в което може да се пусне?

Поздрави,
Л.

**Comment by Alexander-Kostov** [comment]
Вече Commit-нах всичко. Би трябвало да може да тръгне сега.

**Comment by luchob** [comment]
Здравей! 

Предполагам те смущават подобни заявки:

```
http://localhost:8080/products-details/img/product-6.jpg
``` 

Които завършват с 404 и започват с подобни HTML елементи:

``` 
<img src="img/product-1.jpg" alt="Product Image">
``` 

Причината е, че това е относителен адрес към текущия път в браузъра. Колежката имаше същия проблем, описан и решен ето тук:

https://github.com/luchob/softuni-feb2023/issues/17#issuecomment-1451862789

Прочети го и ще разбереш как да викаш правилното, именно:

```
http://localhost:8080/img/product-6.jpg
``` 

Поздрави,
Л.

**Comment by Alexander-Kostov** [comment]
Преди да започна да чета бих искал само да ми потвърдиш дали става въпрос за същия проблем, защото сега като прочетох пак какво съм писал не съм сигурен дали аз го обясних по правилния начин. Така изглежда страницата без да съм кликнал върху даден обект.

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/106506241/229092719-f2edacc7-6e79-413a-bb63-9c7219c8e970.png">

Така изглежда след като кликна на даден обект.

<img width="1271" alt="image" src="https://user-images.githubusercontent.com/106506241/229093297-f9a65b59-8242-4df9-be3f-115602d8c9d6.png">

**Comment by luchob** [comment]
Eee... Ти сега гледаш да не се прецакаш и да го прочетеш напразно :-) :-) :-) Може пък дори и да не е това да има някаква полза ;-)

Но - да, става въпрос за многото 404 грешки на `/product-details/<product-id>`.

Поздрави,
Л.

**Comment by Alexander-Kostov** [comment]
Оправих го точно това беше, Благодаря много!
