### ISSUE TITLE
Проблем с базата

### ISSUE THREAD

**Issue by MariaBonkova** [luchob/softuni-feb2023#113]
Привет Лъчо, имам следните проблеми.
1.
![image](https://user-images.githubusercontent.com/120118418/229355933-d984b312-db99-4f40-8cc0-64e6fe04b38b.png)
Вчера дропнах таблицата в mysql, с идеята да си я напълня наново да видя дали всичко работи и сега честито. Не иска да ми създаде половинатат ентитита. Преди това бяха излезли всички, бях напълнила базата с информацията която ми е в сайта по каталозите. При създаване на дадени продукти се запазваха в репотатат. Сега обаче съм в шок.
2. Може ли да погледнеш като създавам примерно предмет за дом. любимец. Задаваш си параметри натискаш бутоня и редиректвам на следващата страница /така е правилно, така искам /, но в каратата незнам защо ми дава нул цената и името. Дебъгвах излизат като правилно напълване, на незнам във view-то защо не излизат. Така ми става и в секцията за къщи и музикални инструменти.  
4. Гледам, че по задание за проекта се иска 5 ентитати 5 репота, а аз съм нашвраскала вече по 10-тина. Май съм се престарала. 
Чудя се дали да трия от тях или да правя логика само за един вид, че и без това нямам време, а съм до никъде. 
М

https://github.com/MariaBonkova/3D-printing-project

**Comment by luchob** [comment]
:-) Здраве желая!

Относно 1) Насочвам вниманието към следните пропъртита:

```
spring.jpa.hibernate.ddl-auto 
```

Възможни стойности:

```
validate: validate the schema, makes no changes to the database.
drop: database dropping will be generated.
update: update the schema.
create: creates the schema, destroying previous data.
create-drop: drop the schema when the SessionFactory is closed explicitly, typically when the application is stopped.
none: does nothing with the schema, makes no changes to the database
```

```
spring.jpa.defer-datasource-initialization=true
```

Това забавя изпълнението на data.sql след създаването на схемата от hibernate.

```
spring.sql.init.mode
``` 

Като да изпълни `data.sql`

`never` - никога
`always` - винаги
`embedded` (default) - когато усети, че работи с embedded datase

При мен тръгна след:

1. dorp db
2. start app с ddl-auto  update и defer-datasource-initialization true

**Comment by luchob** [comment]
Относно 2) Редиректваш към тази страница: `/pets-view`
 
Контролерът е следния:

```
    @GetMapping("/pets-view")
    public String petsView() {
        return "pets-view";
    }
```

Моделът е празен и няма какво да се покаже... Може би целта е `/create-item-form/pets-view/{id}` където id-то е новосъздадената играчка за домашен любимец?

**Comment by luchob** [comment]
Прескачам 3 и относно 4) Моя съвет е - направи първо минимума. Ако имаш време след това - надгради го.

Поздрави,
Л.
