### ISSUE TITLE
Проблеми

### ISSUE THREAD

**Issue by MariaBonkova** [luchob/softuni-feb2023#115]
![image](https://user-images.githubusercontent.com/120118418/229516367-b63fe173-24c5-4e7b-88d3-74cecbb1d0e3.png)
Привет, Лъчо. Явно не е тук проблема. В базата трябва да има 9таблици, а ми излизат 7. Рових ги имат си анотации ентити и тейбъл. Какво още искат от живота.

И по 2рия проблем. Искам като редиректне към pets-view да се зареди новият продукт и да му се покаже името и цената.
Както предполагаш целта е /create-item-form/pets-view/{id} където id-то е новосъздадената играчка за домашен любимец.
И това не знам как да стане

**Comment by luchob** [comment]
Привет :-) 

Относно 1, какво искат от живота е малко по засукано. Проблемът е тук:

```
    @Column(columnDefinition = "TEXT")
    public String getDescription() {
        return description;
    }
```

На първо време погледни проблема на колегата -> https://github.com/luchob/softuni-feb2023/issues/79

Ако след това все още те интересува проблема се загледай в логовете, какво става с някое от "изчезналите" ентитита. Хибернейт прави ето това:

``` 
  create table `create_house_entity` (
       `id` bigint not null auto_increment,
        `description` `TEXT`,
        `flat` decimal(38,2),
        `material_composition` varchar(255),
        `price` decimal(38,2),
        `product_name` varchar(255) not null,
        `quadrature` decimal(38,2),
        `url_image` varchar(255),
        primary key (`id`)
    )
``` 
Опитай се да пуснеш заявката в MySQL и ще видиш че гърми, защото TEXT е в кавички. Защо обаче е в кавички? Заради тази настройка:

``` 
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
``` 

След това прочети това -> https://stackoverflow.com/questions/60087403/spring-jpa-globally-quoted-identifiers-incorrectly-quoting-column-type-text

И след това вече ще знаеш какво точно става :-)

**Comment by luchob** [comment]
_/create-item-form/pets-view/{id} ....
И това не знам как да стане_

Най просто би било нещо от сорта:

```
var newObjId = myService.createSomething(...)

return "redirect:/create-item-form/pets-view/" +newObjId;
```

Поздрави,
Л.
