### ISSUE TITLE
Не ми зарежда снимки, css в нов html темплейт.

### ISSUE THREAD

**Issue by Alexander-Kostov** [luchob/softuni-feb2023#118]
link: https://github.com/Alexander-Kostov/EStore-Project

Привет Лъчо! Направих си интерсептор в проекта по примера, който ни даде в лекцията - ииухууу, до тук добре. Ама както винаги не може всичко да тръгне от първия път и трябва нещо да не е наред :D. Реших да направя html страница(blacklisted), за посетителите които са блокирани по ип адрес. Сложих снимка, но поради някаква причина не ми я зарежда и не разбирам защо. Видях също, че и css-a не ми се зарежда. В blacklistservice съм оставил метода винаги да връща true, за да може да тествам по-лесно. Може ли да удариш едно рамо ?

**Comment by luchob** [comment]
Здрасти!

Ето защо :-)

<img width="1362" alt="Screenshot 2023-04-04 at 16 29 01" src="https://user-images.githubusercontent.com/10339738/229808371-4ca917d1-cd7b-4774-8a1e-f6e31c30b9a7.png">

Опитваш се да заредиш css-a, интерсептора прихваща опита ти и... връща blocked страницата вместо css-a ;-) Същото със снимката. Интерсептора прехваща и тези рикуести.

Поздрави,
Л.

**Comment by Alexander-Kostov** [comment]
Разбирам.. В такъв случай за да върна blocked страницата със css-a и снимката какво трябва да направя ? Как мога да ги разреша за да ги връща заедно ?

**Comment by luchob** [comment]
Най-простият вариант е да филтрираш URL-тата към ресурса ти с помощта на `HttpServletRequest`-а. С този обект може да вземеш request URL-a и да го пуснеш ако е за твоите картинки, css-и и т.н.

Поздрави,
Л.

**Comment by Alexander-Kostov** [comment]
Може ли да ми дадеш нагледен пример как трябва да стане, тъй като аз изпозлвам по примера от лекцията ThymeleafViewResolver и повече се обърках с този отговор. Това е метода и предполагам тук трябва да стане магията.
  
 @Override
    public boolean preHandle(HttpServletRequest request,
                             HttpServletResponse response,
                             Object handler)
            throws Exception {
        String ip = getIpAddressFromRequest(request);

        if (service.isBlacklisted(ip)) {
    
            View blockedView = thymeleafViewResolver.resolveViewName("blacklisted.html", Locale.getDefault());


            if (blockedView != null) {
                blockedView.render(Map.of(), request, response);
            }
            return false;
        }
        return true;
    }
    
    Поздрави!

**Comment by luchob** [comment]
Привет!

Например, методът `request.getRequestURI()`, според документацията:

<img width="654" alt="Screenshot 2023-04-04 at 21 43 06" src="https://user-images.githubusercontent.com/10339738/229888673-266096f0-eb9f-4d06-8f65-c95603bc9ae9.png">

Например, за твоя CSS връща:

<img width="215" alt="Screenshot 2023-04-04 at 21 43 41" src="https://user-images.githubusercontent.com/10339738/229888802-3b26ab89-08bb-44fa-b219-9ffddeb56ca5.png">

Т.е. можеш да разбереш дали си иска CSS или image, нали? Супер. Следваща стъпка е ако искаш интерсептора просто нищо да не прави е да върнеш `true` от `preHandle`. Както казва документацията:

```
Returns:
true if the execution chain should proceed with the next interceptor or the handler itself. Else, DispatcherServlet assumes that this interceptor has already dealt with the response itself.
```

В псевдокод:

```
var requestURI = request.getRequestURI();

if (isBlacklistAllowedRequest(requestURI)) {
   return true;
}
```

Поздрави,
Л.

**Comment by Alexander-Kostov** [comment]
Искам да ти благодаря за светкавичните и изчепрателни отговори. Но въпреки общите ни усилия пак не успявам да натъкмя картината :/. Първата част от отговора я разбрах май. Втората обаче меко казано ме обатачи - Идеята на интерсептора в моя случай е да blacklist-ва ip-та започващи по даден начин, така че стъпката, която спомена "интерсептора да не прави нищо" не разбирам защо бих искал това, това тотално ме обърка. Логиката ми е следната

чрез този метод взимам ip-то на user-a

     private String getIpAddressFromRequest(HttpServletRequest request) {

        String ipAddress = null;

        String xffHeader = request.getHeader("X-Forwarded-For");
        if (xffHeader != null && !xffHeader.equals("unknown")) {
            int commaIdx = xffHeader.indexOf(",");
            if (commaIdx > 0) {
                ipAddress = xffHeader.substring(0, commaIdx - 1);
            }
        }

        if (ipAddress == null) {
            ipAddress = request.getRemoteAddr();
        }

        return ipAddress;
    }


След това в pre-handle взимам ип-то от метода и проверявам дали е blacklist-нато като съответно подготвям с ThymeleafViewResolver темплейта.

       @Override
        public boolean preHandle(HttpServletRequest request,
                             HttpServletResponse response,
                             Object handler)
            throws Exception {
        String ip = getIpAddressFromRequest(request);

        if (service.isBlacklisted(ip)) {

            View blockedView = thymeleafViewResolver.resolveViewName("blacklisted.html", Locale.getDefault());

            if (blockedView != null) {
                blockedView.render(Map.of(), request, response);
            }
            return false;
        }
        return true;
    }
    
остана само service-а където е логиката за проверката, кои ip-та трябва да бъдат blacklist-нати.

      @Service
      public class BlackListService {

        public boolean isBlacklisted(String ipAddress) {
        
         return ipAddress.startsWith("102") || ipAddress.startsWith("129") || ipAddress.startsWith("196");

    }
}

След твоя отговор, гледайки кода си ми възникват следните въпроси и неясноти като цяло:
1.Все още не разбирам къде трябва да наместя тази логика с псевдо кода ?
2.Как всъщност проверяваме дали е allowed в if проверката от псевдо кода ?
3.request.getRequestURI() връща само / при мен, не разбрах как върна при теб /css/style.css ?

Какво да ти кажа.. Направо манджа.. А след всеки твой отговор относно тоя интерсептор съм - аааа ясно, ето как ставало, след тва бързам веднага да влезна в идето да го напиша докато съм го уж разбрал чувствайки се умен, после следва гледане като теле в зеле и 2-3 часа се чувствам тъп. Дано не ставам досаден вече с тея въпроси, ако да извинявам се, просто не искам да се отказвам.

Поздрави!
А.

**Comment by thrako** [comment]
Здравей,

И на мен горното ми се вижда много сложно (на този етап). Аз реших въпроса по-кардинално: ако user-ът няма право на достъп до съдържанието просто хвърлям ResponseStatusException(HttpStatus.FORBIDDEN). Спринг автоматично пренасочва към error страницата, пътят, към която предполагам ти е с permitAll достъп и съответно би трябвало да имаш всички css-и и картинки. 

Целият клас - > [линк](https://github.com/thrako/receptaria/blob/main/src/main/java/dev/thrako/receptaria/web/interceptor/ContextAuthorizationInterceptor.java) 

Поздрави,
Траян

**Comment by luchob** [comment]
Здравей! 

Може би аз съм се изказал малко неразбираемо. Това, което имах предвид е, че може да дадем достъп дори на блеклистнатите юзъри до нашите статични ресурси - картинки и css-и. Защо не, щом е необходимо да е красиво? Може да стане много лесно, например ако ползваме нещо съвсем готово и познато от настройките на секюритито. Например така:

```
@Override
    public boolean preHandle(HttpServletRequest request,
                             HttpServletResponse response,
                             Object handler)
            throws Exception {
        String ip = getIpAddressFromRequest(request);
        RequestMatcher staticResourceRequestMatcher = PathRequest.toStaticResources().atCommonLocations();
        
        if (!staticResourceRequestMatcher.matches(request) && service.isBlacklisted(ip)) {
            View blockedView = tlvr.resolveViewName("blacklisted.html", Locale.getDefault());

            if (blockedView != null) {
                blockedView.render(Map.of(), request, response);
            }
            return false;
        }
        return true;

    }
```

Ако пък не искаш така, спокойно можеш да inline-ш css-a и картинката в html-a. Също опция. 

Защо на теб ти връща `/`? Ами защото те са няколко заявки поред. Първата е за `/`, след това следва една за css-a и една за картинката. Може да ги видиш в dev конзолата на браузъра.

Поздрави,
Л.

**Comment by Alexander-Kostov** [comment]
Успях! Най-накрая css-a тръгна. Със снимката обаче възникна друг проблем. Мисля, че правилния подход за снимката би трябвало да е така нали:

    RequestMatcher image = PathRequest.toStaticResources().at(StaticResourceLocation.IMAGES);

Проблема обаче, е че при мен папката със снимките се казва img, а enum-а от StaticResourceLocation отговаря за този патърн - "/images/**" 

Опитах по следния начин чрез метода valueOf, който приема Стринг, но ми гърми с 500.

    RequestMatcher imageMatcher = PathRequest.toStaticResources().at(StaticResourceLocation.valueOf("/img/**"));

        if (!staticResourceRequestMatcher.matches(request) && service.isBlacklisted(ip) && !imageMatcher.matches(request))... 

Ето и грешката
        
     jakarta.servlet.ServletException: Request processing failed: java.lang.IllegalArgumentException: No enum constant org.springframework.boot.autoconfigure.security.StaticResourceLocation./img/**

**Comment by Alexander-Kostov** [comment]
Оправих го по следния начин. Благодаря много за търпението и помощта!

RequestMatcher imageMatcher = AntPathRequestMatcher.antMatcher("/img/**");
