### ISSUE TITLE
Проблем с тестовете

### ISSUE THREAD

**Issue by GeorgiPetrov4400** [luchob/softuni-feb2023#119]
Здравей, 

Опитвам се да направя тестовете като тези които ни показа на лекцията, но не ми се получава нито на unit теста за testUserRegister, който се намира в UserServiceImplTest, нито на integration теста testRegistration, който се намира в UserControllerIT. Ако може малко помощ какво трябва да направя :) В integration test когато напиша ".with(csrf()))" ми свети в червено и дори и като се опитах ръчно да му напиша импорта пак не става и продължава да свети в червено.
Линк към Гитхъб проекта ми: https://github.com/GeorgiPetrov4400/Trading-Forecasts/tree/main/TradingForecasts/TradingForecasts 

Благодаря предварително

**Comment by GeorgiPetrov4400** [comment]
Integration теста го оправих. Бях забравил едно dependency и затова ми светеше в червено този csrf :)

**Comment by luchob** [comment]
Здравей!

Когато правиш unit тестове, трябва да забравиш за Спринг. Там нямаш реални сървиси, репозиторита и т.н. Всичко е един mock (с единствено изключение на обекта, който тестваш) и ако не го "обучиш" да прави нещо, всеки негов метод винаги ще ти връща: `0`, `null`, `false` или `Optional.empty()`. Все едно няма спринг, нито каквато и да е функционалност свързана със спринг.

За да не звучи голословно, например леко преработения ти тест може да изглежда така:

```
@Test
    void testUserRegister() {

        when(mockUserRoleService.findUserRole(UserRoleEnum.User)).thenReturn(Optional.of(
            new UserRole().setRole(UserRoleEnum.User)
        ));

        UserServiceModel testUserServiceModel = new UserServiceModel()
                .setEmail("test@example.com")
                .setUsername("Test")
                .setPassword("12345")
                .setConfirmPassword("12345")
                .setFirstName("Tester")
                .setLastName("Testov")
                .setUserRole("User");

        toTest.registerUser(testUserServiceModel);

        Mockito.verify(mockUserRepository).save(any());
    }
```

Въпреки че е готино да се провери какво точно енитити е записано, например с argument captor.

Поздрави,
Л.

**Comment by GeorgiPetrov4400** [comment]
Благодаря :)
