### ISSUE TITLE
Имам нужда от помощ - IDE-то спря да създава таблици

### ISSUE THREAD

**Issue by borisboev79** [luchob/softuni-feb2023#12]
Здрасти, Лъчо. Знам, че питането ми звучи абсурдно, но вече часове се боря и без резултат. 

Правех си моя проект и му прилагах секюритито от последната лекция. В един момент видях, че не работи, както се очаква - нещо каквото и да правех, както го правиш ти в лекцията, не ми се криеха примерно бутоните, според ролята на потребителя. В един момент осъзнах, че съм на таймлийф-екстрас-секюрити5, вместо на 6, смених го и привидно тръгнаха нещата, но в един момент на localhost:8080 спря да ме пуска на индекс странцата, а започна да ми иска юзър и парола - този стандартния прозорец на секюрити. Реших да дропна базата и да я вдигна отначало, пре-импортнах всички депендънсита и тогава установих, че таблиците не се създават. В момента положението е такова, че дори ето това приложение, не вдига двете прости таблички в базата:
https://github.com/borisboev79/Proba

Всякаква помощ ще е добре дошла. Благодаря!

**Comment by luchob** [comment]
Здравей!

Това какво прави хибернейт след стартиране зависи от следната настройка:

```
  jpa:
    hibernate:
      ddl-auto: update
```

Стойностите са както следва:

```
none - No action is performed. The schema will not be generated.
create-only - The database schema will be generated.
drop - The database schema will be dropped.
create - The database schema will be dropped and created afterward.
create-drop - The database schema will be dropped and created afterward. Upon closing the SessionFactory, the database schema will be dropped.
validate - The database schema will be validated using the entity mappings.
update - The database schema will be updated by comparing the existing database schema with the entity mappings.
```

При `update` би трябвало да сработи ако си дропнал базата. Пробвай и с `create`. Когато свалих приложението ти (Proba) го пуснах с update както е и създаде двете таблички без проблем или ексепшън.

Опитай:

1. Да дропнеш базата
2. Провери дали MySQL работи и креденшълите ти са правилни
3. Стартирай приложението с update
4. Виж дали има някакъв ексепшън, който се изпечатва в конзолата.

Поздрави,
Л.

**Comment by borisboev79** [comment]
Привет. Опитах всичко гореописано преди да си позволя да те тормозя. Нищо не става. Тотално съм объркан вече. Старите приложения си стартират, при адресиране на базата си теглят, записват, но всичко ново, което се опитам да създам, увисва. Няма грешки, няма нищо. В пълен шах съм от вчера привечер. А всичко вървеше доста добре. Ъпдейтнах MySQL сървъра до последна версия, ресетнах IntelliJ до дефолтни настройки - нищо. Бих ти дал ремоут достъп през AnyDesk дори, ако желаеш ти или колега, ще си платя за услугата, ако някой може да помогне, защото времето тече, а аз не мога да работя. Остана да преинсталирам изцяло MySQL и J кънекшъна. Друго не се сещам.

**Comment by luchob** [comment]
Ще го оправим, споко. Като пуснеш приложението от IntelliJ, каво се изписва в конзолата?
Вероятно има някакъв проблем при теб, защото при мен тръгва примерното ти приложение.

**Comment by borisboev79** [comment]
![IDE](https://user-images.githubusercontent.com/83350776/221546830-d8f8414e-385c-4a3e-a5c3-e3a45fa1efb2.jpg)
Това излиза - нищо притеснително или нещо, което да ми подскаже накъде да продължа

**Comment by luchob** [comment]
Супер, и при мен се стартира, когато го пусна. Само че трябва да оправя ето това в InitService:

```
.branch(this.branchRepository.findByName("Head Office").orElseThrow())
```

Frontend-ът изглежда малко унило, но работи на порт 8080:

<img width="519" alt="Screenshot 2023-02-27 at 13 24 27" src="https://user-images.githubusercontent.com/10339738/221551665-2b076fdb-7ecb-497d-bca9-f436b18fc410.png">

ДБ-то е пълно:

<img width="519" alt="Screenshot 2023-02-27 at 13 24 27" src="https://user-images.githubusercontent.com/10339738/221551800-4b4e717d-dd0a-4fe3-a317-82203d47bed9.png">

При теб излиза ли нещо на localhost:8080? В ДБ-то с име cruise-groups какво има? Увери се че има процес на MySQL на 3306, закачи се с някакъв клиент дето няма нищо общо със спринг.

**Comment by borisboev79** [comment]
Е, хайде сега унило :) нещо не са се качили ресурсите в репото, не знам що, а този фронтенд е подпрян с дъски и вързан с тел, докато оправя функционалността и логиката, после ще правя фасадата красива. Проблемът е, че при мен проблемът продължава. Сега се опитвам да оправя целия mySQL - от доста време инсталарът реконфигурира сървъра и нещо го гледам, че се опитва да се връзва към някакви стари конекции, които вече ги няма, та си мисля, че ако до довечера не мине тоя уизард, ще махам всичко и ще преинсталирам сървъра, J connection и Workbench от нула. Нямам нещо безценно да губя

**Comment by luchob** [comment]
Добре, да видим какво ще стане. Дотогава затварям този бъг ако има нещо несвързано с инсталацията на MySQL съм насреща :-)
