### ISSUE TITLE
проблем с коментарите

### ISSUE THREAD

**Issue by StefanPYordanov** [luchob/softuni-feb2023#121]
Здравейте,

Бих желал да Ви помоля, да погледнете къде греша при коментарите, все не успявам да ги направя да работят. Намират се на  endpoint /details/1 а в html са в book-details.
Благодаря Ви предварително.
Поздрави,
Стефан

https://github.com/StefanPYordanov/BookLibrary

**Comment by luchob** [comment]
Здравей! 

js-a в `/details/{id}` не ти се зарежда. Тази и други подобни грешки можеш да ги гледаш в dev конзолата. Ето как например. Отваряш  `/details/{id}` и поглеждаш:

<img width="493" alt="Screenshot 2023-04-05 at 19 48 37" src="https://user-images.githubusercontent.com/10339738/230149397-2fda38fe-30b2-4a83-980c-6ba771dd932d.png">

Значи нещо не е наред в comments.js на ред 1. Нека погледнем:

<img width="502" alt="Screenshot 2023-04-05 at 19 50 38" src="https://user-images.githubusercontent.com/10339738/230149624-01146341-8aaf-4a8a-bb36-ffdc490095c4.png">

Ами няма елемент `routeId`. Този елемент е странен за сайт с книги, изглежда като копнат от pathfinder :-) 

Поздрави,
Л.
