### ISSUE TITLE
Integrational Test Problem

### ISSUE THREAD

**Issue by yanamet** [luchob/softuni-feb2023#122]
Здравей, Лъчо :) 
От няколко дни ме мъчи един тест и все не разбирам къде греша. Тестът е ReservationControllerIT. GetMapping-а ми работи, но PostMapping-а - не. Мислех, че може да греша някъде в URL, но тогава би ми връщало по-скоро статус 404. Въпреки че съм анотирала с @WithMockUser(username = "GUEST", roles = {"GUEST"}), ми връща грешка.

MockHttpServletResponse:
           Status = 403
    Error message = Forbidden

Ако може да помоля за някакви насоки, ще бъда много благодарна :) 

Линк към проекта ми -> https://github.com/yanamet/HotelAntique

Поздрави, 
Яна

**Comment by luchob** [comment]
Здрасти, Яна! Как е :-)

Проблемът ти е идентичен с този на колежката -> https://github.com/luchob/softuni-feb2023/issues/101

Поздрави,
Л.
