### ISSUE TITLE
Проблем с добавянето на прогноза

### ISSUE THREAD

**Issue by GeorgiPetrov4400** [luchob/softuni-feb2023#123]
Здравей,

До вчера нямах проблем с AddForecast който се намира в ForecastAddController, а днес когато се опитам да добавя forecast и след като натисна бутона Add ми излиза грешка 500, но в същото време прогнозата ми е добавена в базата и след това мога да ги видя от Orders. Незнам дали не съм счупил нещо днес при писането на тестовете и ако може да ми помогнеш за да отсраня проблема. Също така ще те помоля да ми дадеш идея как да направя един forecast да си излиза само с неговата снимка от Клаудинари в Orders, тъй като в момента ми ги зарежда всичките които са добавени :)
Ако може и малко помощ за последния тест от ForecastAddControllerIT за добавяне на валидна прогноза тъй като нещо не мога да го измисля и него и ми дава грешка при редирект.
Линк към Гитхъб проекта ми: https://github.com/GeorgiPetrov4400/Trading-Forecasts/tree/main/TradingForecasts/TradingForecasts 

Благодаря предварително.

**Comment by GeorgiPetrov4400** [comment]
Сега разбрах, че проблема ми с AddForecast идва след като смених application.properties с application.yml :) След като оправих настройките в yml файла и AddForecast работи отново без да ми хвърля грешка 500.
Ако може само малко помощ да направя един forecast да си излиза само с неговата снимка от Клаудинари в Orders, тъй като в момента ми ги зарежда всичките които са добавени и за последния тест от ForecastAddControllerIT за добавяне на валидна прогноза тъй като нещо не мога да го измисля и него и ми дава грешка при редирект.
Благодаря предварително!

**Comment by GeorgiPetrov4400** [comment]
Cloudinary също го оправих и всяка прогноза си излиза точно с нейната снимка която трябва да е :)

**Comment by luchob** [comment]
Здравей! 

Това което видях в теста след коментиране на малко странния setUp e следното. Ето го контролера:

``` 
@PostMapping("/add")
    public String addForecast(@Valid ForecastAddDTO forecastAddDTO,
                              BindingResult bindingResult,
                              RedirectAttributes redirectAttributes,
                              Principal principal) {

        if (bindingResult.hasErrors()) {
            redirectAttributes.addFlashAttribute("forecastAddDTO", forecastAddDTO)
                    .addFlashAttribute("org.springframework.validation.BindingResult.forecastAddDTO",
                            bindingResult);

            return "redirect:add";
        }
``` 

Ето го и теста:

```
mockMvc.perform(MockMvcRequestBuilders.post("/forecasts/add")
``` 

Естествено това няма да мине, ще има грешка тук:

```
public class ForecastAddDTO {

    @NotNull
    private MultipartFile pictureUrl;

```
Естествено няма файл, тъй като рикуеста не е multipart, както е формата ти:

``` 
<form th:action="@{/forecasts/add}" 
           th:method="post" th:object="${forecastAddDTO}" enctype="multipart/form-data"
          class="mx-auto w-25 bg-blur rounded">
``` 

Намери някоя готина статийка как се праща мултипарт рикуест с mockMvc, защото е по-дългичко за обяснение. Ето случаен пример:

https://www.baeldung.com/spring-multipart-post-request-test

Поздрави,
Л.

**Comment by thrako** [comment]
Здравей Георги,

От няколко часа се боря с този multipart request и едва преди малко го подкарах (още не съм commit-нал дори), така че, за да ти спестя малко време, ето как става:
```
File imageFile = new File("src/test/resources", "testImgOne.png");

        MockMultipartFile imageMultipartFile
                = new MockMultipartFile(
                        "fileData",
                        imageFile.getName(),
                        "image/png",
                        Files.readAllBytes(imageFile.toPath()));

        mockMvc.perform(multipart("/api/photos/temp/upload")
                      .part(new MockPart("fileData",
                                         imageFile.getName(),
                                         imageMultipartFile.getBytes()))
                      .contentType(
                              "multipart/form-data; boundary=----WebKitFormBoundaryk1fn4D7ebCjmFPHl")
                      .param("description", "testDescription")
                      .param("tempRecipeId",
                             recipeBM.getTempRecipeId().toString())
                      .with(csrf())
                     .andExpect(status().is2xxSuccessful())
                    // и нататък си знаеш...
```

Хайде, успех на изпита и следващата Java бира е от теб ;)

**Comment by GeorgiPetrov4400** [comment]
Благодаря за съветите :) Бири ще има задължително :)
