### ISSUE TITLE
./gradlew clean build failed

### ISSUE THREAD

**Issue by Maria-Pavlova** [luchob/softuni-feb2023#124]
Здравей Лъчо, при опит да build -na получавам този ферман. Почетох за проблема, но не ми е ясно как точно да се справя, а и се страхувам да експериментирам 3 дни преди защита. Моля за помощ.
![image](https://user-images.githubusercontent.com/104596493/230164764-1126c153-007e-4ba7-bffe-ca2b77009a29.png)
![image](https://user-images.githubusercontent.com/104596493/230164899-9abed6a2-3ca8-40d4-8dd0-3c8ecb927918.png)

https://github.com/Maria-Pavlova/HomeExchange_SimpleVersion

**Comment by luchob** [comment]
Здрасти!

А `java --version` какво дава?

Поздрави,
Л.

**Comment by Maria-Pavlova** [comment]
Дава 17.0.6 вече. Но до вчера се оказа, че е била 15. Проекта е създаден със 17, която реално съм нямала, но сетнах Gradle JVM на 17. И пак е същото.

**Comment by luchob** [comment]
Добре, а `./gradlew -v` какво дава?

**Comment by Maria-Pavlova** [comment]
![image](https://user-images.githubusercontent.com/104596493/230296801-3be6964d-8d97-4ee8-b75f-1db3caf9d214.png)
Eto разликата

**Comment by Maria-Pavlova** [comment]
Остава да сетна успешно JAVA_HOME

**Comment by luchob** [comment]
Ups :-) 15.0.2. Т.е. не е на 17, както и предположихме...

Я провери сега каква е стойността на JAVA_HOME environment variable. 

Тъй ли се проверяваше? echo %JAVA_HOME%

**Comment by luchob** [comment]
Мислим в една посока май :-) Просто не е инсталирано напълно както трябва новото JDK. Ако не се лъжа gradlew му хвърля едно око. Даже ако хвърлиш едно очо на gradlew.bat вътре има:

```
@rem Find java.exe
if defined JAVA_HOME goto findJavaFromJavaHome
``` 

:-) 

Мисля, че с това проблемът ще се реши.

Поздрави,
Л.

**Comment by Maria-Pavlova** [comment]
Имам вече заветния jar. Благодаря :-)
