### ISSUE TITLE
Проблем с логин и тестове

### ISSUE THREAD

**Issue by msaeva** [luchob/softuni-feb2023#125]
Здравей Лъчо, 
Имам проблем с логването на потребителя, сега забелязах, че с дадени user-и се логвам без проблем, но с други не успявам (имам seeder class, в който си е написана паролата каква е преди да  бъде  encode). Следователно и change-password метод не ми работи, след като сменя парола не съм имала успешен опит за логване.
Също така, друг проблем, в който не мога да намеря решение е, integration test, изписва 'Error creating bean with name', става въпрос за CommentControllerTest и UserControllerTest

проблемите се намират в бранч mmusic-12
https://github.com/msaeva/MMusic 

Благодаря предварително за отделеното време и хубав ден !

**Comment by luchob** [comment]
Хаха, първият ти проблем е много забавен, защото като го гледаш първоначално имаш чувство че някой ти се подиграва :-)) 

Но дебъгера разкрива истината и тя е:

```
                .usernameParameter(UsernamePasswordAuthenticationFilter.SPRING_SECURITY_FORM_USERNAME_KEY)
                .usernameParameter(UsernamePasswordAuthenticationFilter.SPRING_SECURITY_FORM_PASSWORD_KEY)
``` 

``` 
                .usernameParameter(UsernamePasswordAuthenticationFilter.SPRING_SECURITY_FORM_USERNAME_KEY)
                .passwordParameter(UsernamePasswordAuthenticationFilter.SPRING_SECURITY_FORM_PASSWORD_KEY)
``` 

Така си казала, че параметъра където е username-a се казва password. И всъщност успяваш да се логнеш само когато username-a и password-a са еднакви.

**Comment by luchob** [comment]
За втория проблем, освен това казва:
```
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'mail.host' in value "${mail.host}"
```

Колегата имаше същия проблем. Тук -> https://github.com/luchob/softuni-feb2023/issues/112

Хубав ден,
Л.
