### ISSUE TITLE
Проблем с delete метод

### ISSUE THREAD

**Issue by AtanasKaloyanov** [luchob/softuni-feb2023#127]
Здравей, Лъчо!

Проблемът ми е свързан с delete method в BookController-a, който трябва да се изпълни във фронтенда чрез details.html
файла. След логване, добавяне на книга при опит на триене на която и да е от книгите хвърля грешка 405. Това е линкът към приложението ми - https://github.com/AtanasKaloyanov/Libra

Поздрави!

**Comment by luchob** [comment]
Здрасти!

Да почнем поред - направили сме форма с delete метод и delete mapping => трябва да работи :-)

Обаче, то ни казва - методът не е позволен => не намира мапинга.

Помниш ли като говорихме, че браузъра като има форма може да пуска само POST или GET заявки? Не може DELETE. Затова thymeleaf прави малка дяволия - обръща твоя метод от DELETE в POST и слага едно скрито поленце за да подскаже на сървъра, че е правил дяволии. Отвори HTML-а който се генерира в браузъра и го разгледай.

Да де, ама за да сработи тази дяволия, трябва да се направи дяволия и на сървъра. И това става с една малка настройчица, която благодарение на скритото поле прави обратния превод - превръща POST в DELETE.  Ето я и настройката:

https://github.com/luchob/softuni-feb2023/blob/main/mobilele/src/main/resources/application.yml#L12-L15

Поздрави,
Л.
