### ISSUE TITLE
проблем с тестове

### ISSUE THREAD

**Issue by StefanPYordanov** [luchob/softuni-feb2023#129]
Здравейте,

Първо се извинявам за това, че Ви безпокоя, но не се справям с това да разбера, защо при тест на контролера, не ми прави MockMvc на бийн. имам тест на RegisterController, но постоянно гърми, ще бъде благодарен ако може да погледнете.

Поздрави!

https://github.com/StefanPYordanov/BookLibrary

**Comment by luchob** [comment]
Здравей! 

Проблемът е идентичен на този -> https://github.com/luchob/softuni-feb2023/issues/79

Поздрави,
Л.
