### ISSUE TITLE
Имам нужда от помощ, когато регистрирам клиент не го логва автоматично 

### ISSUE THREAD

**Issue by ViliIlieva** [luchob/softuni-feb2023#13]
https://github.com/ViliIlieva/MyKnitShop
правя всичко като от миналогодишната ти лекция, когато регистрирам юзър не иска директно да го логне като на лекцията

**Comment by luchob** [comment]
Здравей! 

Няма да се логне автоманично, трябва да го завършим днес. Оставям това issue отворено, за да го затворим довечера.

Поздрави,
Л.

**Comment by ViliIlieva** [comment]
Аз гледах лекцията от предходния модул и там се логваше и по нея го правих уж, но явно нещо пропускам

**Comment by luchob** [comment]
Не, нищо не пропускаш :-) Това е заради upgrade-a до Спринг 3. Не съм му обърнал внимание и аз. Ако имам време ще го оправя до довечера, ако не ще остане за следващата лекция и там ще го оправим с всички. Преди това ще пиша в този бъг за да коригираме регистрацията и в твоя проект. Оставям issue-то отворено.

Поздрави и доскоро,
Л.

**Comment by ViliIlieva** [comment]
Благодаря

**Comment by ViliIlieva** [comment]
Лъчо а дали можеш да погледнеш, защото след снощната лекция днес цял ден се мъча, защо при логване с грешни данни не ми излиза че имам Грешна комбинация от юзър и парола.

Поздрави и дано не ми се налага скоро пак :)

**Comment by luchob** [comment]
:-) Ще го погледна по-късно. За сега се позанимавах с autologin-a и направих 1 PR-че с първо решение, може да го разгледаш. https://github.com/ViliIlieva/MyKnitShop/pull/1

**Comment by ViliIlieva** [comment]
Благодаря много! Нямам нищо спешно, аз се опитвам да оправям и html-ите

**Comment by luchob** [comment]
Този път проблема е доста по-тривиален. Не си позволила правилно редирект към логин грешката. Липсва наклонена черта:

```
requestMatchers ("/", "/login", "/register", "/about", "/product", "login-error").permitAll ().
```

Трябва да е:

```
requestMatchers ("/", "/login", "/register", "/about", "/product", "/login-error").permitAll ().
```

Тъй като не го разпознаваше в патърна редиректа отиваше към забранена според spring security страница. А когато стане това, отиваш на логина.

Ще затворя това issue, а ако намерим по-елегантно решение за auto login-a ще пиша.

Поздрави,
Л.
