### ISSUE TITLE
Forbidden Delete Mapping

### ISSUE THREAD

**Issue by rnaneva** [luchob/softuni-feb2023#131]
Здравей,
не ми разрешава да изтрия снимка, моля за помощ какво пропускам:
Request URL: http://localhost:8080/api/offers/1112/pictures/5
Request Method: DELETE
Status Code: 403 
Remote Address: [::1]:8080
Referrer Policy: strict-origin-when-cross-origin

PictureRestController и upload-images.js
https://github.com/rnaneva/Project-my-home/tree/master

**Comment by luchob** [comment]
Здравей!

Звучи ми сякаш проблема е идентичен на този -> https://github.com/luchob/softuni-feb2023/issues/111

Може ли да потвърдиш?

Поздрави,
Л.

**Comment by rnaneva** [comment]
Здравей,

Точно това беше, благодаря за бързата реакция!

Поздрави,
Ралица
