### ISSUE TITLE
Не мога да визуализирам инструментите с fetch.

### ISSUE THREAD

**Issue by MarinaVaneva** [luchob/softuni-feb2023#132]
GH URL: https://github.com/MarinaVaneva/toolShop
Problem:  Опитвам се като натисна бутона TOOL да ми се визуализират инструментите от базата но не ми се получава. Искам да добавя и снимка към тях и бутон : купи. След това да ги добавям в кошница. Моля за насоки :)

**Comment by luchob** [comment]
Здравей!

Ами... насоките ще са твърде общи :-) Предполагам, искаш да постигнеш това със rest API/java script. В такъв случай би могла да  направиш include на JS script на дъното на файла. За пример погледни упражнението ни с книжките. Във въпросите има затворени на много колеги, които са се опитвали и са успели да направят нещо подобно.

Ако искаш server-side render-инг трябва да направиш модел и да го напълниш с информация преди визуализацията на страницата. За пример може да видиш mobilele и страничката с офертите. 

За останалите неща също сме бъбрили доста в курса, но има и колеги с подобни проекти. Разгледай затворените въпроси и може да намериш примерни имплементации.

Поздрави,
Л.

**Comment by MarinaVaneva** [comment]
Много благодаря за насоките. 
Поздрави,
Марина
