### ISSUE TITLE
Не ми се смей, но това не мога да го оправя :)

### ISSUE THREAD

**Issue by borisboev79** [luchob/softuni-feb2023#133]
Здрасти,

Ако имаш време да погледнеш тук:

https://github.com/borisboev79/JavaWeb-ExamPrep-GiraApp

ще съм ти благодарен да ми подскажеш защо th:errorclass на селекта на add-task.html чупи страницата.

Това съм го правил вече толкова пъти, че изумявам каква е причината и защо не я виждам.

Мерси предварително!

Поздрави,
Боби

**Comment by luchob** [comment]
Всичко е ок? :-)

**Comment by borisboev79** [comment]
Страшна тъпотия, както очаквах :) Добре, че си я намерих в крайна сметка
