### ISSUE TITLE
PVC

### ISSUE THREAD

**Issue by lamenco** [luchob/softuni-feb2023#14]
Здравей, като направих нов файл в messages.properties ,  и всичко вече излиза на български, но нищо не се променя като  езика.
Единствено ако добавя classpath в "  resourceBundleMessageSource.setBasename("classpath:i18n/messages");", започват да ми излизат пак  думите с въпроси отпред и отзад, но тогава поне се сменят. Не знам гледах и рових къде ли не в интернет и не разбирам защо не ми се сменя.
Относно тестовете, не разбирам защо не може да ме допусне за заявки след като използвам
   @BeforeEach
    void setUp() {
        testUser = new User("admin", "Admin", "a@a", "123",
                List.of(new UserRole().setUserRole(UserRoleEnum.USER),
                        new UserRole().setUserRole(UserRoleEnum.ADMIN)));

        testOffer = new Window(111,125,new Model(ModelEnum.VIVAPLAST),new Colors(ColorsEnum.WHITE),
                new Chambers(ChamberEnum.FIVE_CHAMBER), BigDecimal.valueOf(12),testUser);
    }
Ако можете изтегледете файла PVC.rar и да погледнете заяките testLoginDelete()  и testAddWindow() 
https://github.com/lamenco/Window-Shopper

Съжалявам че ви занимавам толкова често.

**Comment by luchob** [comment]
Здравей! 

Бърз отговор на въпроса за `testAddWindow()`. Ползваш `@AuthenticatedPrincipal` с твоя юзър, но това не работи с `@WithMockUser`. Опитай с `WithUserDetails`. Повече за това може да разбереш тук, в т. 11.4:

https://docs.spring.io/spring-security/site/docs/4.2.x/reference/html/test-method.html#test-method-withuserdetails

**Comment by lamenco** [comment]
Направих го и стана, Благодаря!
На теста когато съм логнат и искам да изтрия, ми излиза
 Expected :REDIRECTION
Actual   :CLIENT_ERROR

**Comment by luchob** [comment]
Здравей отново! Да разгледаме следващия тест с логин и триене. По специално логовете:

```
MockHttpServletRequest:
      HTTP Method = DELETE
      Request URI = /cart/deleteWindow/
       Parameters = {_csrf=[7d26b9d5-a47b-4802-b11e-a0a2a76cf0b0]}
          Headers = []
             Body = null
    Session Attrs = {SPRING_SECURITY_CONTEXT=SecurityContextImpl [Authentication=UsernamePasswordAuthenticationToken [Principal=org.springframework.security.core.userdetails.User [Username=admin, Password=[PROTECTED], Enabled=true, AccountNonExpired=true, credentialsNonExpired=true, AccountNonLocked=true, Granted Authorities=[ROLE_ADMIN, ROLE_USER]], Credentials=[PROTECTED], Authenticated=true, Details=null, Granted Authorities=[ROLE_ADMIN, ROLE_USER]]]}

Handler:
             Type = org.springframework.web.servlet.resource.ResourceHttpRequestHandler

MockHttpServletResponse:
           Status = 404
    Error message = null
          Headers = [Vary:"Origin", "Access-Control-Request-Method", "Access-Control-Request-Headers", X-Content-Type-Options:"nosniff", X-XSS-Protection:"1; mode=block", Cache-Control:"no-cache, no-store, max-age=0, must-revalidate", Pragma:"no-cache", Expires:"0", X-Frame-Options:"DENY"]
     Content type = null
             Body = 
    Forwarded URL = null
   Redirected URL = null
          Cookies = []
```

Пратил си DELETE рикуест на url `/cart/deleteWindow/` и то естествено ти е върнало 404 - not found. Очевидно би трябвало да е  нещо от сорта на `/cart/deleteWindow/1234`. Т.е. трябва да създадеш офертата в ДБ преди да пуснеш теста. 

Поздрави!

**Comment by lamenco** [comment]
Здравей,
използвам да създам офертата и потребителя така

   @BeforeEach
    void setUp() {
        testUser = new User("admin", "Admin", "a@a", "123",
                List.of(new UserRole().setUserRole(UserRoleEnum.USER),
                        new UserRole().setUserRole(UserRoleEnum.ADMIN)));
      
        testOffer = new Window(111, 125, new Model(ModelEnum.VIVAPLAST), new Colors(ColorsEnum.WHITE),
                new Chambers(ChamberEnum.FIVE_CHAMBER), testUser);
    }

и 
  @Test
    @WithMockUser(
            username = "admin",
            roles = {"ADMIN", "USER"}
    )
    void testLoginDelete() throws Exception {
        mockMvc.perform(delete("/cart/deleteWindow/{id}", testOffer.getId())
                        .with(csrf())).
                andExpect(status().is3xxRedirection()).
                andExpect(redirectedUrl("/cart"));
    }

Интересното е, че преди ми работеше, не знам какво обърках. Дори и да сетна Id-to на офертата с 1 и после да сложа след /deleteWindow/1 пак гърми.

Благодаря!

**Comment by luchob** [comment]
:-) Не може да я сетнеш, защото в ДБ няма оферта с но.1. Трябва ти не нещо такова:

```
     testOffer = new Window(111,125,new Model(ModelEnum.VIVAPLAST),new Colors(ColorsEnum.WHITE),
            new Chambers(ChamberEnum.FIVE_CHAMBER), BigDecimal.valueOf(12),testUser);
```

А по-скоро нещо такова. 

        testOffer = testDataUtils.createTestOffer(testUser);

Разбира се, трябва да се справиш с [подобни проблеми](https://stackoverflow.com/questions/2302802/how-to-fix-the-hibernate-object-references-an-unsaved-transient-instance-save).

**Comment by luchob** [comment]
За езиците. Ако гледаш в Network таба трябва да ти сетва куукие, ако работи интерсептора:

<img width="723" alt="Screenshot 2023-03-02 at 17 02 39" src="https://user-images.githubusercontent.com/10339738/222466223-f9300513-1b57-4370-b0c9-5a42bb20521d.png">

Иначе не знам какво да ти кажа, при мен работи без драма, това поне което свалям от твоето репозитори в rar файла. :( И конфигурацията ми изглежда ок.

Като добавя цялостен дебъг в `application.properties`:

```
logging.level.org.thymeleaf=TRACE
logging.level.org.springframework=DEBUG
```

Виждам, че всичко е ок.

```
2023-03-02 17:27:33.247 DEBUG 98686 --- [nio-8080-exec-9] o.s.security.web.FilterChainProxy        : Securing GET /?lang=bg_BG
2023-03-02 17:27:33.249 DEBUG 98686 --- [nio-8080-exec-9] o.s.s.w.a.i.FilterSecurityInterceptor    : Authorized filter invocation [GET /?lang=bg_BG] with attributes [permitAll]
2023-03-02 17:27:33.250 DEBUG 98686 --- [nio-8080-exec-9] o.s.security.web.FilterChainProxy        : Secured GET /?lang=bg_BG
2023-03-02 17:27:33.250 DEBUG 98686 --- [nio-8080-exec-9] o.s.web.servlet.DispatcherServlet        : GET "/?lang=bg_BG", parameters={masked}


2023-03-02 17:27:33.257 TRACE 98686 --- [nio-8080-exec-9] org.thymeleaf.TemplateEngine             : [THYMELEAF][http-nio-8080-exec-9] STARTING PROCESS OF TEMPLATE "index" WITH LOCALE bg_BG


2023-03-02 17:27:33.267 TRACE 98686 --- [nio-8080-exec-9] o.t.T.cache.EXPRESSION_CACHE             : [THYMELEAF][http-nio-8080-exec-9][EXPRESSION_CACHE][CACHE_HIT] Cache hit in cache "EXPRESSION_CACHE" for key "expr|#{navbar_login}".
2023-03-02 17:27:33.268 TRACE 98686 --- [nio-8080-exec-9] o.t.s.expression.MessageExpression       : [THYMELEAF][http-nio-8080-exec-9] Evaluating message: "#{navbar_login}"
2023-03-02 17:27:33.268 TRACE 98686 --- [nio-8080-exec-9] o.t.s.expression.GenericTokenExpression  : [THYMELEAF][http-nio-8080-exec-9] Evaluating generic token: "navbar_login"
2023-03-02 17:27:33.268 TRACE 98686 --- [nio-8080-exec-9] o.t.s.m.SpringMessageResolver            : [THYMELEAF][http-nio-8080-exec-9] Resolving message with key "navbar_login" for template "fragments/fragment" and locale "bg_BG". Messages will be retrieved from Spring's MessageSource infrastructure.
```

Не знам дали няма някакъв проблем от сорта на https://github.com/luchob/softuni-feb2023/issues/19

Но кодът е напълно ОК, работи при мен, не виждам нищо. Някакъв локален проблем има при теб :( Ако виждаш въпроси, означава че всичко сработва, но не намира правилен ключ в месидж сорса.
