### ISSUE TITLE
Частично изолирах проблема, мисля, че е полезно

### ISSUE THREAD

**Issue by borisboev79** [luchob/softuni-feb2023#15]
Привет, Лъчо!

След пълна преинсталация на системата от format C:\, в момента съм на гол Уиндоус 11, IntelliJ последна версия, Java SDK 17.06 директно от Оракъл и последните версии на MySQL сървър и J Connection - 8.0.32

Проблемът си стои, но установих къде се чупят нещата, като вероятно все още бих имал нужда от съдействие:
1. Първоначалните версии депендънситата, с които бях почнал разработката, бяха съответно, на Spring Boot - 3.0.2, а на Thymeleaf Security - 5. 
2. След като установих, че ограничаването на достъпа до меню елементите в navbar с .isAuthenticated() метода от таймлийф секюрити не работят, смених версията на 6 и привидно за малко тръгнаха, но след рестарт на приложението, директно ми изкара дефолтния логин екран на Спринг Секюрити. Затова питах как се маха.
3. Оказа се, че спринг секюрити буквално не вижда нищо от кода на тема секюрити, който съм написал и си пляска дефолтната страница, вероятно оттам и не вдига базата.
4. Отделно се оказа, че някъде между версиите на Спринг буут, подаването на данните от ентититата към mySQL е претърпяла известна разлика.
5. При мен на macBook Air M1, нещата тръгват от раз от грейдъл репото, което качих в гитхъба си, както и при теб вървят. Проблемът е, че като го клонирам на прясната инсталация на Windows 11 машината, стигам до същата задънена улица - приложението стартира, но изкарва дефолтния логин екран на секюрити и нищо повече, без да създаде таблиците. 
6. Създадох чисто нов грейдъл проект със съответните депендънсита, директно от сприн инишълайзъра онлайн и довечера сядам да пиша по него. Ще създам съвсем базова структура с юзър, роли и секюрити, преди да продължа нататък, и ще ти пиша, ако има проблем. 

Ако нещо от горепрочетеното ти светва някаква лампа дали пропускам нещо съществено, пиши, моля! Иначе мерси за вчерашната лекция, беше топ! Може би защото сме си набори, тотално те разбирам като обясняваш и показваш.

**Comment by borisboev79** [comment]
И само един бърз въпрос - нали няма нужда да имам отделна инсталация на Gradle, за да мога да имам работещ Gradle проект в IntelliJ?

**Comment by luchob** [comment]
Не, никога съм нямал инсталация на gradle :-) И грейдъл и мейвън имат wrapper-s, които са целия необходим туул.

**Comment by luchob** [comment]
:-) Какво става с уиндоуса? :-) Има един колега с проект за прозорци, но не се казва уиндоус, а PVC :-)

Знаеш ли, очевидно нещо е скапано не с кода, а с инсталацията затова защо не пуснеш приложението с голям дебъг:
```
logging:
  level:
    org.springframework: DEBUG
```

Пускаш го, вземаме лога. После пускаш страницата напр localhost:8080/something и виждаме какво става. Увери се че не си пуснал няколко spring приложения също :-)

Поздрави,
Л.

**Comment by borisboev79** [comment]
Много благодаря за...елементарното подсещане, че имаме и DEBUG, не само WARN.
Оркестър свири туш ииии умри от смях:
Оказа се, че просто не ми намира класовете на проекта, защото преди няколко дена прекръстих папката, в която стои и в името има просто един спейс. Махнах спейса и всичко тръгна както трябва. Но междувременно два пъти преинсталирах Уиндоус за здраве и берекет :facepalm:

**Comment by luchob** [comment]
Много е тъжно, да. Но понякога се случват такива неща. Ето, разконспирирахме го, но колегата Росен. Нямаше начин да се досетя особено с толкоз пресен проблем. Погледни тук:

https://github.com/luchob/softuni-feb2023/issues/19

Поздрави,
Л.

**Comment by borisboev79** [comment]
Да, и аз установих, че е заради версиите. Също като него минах от 3.0.2 на
3.0.3 и тогава започнаха проблемите
