### ISSUE TITLE
Проблем с BindingResult

### ISSUE THREAD

**Issue by msaeva** [luchob/softuni-feb2023#16]
Здравей Лъчо,
Срещам голям проблем с BindingResult, при регистриране изобщо не ми отчита валидациите. BindingResult винаги показва 0 errors.
https://github.com/msaeva/MMusic

Благодаря предварително!

**Comment by luchob** [comment]
Здравей! 

Проблемът не е в кода, а в `build.gradle`, по-конкретно ето тези 2 dependencies:

```
    // https://mvnrepository.com/artifact/jakarta.validation/jakarta.validation-api
    implementation group: 'jakarta.validation', name: 'jakarta.validation-api', version: '2.0.2'

    implementation 'org.springframework.boot:spring-boot-starter-validation:3.0.3'
```

Тук нередното е:

1. `spring-boot-starter-validation` няма нужда от версия. Спринг поставя такава вместо теб благодарение на този плъгин - `io.spring.dependency-management`. Т.е. той знае каква версия на валидациите е подходяща за спринг 3. И тя не е 3.0.3. Импортнала си доста стара версия. Трябва да е ето така: `implementation 'org.springframework.boot:spring-boot-starter-validation`
2. Това нещо не е необходимо, т.к. се съдържа във валидационния стартер: `implementation group: 'jakarta.validation', name: 'jakarta.validation-api', version: '2.0.2'`. Изтрий го.
3. Тъй като си импортнала стара версия на `spring-boot-starter-validation` навсякъде използваш пакет `javax.validation`. Например `import javax.validation.constraints.Size`. В новия Спринг, поради разни юридически трудности свързани с пускането на java EE open source, този пакет вече е `jakarta.validation`. Мини и замени `javax.validation` с `jakarta.validation`

Това трябва да е достатъчно.

Поздрави,
Л.

**Comment by msaeva** [comment]
Благодаря! Всичко сработи
