### ISSUE TITLE
Въпрос относно JS

### ISSUE THREAD

**Issue by ViliIlieva** [luchob/softuni-feb2023#17]
Днес успях да изгледам до края лекцията от понеделник. Понеже не съм минавала през модул JS исках да попитам, идеята ми е в моя проект да направя страница за админа, в нея да реждам всички продукти и всички поръчки, като продуктите да могат да се трият и редактират. Та това нещо как може да стане с JS да се вземат данните от базата а не от друг localhost. И проблем ли ще е ако е по този начин а не с Java? Дано да съм задала правилно въпроса си

А проблема с който се сблъсквам е че при products/add в web ми зарежда всички полета но ми дава грешка 404 в Network че не ми намира style и css файловете, мисля че някъде греша във securityConfiguration но не успях да се справя
https://github.com/ViliIlieva/MyKnitShop

**Comment by luchob** [comment]
Привет!

Относно въпрос но.1 си представям нещата по следния начин.

Стъпка 1) Извиква се един рикуест към **нормален** контролер, който отговаря с HTML страничка в която има линк към скрипт, напр `js/my-script.js`
Стъпка 2) Браузърът сваля `my-script.js`
Стъпка 3) `my-script.js` се изпълнява и праща REST request към сървъра и сваля някакви данни. 

Дано съм се изразил простичко, добавям и една картинка:

<img width="721" alt="Screenshot 2023-03-02 at 14 53 27" src="https://user-images.githubusercontent.com/10339738/222434266-3f3d0e72-bc26-4e00-b125-4cbb03c4beea.png">

**Comment by luchob** [comment]
Относно вторият ти проблем - той си е в HTML-a. Нека да разгледаме 2 примерни URL-та в HTML-a.

```
lib/owlcarousel/assets/owl.carousel.min.css
```

Това URL означава търсене релативно на текущия път. Например ако в URL бара на браузъра показващ страницата имаш:

http://localhost:8080/products/add

То ще се опита да зареди CSS-а от:

http://localhost:8080/products/lib/owlcarousel/assets/owl.carousel.min.css

Където естествено го няма -> 404.

Да видим другото URL при същата ситуация:

```
/lib/owlcarousel/assets/owl.carousel.min.css
```
Това вече търси абсолютно спрямо сървъра и ще се опита да зареди CSS-a от:
```
http://localhost:8080/lib/owlcarousel/assets/owl.carousel.min.css
```

 С две думи, слагай `/` отпред освен ако наистина имаш причина да го изтървеш :-)

Л.

**Comment by ViliIlieva** [comment]
Това беше първото което гледах, но вече ме заболя главата от търсене и съм го пропуснала. Отново благодаря!

**Comment by ViliIlieva** [comment]
Тръгнах да търся къде съм изпуснала тази черта, но в HTML във фрагмент във head всички lib са нормални. Странното е че Register работи със същия head фрагмент без проблем. След add ли трябва да има черта, защото логиката ми да не сложа е че след login и register няма такава черта

**Comment by luchob** [comment]
Има други линкове, които не работят. Търси ги, като гледаш кое мята 404 и му прави text serch. Ето, направих ти един PR. Подкарах и auto login-a беше много дебела работа, но може да го обсъдим и с другите. 

Поздрави,
Л.
