### ISSUE TITLE
file_path_problem

### ISSUE THREAD

**Issue by RosenMitrov** [luchob/softuni-feb2023#19]
Здравей Лъчо,

Имам технически проблем:

```
Зареждам проект с име "test" в който имам база с няколко ентитита, като таблици.
Проблемът е следния:
Ако директорията на проекта е например: Е:\SoftUni\All Projects\test  -> ми създава базата, но без таблиците в проекта.
Но ако директорията е Е:\SoftUni\Projects\test -> създава успешно всичко и установих, че проблема е в спейса на някоя от папките в пътя. 
```

До този момент нямах такъв проблем и всичко работеше добре.
Може ли малко насока какво точно да търся за да го оправя и да не се чупи, когато има такова име в пътя, понеже всички проекти са ми в подобни папки. 

Благодаря предварително!

Поздрави,
Росен

**Comment by RosenMitrov** [comment]
Здравей,

Малко ъпдейт по темата:

https://www.youtube.com/watch?v=5pLtEWy7ByA
https://github.com/spring-projects/spring-framework/issues/30031
https://github.com/spring-projects/spring-boot/issues/34379

Проблемът наистина се оправя като се върне от 3.0.3 на 3.0.2.

Поздрави,
Росен

**Comment by luchob** [comment]
Хаха :-) Яко! Ми... :-) Не съм сигурен как да коментирам ситуацията.

3.0.2 и чакаш да го оправят. Случват се такива неща.

Поздрави,
Л.
