### ISSUE TITLE
DeleteMapping

### ISSUE THREAD

**Issue by RosenMitrov** [luchob/softuni-feb2023#2]
Здравей Лъчо, 

Стигнах до работещо решение за DeleteMapping / deleteById(bookId), но не съм сигурен дали е правилно.

********************************************
Стъпка 1:
Създаване на наш exception -> EntityNotFoundExceptionById
********************************************

@ResponseStatus(HttpStatus.NOT_FOUND)  ****(като тук се чудих дали да сложа NO_CONTENT)
public class EntityNotFoundExceptionById extends RuntimeException {
    public EntityNotFoundExceptionById(String message) {
        super(message);
    }
}
********************************************
Стъпка 2:
Обработка на service ниво:
********************************************
    public void deleteById(Long bookId) { ****(тук опитах с try/catch, но нещо не се получи - но с тази проверка работи)
        if (!this.bookRepository.existsById(bookId)) {
            throw new EntityNotFoundExceptionById("Invalid id was provided");
        }
        this.bookRepository.deleteById(bookId);
    }
********************************************
На ниво контролер го оставих, както го написахме по време на лекцията. 
********************************************
    @DeleteMapping("/{id}")
    public ResponseEntity<BookDto> deleteBookById(@PathVariable("id") Long id) {
        this.bookService.deleteById(id);
        return ResponseEntity
                .noContent()
                .build();
    }
********************************************
Като допълнение прилагам и снимка на заявките в Постман :)

![delete mapping requests](https://user-images.githubusercontent.com/97394483/220203303-4dfbc978-c67c-4a95-8019-e68f8a0d0144.png)

**Comment by luchob** [comment]
Привет!

Да, опция е твоето решение. Също опция е това:

https://stackoverflow.com/questions/38785622/how-to-i-tell-a-springdata-repositorys-delete-method-to-not-throw-an-exception

Може да го усложним малко следващия път и да го направим да връща 404 като няма такъв обект.

Поздрави,
Л.
