### ISSUE TITLE
Receptaria - map arbitrary number of ingredients in controller

### ISSUE THREAD

**Issue by thrako** [luchob/softuni-feb2023#20]
Здравей Лъчо,

Изпращам линк до репото на проекта си: https://github.com/thrako/receptaria 

Моля за съвет как да си реформатирам кода, така че при няколко динамично добавени съставки от формата за добавяне на рецепта в контролера в `@PostMapping("/recipes/add")` да получавам готово намапено `RecipeDto`, в което да се съдържа `List<IngredientDto>`, а ако това не е възможно - някакъв по-елегантен начин, чрез който да постигна същия резултат.

Имам подобен проблем със снимките като описания по-горе относно съставките. 
Освен това, в допълнение, при добавяне на няколко снимки, бих искал потребителят да има възможност да избере, коя от тях е "primary" и съответно именно тази снимка да се показва като thumbnail в списъка с всички рецепти. Сложих radio бутони във формата, но информацията, която получавам от тях в `multipartRequest.getParameterMap()` не е достатъчна, за да идентифицирам снимката. 

Моля да се абстрахираш от това, че стилът на кода ми се разминава на места. Още експериментирам с различни стилове, планирам по-нататък да мина и да уеднаквя стиловете наведнъж.

Благодаря за времето ти!

Поздрави,
Траян

**Comment by luchob** [comment]
Добра вечер :-)

Съжалявам за бавните отговори, но тези дни е напечено положението. Не мога да ти отговоря в момента прекалено конкретно НО мога да ти дам добър джокер. Работенето със списък е с малко по-тегав синтаксис. Един колега прави такова нещо в проекта си и го обсъждахме с него [тук](https://github.com/luchob/softuni-may2022/issues/101). Накратко нещата са описани приемливо и с примери в тази [статия](https://www.baeldung.com/thymeleaf-list).

Ще може ли да те помоля да погледнеш и да видим натам какво ще става? :-)

Поздрави,
Л.

**Comment by thrako** [comment]
Здравей Лъчо! Честит празник!
Отговаряш много по-бързо, отколкото съм очаквал и то с адекватна информация, за което съм ти благодарен, както и за цялата ти отдаденост на преподаването! 

По-същество: Разгледах статията и fork-нах проектa на колегата, за да го debug-на. Мисля, че схващам генералната идея - имаме един временен wrapper DTO (при колегата това е `CartDTO`, който съдържа `List<CartProductDTO>`), който визуализираме в browser-a и при всяка промяна в него от страна на user-a, на server-a проверяваме кои данни са изменени, записваме промените в базата данни и визуализираме отново с update-натите данни. На практика елементите в `List`-а се добавят един по един, като при всяко добавяне се изпълнява цялата update логика на server-а и се рендерира нов html с нов `form` елемент, в който данните са предварително попълнени съгласно текущите записи в `CartDTO`. При submit на формата временният обект се трансформира в окончателен `public void createOrderAndClearCart(String email)` в `OrderService`. 

При него това решение е паснало доста добре, т.к. бизнес логиката на сайта изисква, в случай че потребителят желае да продължи с пазаруването (т.е. евентуално да добави нов елемент в `CartDTO`), да продължи да browse-ва сайта и неминуемо имаме презареждане на страницата.

При мен бизнес логиката се различава съществено. Имам една сравнително сложна форма (в сравнение с тази на колегата), която цели да създаде RecipeDTO със следните полета:
- private String title;
- private `List<PhotoUploadDTO>` photoDTOS;
- private `List<IngredientDTO>` ingredientDTOS;
- private int preparationHours;
- private int preparationMinutes;
- private int cookingHours;
- private int cookingMinutes;
- private int servings;
- private String description; //за момента е textarea, но мисля да имплементирам WYSIWYG и да записвам html-форматиран String в базата данни, който впоследствие да рендерирам при рендериране на рецептата (при положение че открия начин да го направя сигурно). 
- private UserEntity author;
//вероятно е да добавя и още едно поле visibilityStatus (enum {PUBLIC, PRIVATE, FOLLOWERS_ONLY}), ако напредна със Spring Security достатъчно, за да го имплементирам.

Както е видно имам два nest-нати List-а с различни DTO обекти, единият от които изображения, които могат да са доста големи по размер. Вероятно е теоретично възможно да имплементирам същата логика, но дори да се абстрахирам от това, че при мен имплементирането би било по-сложно (най-малкото защото имам два List-а, за които да се грижа), то се отваря следния проблем: при всяко добавяне / изтриване / промяна на снимка ИЛИ съставка, цялата информация (ведно с файловете) ще трябва да пътува от client-а до server-a, да изпълнявам цялата сложна логика и след това да презареждам текущата страница като изпращам същата (или почти същата) информация обратно до client-a, за да попълня актуалното състояние на формата за добавяне на рецепта. Вярвам ще се съгласиш, че целият този трафик на данни от client до server и обратно, никак не е оптимален.

Това, което правя в момента е: визуализирам по един box (взаимо-свързана група) с input полета за снимка и съответно един box за съставка като при желание на потребителя да добави повече снимки или съставки най-отдолу съм сложил по един бутон, който чрез JS създава и добавя нов box от съответния вид. Аналогично, чрез JS премахвам box. Накрая, при submit, данните се изпращат до server-а само веднъж, връщат се обратно до client-a единствено, ако в данните се открият грешки. Целият процес ми се струва много по-оптимален. 

~~Съответно, при добавянето на box чрез JS, Thymeleaf, вече е свършил своята работа и аз не мога да добавям `th:` атрибути. Това, което мога да опитам е чрез JS да добавя hidden input, подобно на тези редове: <div (...) th:each="p, itemStat: ${userCart.cartProducts}"> <input type="hidden" th:id="*{p.id}" th:value="${p.id}" th:attr="name='id'"> като не съм сигурен къде точно трябва да го поставя в моята форма, за да проработи евентуално, вероятно непосредствено след `<div>` tag-а на всеки box.~~

**При това решение въпросът относно primary photo остава отворен.**

EDIT No. 2: Имаме сериозен напредък. Всъщност, ключова се оказа стойността на `name` атрибута. Ако го сетна ето така:
```
<input id="ingredient-name-0" class="ingredient-name" type="text" name="ingredientDTOS[0].ingredientName" value="tomatoes">
```
и подобно за останалите полета на ingredientDTO, работи за индекси сетнати през Thymeleaf. Намапва ги идеално. Когато сетна някакъв индекс през JS обаче, той винаги е със стойност равна или по-голяма от размера на ArrayList-а и съответно винаги хвърля IndexOutOfBoundsException.  

EDIT No. 3: Имаме още по-сериозен напредък. Инициализирах List-а с LinkedList и Spring вече не се сърди. Ако имам "дупка" между индексите, напр. 0, 1, 4 с липсващи 2 и 3 - на 2 и 3 сетва IngredientDTO, в което всички полета са null. Добавих си във формата hidden input, от който да взема .size() на List-a, за да зная от колко да ми започват индексите на динамично добавените елементи с JS. Едното решение, за което се сещам (явно и ти, ако съдя по отговора ти, който получих междувременно) е да преномерирам name атрибутите при всеки removeElement() и да ресетвам текущия индекс в JS да е равен на броя на елементите, за да може при addElement() да вървят последователно. Другото решение е в Spring да филтрирам нулевите елементи със .stream().filter() при map-ването. Ще опитам да приложа и двата метода, т.к. освен "фалшиво нулеви" елементи, може да имам и такива, при които потребителят е добавил input полета за нова съставка, но не е попълнил нищо.     

~~Другото, което мога да опитам и ми се струва по-вероятно да доведе до успех е: на submit бутона да закача eventListener с preventDefault(), който да извлича информацията от form елемента в някакъв JS обект, който след това да JSON.stringify()-на и да изпратя с Fetch API до servera. С по-голямата част от информацията, вероятно ще се оправя и със сегашните си знания (вкл. с primary photo), но нямам никаква представа как да обработя снимките, така че да изпратя файловете до server-a.~~

~~EDIT: Друга посока, в която съм разсъждавал е следната: Доколкото зная Spring отдолу ползва Jackson, за да намапи данните от Request-а към поисканото DTO в съответния метод в Controller-а. Дали няма някакви анотации, които да му помогнат да ги намапи правилно към List от друго DTO?~~

Моля да ме извиниш, че се получи малко дълго. Честно казано не съм очаквал такава наглед trivial-на операция да доведе до толкова усложнения, но явно случаят ми е такъв. 

С нетърпение очаквам да разгледаш проекта ми в по-голяма дълбочина и да ми дадеш по-конкретни насоки, но напълно разбирам, че времето ти е ограничено, така че не се тревожи, ако отговорът се забави. Междувременно имам още много други неща да имплементирам в проекта си през ограниченото време, с което разполагам (семейството и работата са с приоритет :) ), а и вече имам някакво работещо решение, макар и дървено, така че мога да работя по останалите неща докато чакам.

Поздрави, 
Траян

**Comment by luchob** [comment]
Здравей!

Да, `name` e стойността, която пътува към сървъра. Какво ще кажеш, дали ще работи една доста по-простичка идея. Преди събмит на формата с JS да се именуват правилно input полетата с правилни индекси. Например, нещо такова:

```
addFormElement.addEventListener('submit', submitForm)

function submitForm(event) {
    event.preventDefault();

    let ingredients = document.getElementsByClassName('ingredient-name')

    for (let ingredient of ingredients) {
        //set name here
        // name must be ingredientDTOS[idx].ingredientName
    }
}
```

Струва ми се, че би трябвало да сработи.

Поздрави,
Л.

**Comment by thrako** [comment]
> ... Например, нещо такова:
> 
> ```
> addFormElement.addEventListener('submit', submitForm)
> 
> function submitForm(event) {
>     event.preventDefault();
> 
>     let ingredients = document.getElementsByClassName('ingredient-name')
> 
>     for (let ingredient of ingredients) {
>         //set name here
>         // name must be ingredientDTOS[idx].ingredientName
>     }
> }
> ```
> 
> Струва ми се, че би трябвало да сработи.

Само така няма да сработи, защото ако List се инициализира с ArrayList, после Spring хвърля IndexOutOfBoundsException за всеки индекс, който е index >= ArrayList.size() . Както си edit-нах горния пост, решението е инициализиране с LinkedList. Така работи като "липсващите" индекси ги попълва с IngredientDTO, в което всички полета са null. Този проблем вече се оправя, с решението, което си ми дал по-горе и тепърва ще опитам да разпиша. Не съм карал JS курса, но имам някакви базови познания по JS и се надявам да се справя. Благодаря много за насоките дотук. 

Остават ми отворени следните въпроси:
(1) Как да определя primary photo с някакъв input таг във формата? За момента съм сложил radio бутони, защото няма как повече от една снимка да е primary, но стойността, която ми изпраща в Controllera, не ми носи достатъчно информация, за да определя за кой файл се отнася.
(2) Как да имплементирам сигурно WYSIWYG едитор. Четох за някаква библеотека jsoup, която не съм пробвал как работи. Според теб, достатъчно ли е да я тествам с някакъв <script> таг, добавен в едитора - ако го изчисти, значи работи добре или е прекалено лаишко? :)

**Comment by luchob** [comment]
Привет! 

Тц, пробвам и работи. Може би причината е тук:

```
    @ModelAttribute("recipeDTO")
    public void initRecipeDTO (Model model) {

        model.addAttribute("recipeDTO", new RecipeDTO().setIngredientDTOS(List.of(EMPTY_INGREDIENT)));
        model.addAttribute("units", unitService.getDistinctUnitNames());
    }
```

Тук се слага immutable list, а вместо това може да стане `ArrayList`, например и тогава ще работи. Идеята ми е, че няма нужда да има дупки в никакви индекси и ще стане адски просто:

```
function submitForm(event) {

    let ingredients = document.getElementsByClassName('ingredient-name')
    let ingredientQtys = document.getElementsByClassName('ingredient-quantity')
    let ingredientUnits = document.getElementsByClassName('ingredient-unit')


    for (let idx = 0; idx < ingredients.length; idx++) {
        ingredients[idx].name = `ingredientDTOS[${idx}].ingredientName`
        ingredientQtys[idx].name = `ingredientDTOS[${idx}].quantity`
        ingredientUnits[idx].name = `ingredientDTOS[${idx}].unitName`
    }
}
```

С важната забележка, че `getElementsByClassName` ги връща в реда на DOM-а, но и да не е така, може да ги сложим в някакъв контейнер елемент и да ги вземаме поред. Кодът ще вземе всички input-и по клас и ще им сложи поредни индекси без дупки. Т.е. на сървъра ще получиш поредни индекси. Например ако добавя 3 съставки и изтрия средната след събмит на формата по HTTP пътува:

```
ingredientDTOS[0].ingredientName: fsdfds
ingredientDTOS[0].quantity: 123
ingredientDTOS[0].unitName: drop
ingredientDTOS[1].ingredientName: dsadsadsadas
ingredientDTOS[1].quantity: 23
ingredientDTOS[1].unitName: drop
```

Няма да има празен индекс и да са 0 и 2. И ти получаваш някакъв лист с два елемента (няма значение какъв, само да не инициализираш receipeDTO с immutable collection). 

Относно оставащите въпроси - да, с някакво допълнително input-че. А за 2 за съжаление не мога да те посъветвам.

**Comment by thrako** [comment]
Хм.... Много странно! И аз видях, че му подавам immutable List и това беше едно от първите неща, които рефакторирах, ето така:

```
@ModelAttribute("recipeDTO")
    public void initRecipeDTO (Model model) {

        final RecipeDTO recipeDTO = new RecipeDTO().addIngredientDTO(EMPTY_INGREDIENT);
        model.addAttribute("recipeDTO", recipeDTO);
        model.addAttribute("units", unitService.getDistinctUnitNames());
    }
```
но докато инициализирах с `ArrayList` в конструктура на `RecipeDTO` си хвърляше `IndexOutOfBoundException`. Оправи се, едва, когато го смених на `LinkedList`. В момента разписвам JS логиката, макар че като гледам ти половината си ми я дал наготово :). След това ще опитам отново с `ArrayList`. **EDIT:** Прав си! Работи и с `ArrayList`, ако индексите са последователни, явно само съм си мислел, че съм пробвал с последователни индекси.

Иначе подавам празен ingredient, за да има frontend-а какво да визуализира при начално зареждане на страницата. 

Относно подредбата: подредбата на DOM-а би трябвало винаги да е правилната подредба, така че всичко е наред.

Благодаря много за насоките!

P.S. issue.setStatus(Status.RESOLVED);
