### ISSUE TITLE
Теми за лекциите, ако остане време:

### ISSUE THREAD

**Issue by borisboev79** [luchob/softuni-feb2023#21]
Здрасти, Лъчо,

след като излекувахме "детските болести" по проектите си, виждам от чатовете ми с колеги, че има две теми, които доста ни мъчат и на които ми се иска, ако остане време, да ни помогнеш в някоя от следващите ни лекции:
1. Асинхронно взимане на данни с FETCH - това същото, което ни показа на 27.2 ли е или има нещо по-специално в асинхронността? Това е изискване за финалния ни проект, затова питам.
2. Пак като изискване за проекта - да се ползва минимум един интерсептор. Виждам отново, че не съм само аз, масово чудене е - дай ни идея за реално използваем интерсептор - и като идея, и като начин на писане и имплементация. Всички примери, които виждам онлайн, дават само някакви dummy примери с трите метода и това е. Никаква реална usecase ситуация.
3. Третата точка, която е масов леш е темата с Принципала - понеже реално в спринг секюрити контекста единственият юзър, който живее в сесията е инстанцията на User класа, който си идва от Спринг секюрити, и който има в UserDetails единствено username, password и id. Има ли начин без ходене до базата да си взимаме от реалното ентити на юзъра и други данни, като например firstName, lastName и т.н.?

Предварително благодаря!

**Comment by luchob** [comment]
Въпрос 3 - отговорен на 8.03 в 19:57 :-)

**Comment by borisboev79** [comment]
Много благодаря! Остана само да изясня за себе си първия от горните въпроси - по изискването за проекта има следната точка:
Use Fetch to asynchronously load and display data somewhere in your application.
Ползването на FETCH Api примера от лекцията от миналия понеделник това ли е, понеже никъде там не ставаше дума за асихнронността или тя си е присъща на Fetch Api?

**Comment by luchob** [comment]
Да, точно това е. Трябва да има някъде FETCH API дето да довлачи нещо в браузъра през REST. Достатъчно е това, което сме правили.

**Comment by borisboev79** [comment]
Благодаря ти отново! С това броя трите ми въпроса за отговорени, тъй като по темата с интерсепторите направих един логинг интерсептор, който даже ми е доста полезен като дебъг в конзолата направо. Засега имам проблем с имплементацията на регистрацията по начина, който показа вчера, нещо не ми вписва паролата в базата данни, но ако имам проблем ще отворя отделно issue. Лека вечер!
