### ISSUE TITLE
Проблем с login при използването на Spring Security

### ISSUE THREAD

**Issue by StefanPYordanov** [luchob/softuni-feb2023#22]
Здравейте,
Извинявам се, че Ви притеснявам, но когато се опитвам да логна потребител, нищо не се случва, също при подаването на грешни данни ни ми показва грешката за потребител или парола. Ще се радвам ако имате време да погледнете къде съм сбъркал. Благодаря Ви предварително, хубав и усмихнат ден!

https://github.com/StefanPYordanov/BookLibrary

**Comment by luchob** [comment]
Привет! На пръв поглед виждам 3 грешки, 2 от които със сигурност са в основата на проблемите ти.

Номер 1. Spring boot 3 работи със thymeleaf-extras-springsecurity6, а не 5. Правилното депендънси е:

```
        <dependency>
            <groupId>org.thymeleaf.extras</groupId>
            <artifactId>thymeleaf-extras-springsecurity6</artifactId>
        </dependency>
```

Ако не го смениш ще имаш необясними проблеми :-)

Номер 2. Трябва да запишеш в ДБ хеш на паролата на потребителя, а не такава в plain text. Т.е. имаш:

```

    @Bean
    public PasswordEncoder passwordEncoder() {
        return new BCryptPasswordEncoder();
    }

```

Следователно трябва да inject-неш този бийн и в инит сървиса да ползваш, например:
```
 var user = new UserEntity()
                .setUsername("user")
                .setPassword(passwordEncoder.encode("topsecret"))
                .setEmail("user@example.com")
                .setFullName("User Userov");
```

Номер 3. Тези 2 ендпойнта не може да се казват по един и същи начин. Затова не ти работи грешката:
```
loginPage("/login").
failureForwardUrl("/login"). //"/users/login-error
```

Поздрави,
Л.
