### ISSUE TITLE
Проблем с финалният проект.

### ISSUE THREAD

**Issue by MariaBonkova** [luchob/softuni-feb2023#23]
Привет, започнах да пиша логиката по проекта си, но още в началото започват гърмежите, с който не мога да се справя. Опитвам се да направя логиката за регистриране. В applicationBeanConfiguration се опитах да сложа валидацията от лекциите където са спринг секюрити.  Проблема е , че като рънна проекта зарежда моят проект, но като дам на home  и ми изкарва логина са спринг секюрити, иначе регистрация и вход ми зарежда мойте страници. И допълнително в конзолата ми изписва Using generated security password: 00e87e41-daa7-48ca-823e-bd69eb4cd2b1

This generated password is for development use only. Your security configuration must be updated before running your application in production.
Но въпреки това върви за сега. 
Ще бъда благодарна, ако може жокер как да го оправя.
Мария
https://github.com/MariaBonkova/3D-printing-project/tree/master

**Comment by luchob** [comment]
Здравей!

Може ли да потвърдиш/отхвърлиш този проблем -> https://github.com/luchob/softuni-feb2023/issues/19

Поздрави,
Л.

**Comment by MariaBonkova** [comment]
Превет!
в пома спринг буут ми беше версия 3.0.1 промених на 3.0.2 но все същото. Обаче проблема остава. Реално като кликна бутон начало трябва да ми отвори http://localhost:8080/home, а ми отваря http://localhost:8080/login. В хтмл съм ги сложила правилно   <a class="navbar-brand link-success" aria-current="page" href="/home">Начало</a>. Вече се чудя къде да гледам.

**Comment by luchob** [comment]
Здравей!

Първо трябва да оправиш трите Bean-a в `ApplicationBeanConfiguration` - `SecurityFilterChain`, `UserDetailsService` и `PasswordEncoder`. Без тях не можеш да очакваш да проработи. За пример може да използваш - https://github.com/luchob/softuni-feb2023/tree/main/security-demo.

 _Реално като кликна бутон начало трябва да ми отвори http://localhost:8080/home, а ми отваря http://localhost:8080/login._

Това става, заради комбинация от две неща. 

1. В `SecurityFilterChain`-а `/home` не е разрешен за анонимни юзъри:
```
 .requestMatchers("/", "/users/login", "/users/register", "/users/login-error").
      permitAll()
```
2. Когато кликнеш `/home` тъй като не е разрешен, те пренасочва към логин страницата. Но тя също не е конфигурирана:
```
.formLogin().loginPage(???)
```

Тъй че се използва default-ната на Spring Security.

Като оправиш тези неща ще сработи.

Поздрави,
Л.

**Comment by MariaBonkova** [comment]
Привет, вече леко отчаяна и объркана в кода си. Направих регистрацията и добавянето на нов юзър в репото като се регистрира. Обаче сега проблема ми е че паролата не се енкодва. Направих в конфиг папката трите важни неща за секюрити. Честно копирах от твоя код копирах initServise  в моят userServiseImpl с надеждата да ми се кодира паролата. Обаче възникна друг проблем с който не знам как да се оправя  Could not resolve placeholder 'app.default.password' in value "${app.default.password}" това от една страна и  Error creating bean with name 'userServiceImpl' defined in file [C:\myProject\demo\target\classes\com\example\demo\service\impl\UserServiceImpl.class]: Unexpected exception during bean creation.
Сега в мен възниква двулменето това секюрити само за логване или и за регистриране трябва. Първоначално разбрах, че при логване трябва, сега се чудя с добавянето на ролите още при регистриране и енкодването трябва ли или не и как да го направя? Също се чудя и как трябва да направя ролите да се сменят когато се извърши някакво действие по сайта . Например искам като се отвори страницата в нав бара да пише гост, но като се регистрира вече да е купувач, като иде на бутон създай продукт да стане създател. Това наистина незнам къде в кода трябва да го напиша. Почват да изникват някакви стари спомени от курса по js, но съм много объркана.
С уважение М.
https://github.com/MariaBonkova/3D-printing-project/tree/master
