### ISSUE TITLE
Достъп до cloudinary проект

### ISSUE THREAD

**Issue by AtanasKaloyanov** [luchob/softuni-feb2023#24]
Здравей, Лъчо!

В момента гледам първият Workshop от изданието на курса, започнал септември месец 2021 и там видях, че си направил cloudinary проект, които би ни бил полезен и за нашите проекти. Проблемът е в това, че не го намирам в github-a ти (не изключвам и нещо аз да не довиждам). Workshop-a се е провел на 05.11.2021.

Поздрави!

**Comment by luchob** [comment]
Здравей!

Бях го скрил, защото получих едно питане година и половина след курса за някакъв тест дето не върви :P 

Отварям го наново, ако не е много старо хвърли един поглед. Ето тук има изолиран от всичко пример: https://github.com/luchob/softuni-spring-advanced-2021/tree/master/cloudinary

Ако не работи ще го мъчим. Никога не пречи и да се четат issues и да се хвърля око на колегите :-) :-) https://github.com/luchob/softuni-feb2023/issues/3

Ами така де, писането на код е групово занимание :-)

Поздрави,
Л.
