### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by RosenMitrov** [luchob/softuni-feb2023#26]
Здравей Лъчо,

Искам да попитам нещо за Login, което ме мъчи от известно време. 
Тъй като Spring Security извършва за нас @PostMapping за Login и не го пишем никъде ме притеснява следното:
Примерно имаме: 
```
UserLoginDto {
   
   @NotBlank
   @Size(min = 5, max = 20)
   private String username;
    @NotBlank
   @Size(min = 8, max = 30)
   private String password;

 гетъри и сетъри
}
```
До този момент правихме Post-Redirect-Get и ако данните нещо сгафят с @Valid проверявахме за error-и и връщахме на същата форма със съответната грешка, не допускахме заявка до базата, запазвахме евентуално username във формата и тн.

Не мога да си обясня това нещо как се случва със Security. 
Има ли как да стане по подобен начин, или вече изцяло тази валидация става на ниво клиент? И ако да, в случай на заобикаляне на клиента, как се предпазваме, ако изобщо има от какво в тази ситуация? Нещо изпускам по веригата, но не мога да се ориентирам кое точно.

Благодаря!

Поздрави,
Росен

**Comment by luchob** [comment]
За съжаление това е много трудно :( 

Има няколко статии в нета, които показват как става с  override на`UsernamePasswordAuthenticationFilter` но честно казано не ми се е налагало да го правя, т.к. "в живота" разчитам повечко на JWT. Ако се налага препоръчвам client side валидация, ако това е възможно и чак тогава модификация на spring security.

Поздрави,
Л.
