### ISSUE TITLE
Spring Security Problem

### ISSUE THREAD

**Issue by cUserd** [luchob/softuni-feb2023#27]
Здравей Лъчо, 
имам нужда от малко помощ или насоки.
имам два проблема със секюритито  на приложението:
1. когато сетна anyRequest().authenticated() и приложението ми седи на preloaderа и не се отваря, на permitAll се оправя  и работи нормално;
2. когато тръгна да се логвам мe насочва към failureForwardUrl като не виждам причина за това. Четох за проблемите на колегите с версиите но при мен мисля че са точните.

https://github.com/cUserd/finalProject_softUni_Model3d

тук е репото ако намериш време да погледнеш, Благодаря!

**Comment by luchob** [comment]
Здравей!

На първо място махни версиите от тези стартери:

```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.thymeleaf.extras/thymeleaf-extras-springsecurity5 -->
        <dependency>
            <groupId>org.thymeleaf.extras</groupId>
            <artifactId>thymeleaf-extras-springsecurity6</artifactId>
        </dependency>
```

Давайки им твърда версия овъррайдваш тази, която спринг са задали и оттам проблемите ти могат да бъдат буквално всякакви :-)

На второ място не ти се отварят нещата защото имаш много забранени Javascript библиотеки, които се намират в libs папка. Тази папка не се води "standard location" и не се покрива от това:

```
                requestMatchers(PathRequest.toStaticResources().atCommonLocations()).permitAll().
```

Трябва да я разрешиш, напр:

```
                requestMatchers("/", "/libs/**", "/login", "/register", "/login-error").permitAll().
```

За това, което задаваш в `failureForwardUrl` трябва да имаш POST mapping в кода, а не GET :-)


Поздрави,
Л.

**Comment by cUserd** [comment]
Благодаря за отделеното време, някой неща се оправиха обаче логина все така ме хвърля в failureForwardUrl при положение, че юзера го има в базата виждам и през f12 че се пращат правилните username и password. от базата си вадя правилният юзер с findByEmail но какво се случва в секюрити не ми е много ясно :(
просто ме препраща всеедно е грешен потребител. във логин формата всичко е както трябва поне според мен.

иначе за папка libs реших да използвам:
  @Bean
    public WebSecurityCustomizer webSecurityCustomizer(){
        return web -> web.ignoring()
                .requestMatchers("/css/**","/js/**","/images/**","/libs/**");
    }
