### ISSUE TITLE
Security Login not work

### ISSUE THREAD

**Issue by cUserd** [luchob/softuni-feb2023#28]
Благодаря за отделеното време, някой неща се оправиха обаче логина все така ме хвърля в failureForwardUrl при положение, че юзера го има в базата виждам и през f12 че се пращат правилните username и password. от базата си вадя правилният юзер с findByEmail но какво се случва в секюрити не ми е много ясно :(
просто ме препраща всеедно е грешен потребител. във логин формата всичко е както трябва поне според мен.

иначе за папка libs реших да използвам:
@bean
public WebSecurityCustomizer webSecurityCustomizer(){
return web -> web.ignoring()
.requestMatchers("/css/","/js/","/images/","/libs/");
}

_Originally posted by @cUserd in https://github.com/luchob/softuni-feb2023/issues/27#issuecomment-1460534820_

**Comment by luchob** [comment]
Здравей!

За начало - прави ми впечатление нещо, което не е ОК. Експоузваш 2 инстанса на юзър детайлс сървис:

```
  @Bean
  public UserDetailsService userDetailsService() {
    return new CustomerUserDetailsService(userRepository);
  }
```

и
```
@Service
public class CustomerUserDetailsService implements UserDetailsService 
```

Може би ако махнеш `@Service` анотацията още малко неща ще тръгнат :-)

Л.

**Comment by cUserd** [comment]
Здравей!

Ами не знам да се смея ли да плача ли вече ... това секюрите не се предава и това е ... има напредък без @Service анотацията  вече ми дава друга грешка 
.... тази която говорихме вече няколко пъти за faviconata  (There was an unexpected error (type=None, status=999).) ... до тук добре ... реших че слагам иконката и отварям шампанското, но нито като я сложа се оправя ... нито като дам defaultSuccessUrl("/",true) все си ме води при тази грешка ... 


иначе си я зарежда иконката горе на таба .. явно си я намира
и линка в head си оправих , пробвах с друга иконка с емотиконка .. но не иска да подпали този логин

**Comment by luchob** [comment]
Здравей! 

Свалих на чисто последната версия на проекта ти. Само се наложи да "хакна" паролите тъй като не ги зная. При мен логина е успешен:

<img width="1090" alt="Screenshot 2023-03-09 at 18 16 06" src="https://user-images.githubusercontent.com/10339738/224085632-1d683ca8-f0bc-4251-91d2-ee4950dcb162.png">

Както се вижда и логин рикуеста е ОК, редиректва към хоум пейджа и изглежда съм логнат. Не съм сигурен какво да ти кажа :-) Ако искаш... свали го на чисто и го пусни :-)

Поздрави,
Л.

**Comment by cUserd** [comment]
И при мен се логва вече ... просто не знам какво да кажа освен   ... Благодаря сърдечно за положените усилия ... една седмица мъка с този Spring security и около 6-7 започнати от самото начало проекти ... с модули без модули ... дори и copy paste от твоето демо  и все до едно и също място забивах... вече мога да празнувам :)  дано да бъдем полезни и на някой друг колега с моят казус ... още веднъж БЛАГОДАРЯ!

**Comment by cUserd** [comment]
Здравей отново ... проблема с тази грешка си ми седи в админ модула иначе клиентският си е наред поне :) .. но след доста тестване се оказа че е нещо от темплайтите или поне от тази папка ... като ги сменя с други си работи .. и въпроса ми е следният ... според теб ако в този админския си направя логването да не е през спринг секюрити тъй като вече си почнах да си разработвам някой фичъри и не ми се иска да почвам наново този панел дали ще е голяма драма знам че това спринг секюрити е идеята на този курс ама ще ме подлуди най-накрая :)

**Comment by luchob** [comment]
Здравей! 

Според мен може да преместиш проекта в един модул, за да стане сравнително нормален за пускане :-) и да ползват един модул. Според мен. Дали ще е драма нещо друго, не мога да ти кажа, т.к. не участвам в изпитите или писането на изисквания за тях. Най-добре подобни въпроси ги отнасяй към СофтУни, за да не стане някоя драма наистина :-)

Поздрави,
Л.
