### ISSUE TITLE
security

### ISSUE THREAD

**Issue by RosenMitrov** [luchob/softuni-feb2023#29]
Здрасти Лъчо, пак съм аз :)

По време на лекцията, мисля ще не успях да си задам въпроса правилно относно UserEntity със Security.

Ситуацията е следната:
Създава се наш JpaUserDetailsService и се импплементира UserDetailsService по този начин:

```
@Service
public class JpaUserDetailsService implements UserDetailsService {

    private final UserRepository userRepository;

    @Autowired
    public JpaUserDetailsService(UserRepository userRepository) {
        this.userRepository = userRepository;
    }

    @Override
    public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {

        var user = this.userRepository.findFirstByUsername(username);

        return user.map(SecurityUser::new)
                .orElseThrow(() -> new UsernameNotFoundException("Username not found " + username));
    }
}
```

Също така се създава наш клас SecurityUser, който имплементира UserDetails по следния начин:

```
public class SecurityUser implements UserDetails {

    private final UserEntity user;

    public SecurityUser(UserEntity user) {
        this.user = user;
    }

    @Override
    public String getUsername() {
        return this.user.getUsername();
    }

    @Override
    public String getPassword() {
        return this.user.getPassword();
    }

    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        //not implemented
        return List.of(() -> "read");
    }


    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    @Override
    public boolean isEnabled() {
        return true;
    }
}
```
И така вместо да подаваме отделните полета, да го направим с цялото ентити. Въпросът ми е дали по този начин да подадем цялото UserEntity е напълно грешно?
Или ако е много лоша практика да се инжектира по този начин, възможно ли е в метод "loadUserByUsername" да се трансформира ентитито в ДТО и след това в SecurityUser да подадем въпросното UserDto?

```
    @Override
    public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {

        var user = this.userRepository.findFirstByUsername(username);

    тук с мапър да го преобразувам в DTO и да го подам него на SecurityUser като  private final UserDto userDto;
     UserDto userDto = this.modelMapper.map(user, UserDto.class);
     
        return userDto .map(SecurityUser::new)
                .orElseThrow(() -> new UsernameNotFoundException("Username not found " + username));
    }
```

Четох, че подобден подход се нарича adapter/decorator pattern, но може и да бъркам.

И като допълнение къде би било подходящо да се вкарат всички филдове от UserDetails -> isAccountNonExpired, isAccountNonLocked и тн. В UserEntity предполагам и да се пази true/fasle, като статус в базата или?

Благодаря предварително :)

Поздрави, 
Росен

**Comment by luchob** [comment]
Здравей!

Разбрах какво ме питаш и мисля, че е погрешно - за съжаление не напълно, което означава че ще работи през повечето време на външен вид :-) . Имай предвид, че спринг не пита на всеки HTTP рикуест твоя сървис за `UserDetails`. По скоро има имплементации на `SecurityContextRepository`, които се ползват от филтрите на спринг секюрити за да възстановяват секюрити контекста (от който UserDetails е част). При нашия логин механизъм това става с помощта на HTTP сесията. Пък някъде много дълбоко сървлет контейнера може да реши в даден момент да сериализира сесията. Ако забелязваш един дребен детайл, който е срамежливо изпуснат в документациите - UserDetails е Serializable. Сега си представи всички релации на юзъра + ненужните му пропъртита като рожден ден, пол и т.н. как и дали се сериализират. 

Освен това въпросното `UserEntity` минава в detached state (когато нямаш хибернейт контекст). Всички lazy релации ще започнат да гърмят в даден момент защото им липсва сесия. Ей такива проблемчета ще почнат да се появяват неочаквано (защото на локалната ти машина всичко ще работи). Някои колеги са дори по-крайни и имплементират `UserDetails` в `UserEntity`. Това, което ти препоръчвам си го написал горе:

_трансформира ентитито в ДТО и след това в SecurityUser да подадем въпросното UserDto_

Относно `isAccountNonExpired` може да го пазиш в базата, стига да искаш да имаш фичър за експайрнъли акаунти в проекта. Ако не - връщаш дифоултна стойност.

Поздрави,
Л.
