### ISSUE TITLE
cloudinary SunCertPathBuilderException: unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by toshko89** [luchob/softuni-feb2023#3]
Привет :) 
Имплементирам cloudinary в моят проект и имам един проблем 
При качване и триене на снимка излиза тази грешка PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Успях да кача SSL сертификата, но днес при стартиране отново излезе това. Има ли начин веднъж щом се качи този сертификат в “%JAVA_HOME%/jdk-18.0.2.1/lib/security/cacerts, повече да не се налага да го правя ? 

Използвам тази команда: 
keytool -importcert -file ‪C:\Projects\_.cloudinary.crt –alias dinardap –keystore C:\Program Files\Java\jdk-18.0.2.1\lib\security\cacerts

Благодаря !

**Comment by luchob** [comment]
Здравей!

Проблемът ти е доста странен и това, което ми хрумва е че си си поиграл със сертификатите и нещо се е посчупило. :-)  При мен твоя клаудинари сървис работи без проблеми (open JDK 17). Може би опитай на го стартираш с друго JDK или да преинсталираш JDK-то си. Сигурен съм, че проблемът ти не е в кода, нито пък трябва да го решиш точно така.

Какво мислиш?

**Comment by toshko89** [comment]
Здрасти, преинсталирах JDK-то... явно нещо съм оплескал. Благодаря :)
