### ISSUE TITLE
Отново имам нужда от помощ

### ISSUE THREAD

**Issue by ViliIlieva** [luchob/softuni-feb2023#30]
https://github.com/ViliIlieva/MyKnitShop
Да помоля да погледнеш във html shopping-card защо не ми засича ДТО-то.
Също искам да попитам в OrderControlera направих Гет и Пост заявка с идеята че когато изпълнявам products/order т.е. html order-details (когато клиент си потвърждава поръчката) очаквам пост заявка защото попълвам две полета с данни които идват с тази заявка, а в Network виждам че заявката всъщност е Get, това защото не ми е засякло ДТО-то и защото нямам th:field във htmla ли се получава. 
Май доста объркано си зададох въпроса дано да съм успяла да обясня.
Благодаря предварително!

**Comment by luchob** [comment]
Здравей :-)

Ако съм напълно откровен, въпросите наистина са объркващо зададени. Добре, въпреки това нека да се опитам. Предполагам, че не ти "засича" ДТО-то защото просто няма такова в модела или аз не го виждам:
```
    @GetMapping("/shopping/card")
    public String shoppingCard(Principal username, Model model) {
        model.addAttribute("cardCashProduct", this.userService.getPurchaseListByUserToViewInShoppingCard (username));
        model.addAttribute ("count", this.userService.countOfItemInShopCard (username));
        model.addAttribute ("sumForAllProducts", this.userService.sumForAllPurchaseProduct (username));
        return "shopping-card";
    }
```

_Off-topic: cart е количка (e.g. shopping cart, там където си поставяш продукта вкл. в електронен магазин) а shopping card по-скоро е... например някаква Billa карта отпечатана на пластика :-) Набива се в окото :-)_

Относно другия въпрос... малко съм озадачен, но в HTML-a няма форма изобщо... Виждам това:
```
<div class="card p-4 mt-3" th:action="@{/products/order}">
``` 

а очаквах да има:

```
<form th:action="..." th:method="..."
```

Дано съм се ориентирал правилно за проблемите.

Поздрави,
Л.
