### ISSUE TITLE
Synchronization of constraints

### ISSUE THREAD

**Issue by thrako** [luchob/softuni-feb2023#32]
Здравей Лъчо,
Не съм сигурен, че ми разбра въпроса относно синхронизацията на validation constraints между backend и frontend по време на днешната лекция. Имах предвид следното: например в backend-а съм задал на полето password `@Size(min = 5)` и подобно във frontend-а извеждам съобщение с JS, ако паролата е по-къса от 5 символа. По-късно обаче променям изискването в backend-а да е `@Size(min = 8)` и пропускам да си ъпдейтна frontend-a. Получава се неприятна ситуация, потребителят въвежда парола, която според frontend-а е с допустима дължина, но backend-а не я допуска. За да не се случва това искам тези числа, regex-и и т.н. ("constraints") да ги залагам на едно единствено място, от което да си ги вземат и backend-a и frontend-а. По същия начин мисля да процедирам и със съобщенията, за да са идентични, независимо дали се генерират от frontend-а или от backend-а. Начините, по които съм открил, че може да се имплементира са: (1) script таг, в който подавам данните чрез Thymeleaf variable като тук хубавото е, че мога да подам Map; (2) hidden input field, но трябва да правя отделно поле за всеки constraint (или поне аз така си мисля); (3) REST Controller + Fetch заявка -> не съм сигурен, че е ОК да го ползвам за такива "служебни" данни, макар да не виждам друга очевидна причина защо би било грешно. Вероятно има и други начини, за които аз не се сещам. Та... въпросът ми е, кой е препоръчителният начин да го имплементирам?

**Comment by luchob** [comment]
Здравей! 

Тъй като клиента и сървъра работят на различни машини (в браузъра и на сървъра) и използват съвсем различни технологии, мисля че няма особено добър начин да ги комбинираш, поне не и с технологиите които използваме. 

Сървърните валидации са абсолютно задължителни, тъй като гарантират:

- сигурност
- data integrity

Клиентските са по-скоро за:

- удобство на юзъра
- перформънс (данните не ходят до сървъра)

В опита винаги съм ги виждал:

- дуплицирани
- изпуснати на клиента и изцяло имплементирани на сървъра
- частично изпуснати на клиента и изцяло имплементирани на сървъра

Мисля, че ти разбрах въпроса на лекциите и в отговора си имах предвид, че например на сървъра няма нужда да пазиш съобщения за грешките - така или иначе всеки с легален клиент ще ги види в браузъра, а за такива с лоши или хакерски намерения не е нужно да показваш грешки. Ако се разминат обаче на клиента и сървъра - тогава - кофти.

Поздрави,
Л.
