### ISSUE TITLE
Сетване на модератор и админ

### ISSUE THREAD

**Issue by PlamenPeev** [luchob/softuni-feb2023#33]
Здравей, интересно ми е относно начина който ни показа сетването на админа и модератора на лекцията за секюритито, дали може да си сетнем примерно така два админа и три модератора примерно и как трябва да стане? 
Благодаря предварително!

**Comment by luchob** [comment]
Привет!

Не виждам никакъв проблем да има сетнати N админа и M модератора. Например с 2 админа таблиците ще изглеждат горе долу така:

`users`:

| id | email | first_name | last_name | password |
| ----------- | ----------- |----------- |----------- |----------- |
|1 | admin1@example.com|Admin1|	Adminov1|...|			
|2 | admin2@example.com|Admin2|Adminov2|...|	

Ролите си отсават същите.

`roles`:

| id | role | 
| -----|-----|
|1 | MODERATOR|
|2 |ADMIN|

И съответно many-to-many таблицата става:

|user_id|role_id|
| -----|-----|
|1|1|
|1|2|
|2|1|
|2|2|

Създаване с код:

```
private void initAdmin(){
    var adminUser = new UserEntity().
        setEmail("admin1@example.com").
        setFirstName("Admin1").
        setLastName("Adminov1").
        setCountry("Bulgaria").
        setPassword(passwordEncoder.encode("topsecret")).
        setRoles(userRoleRepository.findAll());

    userRepository.save(adminUser);
  }

  private void initAdmin1(){
    var adminUser = new UserEntity().
        setEmail("admin2@example.com").
        setFirstName("Admin2").
        setLastName("Adminov2").
        setCountry("Bulgaria").
        setPassword(passwordEncoder.encode("topsecret")).
        setRoles(userRoleRepository.findAll());

    userRepository.save(adminUser);
  }
```

Но най-разумно ми изглежда първоначално да има 1 админ, който да може да превръща останалите юзъри в админи/модератори. В кода:

1. Взема се таргет юзъра
2. Сетват му се всички необходими роли
3. Записва се

Поздрави,
Л.
