### ISSUE TITLE
Проблем със качване на снимка и друг файл

### ISSUE THREAD

**Issue by cUserd** [luchob/softuni-feb2023#35]
Лъчо здравей,

имам два проблема които не успявам да разреша и ще съм благодарен за малко съвети и помощ.
проблем 1 : в приложението ми искам да може да се качва снимка. качвам я записвам я в папката (вижда се) има си я в базата като стринг, но когато се мъча да я визуализирам с tymeleaf ми гърми. Доколкото четох и разбрах се използва 
th:src="|data:image/jpeg;base64,+${model.image}|
обаче не ми я визуализира 

проблем 2: в приложението ми искам да мога да качвам файл към базата отново като стринг . Тук още на ниво база не мога да го кача. Четох че трябва да  е BLOB пробвах и различни варианти но базата не иска да го приеме. Също бих те помолил за съвет какво трябва да потърся и прочета за да мога да го сваля в един момент от някакъв бутон примерно download object
или стъпките са както съм го вкарал с input stream да го обърна с output stream.

тук е приложението ми ако намериш малко време да погледнеш.

https://github.com/cUserd/finalProject_softUni_Model3d/tree/master

**Comment by luchob** [comment]
Здравей!

Направих едно малко демо в което качвам и свалям файл в/от базата. 

https://github.com/luchob/fileupload/

Надявам се да помогне.

Разбира се, няма нужда да казвам, че демото е направено много бързо и мръсно. :) Но може да качи файл и после да го покаже в thymeleaf.

Поздрави,
Л.

**Comment by cUserd** [comment]
Благодаря за демото. Много полезно!
