### ISSUE TITLE
Проблем със spring security

### ISSUE THREAD

**Issue by ivadar** [luchob/softuni-feb2023#36]
Здравейте, ако имате време може ли да погледнете проекта ми [https://github.com/ivadar/Vandi-gym-project], имам проблем след добавяне на спринг секюрити, не ми визуализира табовете за регистрация, логин и др., както аз искам и винаги ме препраща към логин независимо къде кликна. Home html-a въобще не се показва, все едно го няма.
Ще се радвам на отговор, благодаря!

**Comment by thrako** [comment]
Здравей Ива,
Не си разрешила достъпа до "/", това е причината да не ти дава достъп до началната страница. Опитай да добавиш: .requestMatchers("/").permitAll() в SecurityConfiguration. 
Можеш ли да провериш дали това решава проблема?

**Comment by ivadar** [comment]
За съжаление не е това, все още виждам само индекс страницата, но не и хоума след логване.

**Comment by thrako** [comment]
Login логиката ти не работи, защото след добавянето на Spring Security, същото използва подадения му PasswordEncoder, за да сравни хеша от въведената в login формата парола с хеша записан в базата данни (а ти в базата данни записваш raw password: прим. 1234).

Добавих един ред в UserServiceImpl и мисля, че всичко тръгна:
```
@Override
public void registerUser(UserServiceModel userServiceModel) {
    User user = this.modelMapper.map(userServiceModel,User.class);
    user.setPassword(passwordEncoder.encode(userServiceModel.getPassword())); ето този ред, но преди това трябва да си добавиш поле PasswordEncoder и да го инициализираш с конструктура
    
    this.userRepository.saveAndFlush(user);
}
``` 

След тази добавка и като се логна ми отваря: 
![Vandy](https://user-images.githubusercontent.com/101820581/224676211-6fe1f63e-fc9a-46d5-8048-3f1009249b6b.png)

Може ли да провериш с тази добавка?
