### ISSUE TITLE
Problem with registration

### ISSUE THREAD

**Issue by Paytakov** [luchob/softuni-feb2023#37]
Привет, Лъчо!
Мъча го този проблем от доста време и не мога да разбера защо не иска да ми регистрира потребител. Нито някаква грешка хвърля, нищо. Просто като стигнем до регистрирането на потребителя и приложението овисва?? Мисля си, че може да има нещо общо с енкодера на пароли, но не съм сигурен. Честно казано вече нямам идея. :(

Ще съм благодарен ако успееш да му хвърлиш едно око и да дадеш някакъв съвет. :)

Линк към репо: https://github.com/Paytakov/mobilele-app

Хубав ден и поздрави!

**Comment by luchob** [comment]
Здравей!

След чекаут на чисто на този проект при мен регистрацията работи. Не съм сигурен дали ми даваш правилен линк, но това репо което виждам не е пипано от месеци. Спринга е версия 2.7.

Аз ли бъркам нещо или има някакви неща дето ги няма в github?

Л.

**Comment by Paytakov** [comment]
Ами до това положение го бях добутал и не съм правил промени по проекта от известно време. Остават ми някои неща, които искам да добавя. Но при мен, както споменах, има явно някакъв проблем с регистрацията и не работи. Може би ще трябва да мигрирам на нова версия на спринг.

**Comment by luchob** [comment]
Ами честно казано малко ми е трудно да ти дам някакъв съвет. 
Свалих проекта и го подкарах в отделна база. Регистрацията се случва и не виси по никакъв начин. Юзъра се записва в ДБ.
Прегледах кода и не виждам нищо ненормално. :(

Съжалявам наистина :(
