### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by ilambrev** [luchob/softuni-feb2023#38]
Здравей,

В лекцията от 13.03.2023 г. ни показа как да използваме Environment variables за да не публикуваме чувствителна информация в GitHub като пароли, потребителски имена и т.н., за което съм ти много благодарен, тъй като никой до момента не ни беше показал тази възможност. Мисля, че ще е добре ако остане малко време на следващата лекция да се допълни информацията, като се обърне внимание на една особеност, която може да обезсмисли това действие.

Тъй като ми стана интересно къде се съхранява конфигурацията на Environment variables, открих следната информация на сайта на JetBrains:

https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000259664-Are-my-environment-variables-backed-up-to-Github

Всъщност за всеки проект информацията се съхранява в диркеторията на проекта в поддиректория .idea във файл workspace.xml.

Тази поддиректория никога не трябва да се къмитва, т.е. трябва да се внимава и винаги да се добавя във файл .gitignore на всеки проект.

**Comment by luchob** [comment]
Хах, да :-) .gitignore наистина е сериозно игнориран файл и колегите много често си слагат и idea папката и target/build/output и какво ли още не, барабар с паролите в application.yaml. 

Явно наистина трябва малко да наблегнем на този файл. Оставям отворено това issue до следващата лекция.

Поздрави,
Л.

**Comment by ilambrev** [comment]
Във връзка с темата за Git и GitHub секюрити (и вдъхновен от една прочетена статия https://rewind.com/blog/git-security-issues-watch-out-for/) днес си поиграх да си генерирам и инсталирам SSH и GPG ключове за достъп при push и подписване на commits. Това също е интересна тема. Друго си е да се вижда в историята на commits "
This commit was signed with the committer’s verified signature. "
Би било хубаво ако СофтУни включат една по-сериозна лекция за Git и GitHub в някой от модулите.

Поздрави!

**Comment by luchob** [comment]
Здравей!

Обърнах внимание на колегите да внимават с .gitignore. За гит е много добра идея, т.к. комитите в някои репозиторита са меко казано странни.

Поздрави и благодаря!
