### ISSUE TITLE
Моля за помощ с проекта

### ISSUE THREAD

**Issue by ViliIlieva** [luchob/softuni-feb2023#39]
https://github.com/ViliIlieva/MyKnitShop.git
Здравей отново, на мен май ми е най труден таймлийфа.
В OrderControler съм направила два метода за cart, гет и пач, с идеята че пач метода приема данни за юзъра които трябва да бъдат допълнени във вече създадения такъв. 
Направих и страницата след потвърждаване на поръчката и тя е order-details като в контролера създадох метод и за нея, 
ако самостоятелно заредя страницата localhost:8080/order/details/5 ми зарежда страницата и ми издърпва всички необходими данни.
Но не успявам от cart.html когато събмитна "Потвърди Поръчката" да ме прехвърли към  localhost:8080/order/details/{id} уж в пач метода съм задала да презареди order-details
Да помоля да погледнеш

**Comment by luchob** [comment]
Здравей!

А помага ли ако редиректнеш? Например, не така:

```
return "order-details";

```

а по-скоро:

```
return "redirect:/order/details/" + orderId;
```

?

**Comment by ViliIlieva** [comment]
Да стана много благодаря
