### ISSUE TITLE
Благодаря

### ISSUE THREAD

**Issue by lamenco** [luchob/softuni-feb2023#4]
Здравей Лъчо, съжaлявам че въпросите са 3, но когато имаш време ще се раздвам ако може да ми помогнеш, Имам проблем като пускам тестовете, че получавам грешка "java: illegal character: '\ufeff'" И " java: class, interface, enum, or record expected".

Втория ми проблем е, че не разбирам защо интересептора ми не работи. Не ми се сменя езика на навигацията.
Всичко ми е на UTF-8 и с BOM или без BOM нищо не се получава.

И третия ми проблем е, че се опитвам да сложа на всеки нов потребител роля USER Още на регистрация с кода
" List<userRoles> userRoles = new ArrayList<>();

if(userRegisterDto.getUsername().equals("lambo")){
userRoles.add(new UserRole().setUserRole(UserRoleEnum.ADMIN));
}else{
userRoles.add(new UserRole().setUserRole(UserRoleEnum.USER));
}
newUser.setUserRole(userRoles);"
но ми дава грешка.

Ще оставя линк към проекта -> https://github.com/lamenco/Window-Shopper , изтегли PVC7.rar
Нещо още не мога да се ориентирам добре как се качва в репозиторито.

Благодаря!

**Comment by luchob** [comment]
Привет, относно първия ти проблем - този символ е т.нар. BOM (byte order mask). Ползва се понякога, за да означи че файлът е unicode но не трябва да присъства в Java файла ти. Не го виждаш, не е в `WindowShopperDetailsServiceTests`. Сигурно си го отварял с някакъв странен редактор. Ето как можеш да го махнеш с IntelliJ.
<img width="378" alt="Screenshot 2023-02-23 at 8 26 51" src="https://user-images.githubusercontent.com/10339738/220834922-266d8e7d-e9e6-4a09-b28a-54885b59eda8.png">

**Comment by luchob** [comment]
Относно втория въпрос - не разбирам какво точно не работи. Пуснах проекта ти при мен и изглежда че работи.

<img width="684" alt="Screenshot 2023-02-23 at 8 33 50" src="https://user-images.githubusercontent.com/10339738/220835607-4ba674e5-8ca2-4932-bbf9-fd86c15c766f.png">

<img width="641" alt="Screenshot 2023-02-23 at 8 34 52" src="https://user-images.githubusercontent.com/10339738/220835647-2a1dd38c-afe6-46b9-a123-e8d1ffb9c06a.png">

**Comment by luchob** [comment]
За третият:

Може да направиш подобен метод: 
```
@Repository
public interface UserRoleRepository extends JpaRepository<UserRole,Long> {
  Optional<UserRole> findUserRoleByUserRole(UserRoleEnum roleEnum);
}
```

И да сетваш ролята така:
```
userRepository.findUserRoleByUserRole(ADMIN).orElseThrow()
```

Разгледай [тук](https://github.com/luchob/softuni-feb2023/blob/main/security-demo/src/main/java/bg/softuni/security/service/InitService.java#L67).

**Comment by lamenco** [comment]
При мен стоят само на български Вход
 и Регистрация, независимо дали го сменям и не знам защо ми излзиа
 ??fragment_language_en_US??  
 след като имам в messages като Език или Language.    
  







 >-------- Оригинално писмо --------

 >От: Lachezar Balev ***@***.***

 >Относно: Re: [luchob/softuni-feb2023] Благодаря (Issue #4)

 >До: luchob/softuni-feb2023  

 >Изпратено на: 23.02.2023 08:35



 
 
  
  
  
Относно втория въпрос - не разбирам какво точно не работи. Пуснах проекта ти при мен и изглежда че работи.
