### ISSUE TITLE
Моля за Вашата помощ

### ISSUE THREAD

**Issue by StefanPYordanov** [luchob/softuni-feb2023#40]
Здравейте,

Бих желал да Ви помоля за малко помощ,
имам няколко проблема и към момента не мога да ги разреша.
При отиване на ендпойт на профил, ме редиректва към логин, 
разрешил съм го за всички потребители, преди да вкарам принципал, си
работеше, но след това започна да редиректва.
Също когато подам две различни пароли на pass и repass при регистрация 
не запазва данните в базата, но не дава и ерър, също така и при логин нито ми показва ерърите, нито че
потребителя вече съществува, или че има грешен потребител или парола.
При addbook в html имам поле option и искам да го направя да ми показва авторите от репозиторито, опитвам се да
го направя с th.each, но не ми се получава, явно не го правя праравилно, знам че трябва да направя лист с 
findAllAuthors и да го покажа в options на html, но нещо не успявам да го направя.

Благодаря Ви изключително много. Пожелавам Ви прекрасен и усмихнат ден !

https://github.com/StefanPYordanov/BookLibrary

**Comment by luchob** [comment]
Здравей!

**Проблем 1)**

_При отиване на ендпойт на профил, ме редиректва към логин, разрешил съм го за всички потребители, преди да вкарам принципал, си работеше, но след това започна да редиректва._

Ако се загледаш в конзолата, ще забележиш следната грешка:

``` 
java.lang.NullPointerException: Cannot invoke "java.security.Principal.getName()" because "principal" is null
	at com.example.Library.web.ProfileController.profile(ProfileController.java:25) ~[classes/:na]
```

Проблемът е, че за анонимни юзъри принципала е null, а в контролера имаш този код:

```
   @GetMapping("/profile")
    public String profile(Principal principal, Model model){
        ...
        String username = principal.getName(); <-- NPE e тук
       ....
   }
``` 

Не е логично да имаш анонимен юзър който идва тук. Когато се хвърли NPE спринг те редиректва към `/error`. Но и тази страница не е достъпна за анонимни юзъри, тъй като не е разрешена. Затова спринг те редиректва към логин страницата.

**Comment by luchob** [comment]
**Проблем 2)** 

_Също когато подам две различни пароли на pass и repass при регистрация не запазва данните в базата, но не дава и ерър_

Всъщност, хвърля ексепшън:

```
        if (!registrationDTO.getPassword().equals(registrationDTO.getRepeatPassword())) {
            throw new RuntimeException("passwords.match");
        }
```

Това те прехвърля към `/error` ендпойнта, който е забранен и отиваш на логин страницата. Виж предния проблем. Според мен трябва да правиш валидацията с валидатор и validation api а не с ексепшън. Виж например  [тук](https://github.com/luchob/softuni-may2022/blob/main/mobilele/src/main/java/bg/softuni/mobilele/model/validation/FieldMatchValidator.java).

**Comment by luchob** [comment]
**Проблем 3)** 

_също така и при логин нито ми показва ерърите, нито че потребителя вече съществува, или че има грешен потребител или парола._

При неуспешен логин поведението се конфигурира тук:

```
                failureForwardUrl("/login-error"). //"/users/login-error"
```

Спринг търси `@PostMapping` на този ендпойнт а такъв не съществува в проекта.

**Comment by luchob** [comment]
Проблем 4) 

_При addbook в html имам поле option и искам да го направя да ми показва авторите от репозиторито, опитвам се да го направя с th.each, но не ми се получава,_ 

Не успявам да видя `th:each` в авторите. Това което виждам е:

```
<div>
            <div class="form-group">
                <label for="authorList">Author</label>
                <select id="authorList" class="custom-select">
                    <option value="" selected>Select author</option>
                </select>
            </div>
        </div>
``` 

Всъщност, това което трябва да се направи е да се сложат авторите в модела преди зареждането на страницата и да се покажат в комбо.

Поздрави,
Л.
