### ISSUE TITLE
Submit HTML form does not persist data in the database

### ISSUE THREAD

**Issue by AngelJava123** [luchob/softuni-feb2023#41]
Здравей Лъчо,

Нуждая се от малко помощ за проекта ми, който разработвам. Та проблема е че когато събмитна Create Car Offer или Inquiry абсолютно нишо не се популира в базата данни, никакви ерори не ми излизат също и не мога да намеря каква точно е причината. С Login има проблем също. Всичко изглежда наред в структурата и кода на проекта и според мен не би следвало да има проблеми, но явно нещо аз пропускам предполагам. 

Ще съм благодарен ако го погледнеш и ми дадеш някакви насоки.

Поздрави,
Ангел

**Comment by luchob** [comment]
Здравей!

Погледнах го, но за съжаление изглежда че или гледам нещо което не трябва или има някакво по-сериозно недоразумение :-)

За Inquiry виждам контролера и там дори няма сървис, който се извиква:

```
@PostMapping("/inquiries")
    public String register(@Valid InquiryDTO inquiryDTO,
                           BindingResult bindingResult,
                           RedirectAttributes redirectAttributes) {

        if (bindingResult.hasErrors() || !this.inquiryService.send(inquiryDTO)) {
            redirectAttributes.addFlashAttribute("inquiryDTO", inquiryDTO);
            redirectAttributes.addFlashAttribute("org.springframework.validation.BindingResult.inquiryDTO", bindingResult);

            return "redirect:/inquiries";
        }

        return "redirect:/";
    }
```

За офертата извикването на сървиса е коментирано:

```
        //this.createService.create(createCarDTO, userDetails);
```

Като го разкоментирам, не намира метор с `userDetails` аргумент в сървиса. Самият сървис има грешки, например следните липсващи методи:

```
this.categoryRepository.findByCategory(createCarDTO.getCategory().getCategory());
this.gearBoxRepository.findByGearBoxType(createCarDTO.getGearBox().getGearBoxType())this.colorRepository.findByPaint(createCarDTO.getColor().getPaint());
```

За да се опитам да помогна, ми трябва проект, който да мога да пусна.

Оставам issue-то отворено за обратна връзка.

Поздрави,
Л.

**Comment by AngelJava123** [comment]
Здравей Лъчо, 

Извинявам се за причиненото неудобство.

Благодаря за бързата реякция. Причината поради която съм коментирал сървиса е тази че съм го добавил директно горе в в проверката if (bindingResult.hasErrors() || !this.inquiryService.send(inquiryDTO)) { така че ако не се изпълни ще върне директно false от метода в сървиса. Не знам дали така е най-удачно но по принцип работи по този начин. 

Изоращам ти линк към release със zip на целия ми проект, така че да можеш да го пуснеш:

https://github.com/AngelJava123/Java_WEB_Dev_And_Fundamentals/releases/tag/java

Ако случайно не работи линка изпращам и линк на репото като единствения release отстрани е именно този проект:

https://github.com/AngelJava123/Java_WEB_Dev_And_Fundamentals

или

https://github.com/AngelJava123/Java_WEB_Dev_And_Fundamentals/releases

Интересното е че няма никакви индикации за грешки. които излизат така че да мога да се ориентирам поне малко и от там за заходя с търсене на решение. Просто вече два пълни дни без успех се опитвам да разбера причината това да се случва. 

Благодаря за вниманието което отделяш. 

Ще очаквам някаква помощ. ;)

**Comment by luchob** [comment]
Здравей! 

Отново липсват методи в репозиторитата в zip-a, но си ги написах сам. Няма значение. Няколко насоки:

На първо място, папката с assets не е видима, защото т.нар. `atCommonLocations()` не включва папка `assets`. Трябва да се разреши, напр:
```
                antMatchers("/assets/**", "/contact", "/inquiries", "/terms", "/create").permitAll().
```
Или да си преместиш асетите на мястото, което спринг счита за "common location" (images, js и css). 

По същество сега. Няма индикации за грешки и нищо не става, т.к. изобщо не се събмитва формата и нищо не стига до сървъра (можеш да провериш в Network tab-a). Ето този JS е проблемен:

```
if (name && email && mobile && message && terms) {
                                    // Submit the form programmatically
                                    document.getElementById("inquiry-form").submit();

                                    // Show success message
                                    alert("Your inquiry has been submitted successfully!");

                                    // Clear form fields
                                    document.getElementById("inquiry-form").reset();

                                    // Return to home page
                                    window.location.href = "/";
                                  }
```

Ако кометираш `window.location.href = "/";` ще се увериш.

Защо това е така, може да прочетеш [тук](https://stackoverflow.com/questions/7985930/is-form-submit-synchronous-or-async). 

Поздрави,
Л.

**Comment by AngelJava123** [comment]
Здравей Лъчо,

Изключително много съм ти благгодарен за помощта, не знам какво да кажа :) Иначе погледнах линка който ми изпрати и разбрах защо по този начин се държи приложението сега :). Относно методите в репотата не знам защо при теб не се появяват при мен си ги има. Отново много благодаря. 

Поздрави,
Ангел
