### ISSUE TITLE
Помощ за снимките :'(

### ISSUE THREAD

**Issue by IvailoB** [luchob/softuni-feb2023#42]
Привет! 
Аз съм с проекта, чийто снимки до момента ми играят в контра.
Благодарение на вас от последната лекция успях да запазя нещо в базата, но не точно това е желания резултат.

Аз мисля че трябва да приема някакъв Set<MultipartFile> за да се запази в базата множество снимки за един продукт.
И точно там удрям на камък, както после и при визуализацията. 
Дали това е по- добре всичко това да го направя на отделен controller & service. 

Може ли да хвърлите едно око над проекта и да споделите мнение. Благодаря! :-)
https://github.com/IvailoB/SoftUni-Java-WEB/tree/main/CarWeb/CarWeb

**Comment by IvailoB** [comment]
също така когато прехвърлих на Secutiry 
 requestMatchers(PathRequest.toStaticResources().atCommonLocations()).permitAll()  
има нещо доста странно защото като всички снимки не ми ги открива а css  го намира.
Как трябва да е в html -> в момента е така   src="/image/homeimg.jpg" - НЕ ГО НАМИРА
                                                                           href="/css/index.css" - НАМИРА ГО

**Comment by luchob** [comment]
Здравей, според мен ще ти е много по-лесно да го направиш на отделен контролер. Т.е. след като създадеш офертата да може да и добавяш по-късно картинки. Показването им е 1:1 с демото.

Относно втория въпрос проблемът е тривиален:

```
PathRequest.toStaticResources().atCommonLocations()
``` 
Под "common location" за картинките спринг разбира images (с s отзад), а не image.

Поздарви,
Л.
