### ISSUE TITLE
Въпрос за Thymeleaf достъп до Модел атрибут

### ISSUE THREAD

**Issue by ViliIlieva** [luchob/softuni-feb2023#43]
Имам заявка с която взимам всички order от базата данни. 
Като в клас Order имам  

@ManyToMany(fetch = FetchType.EAGER) 
private List<PurchasedProducts> orderedProducts = new ArrayList<> (); 

@ManToOne
private User client; 
 
Как със Таймлийф мога да достъпя полето клиент и листа от продукти към всяка поръчка.
Направила съм си th:each="order : ${allOpenOrders}", но имам достъп само до базовите полета

**Comment by thrako** [comment]
Здравейте колега,

Синктаксисът за th:each изглежда правилен ( https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#using-theach ). Проблемът, най-вероятно се корени в това, което се подава като model attribute в контролера, т.е. това, което стои зад allOpenOrders.

Може ли да споделите цялото repo, за да го разгледам? Имах подобен проблем с List и ако мога, с радост ще помогна. 

Поздрави,
Траян

**Comment by ViliIlieva** [comment]
Май успях да се преборя но се оказа само със client. Май не успявам да итерирам по листа, преди да напиша th:object ми засича листа, но когато напиша обекта отдолу и вече ми дава че не намира този обект
<tr th:each="prod : *{orderedProducts}"
                th:object="${prod}">

**Comment by luchob** [comment]
Здравей!

По някаква причина не мога да се ориентирам къде е репозиторито. Ако е https://github.com/ViliIlieva/MyKnitShop то вече не е видимо.

Поздрави,
Л.

**Comment by ViliIlieva** [comment]
сега ще го пусна видимо

**Comment by ViliIlieva** [comment]
готово

**Comment by luchob** [comment]
Здравей!

Според мен, това което трябва да направиш е някакво DTO, което да се подаде в модела (не излагай entities). Ето тук:

```
model.addAttribute ("allOpenOrders", this.orderService.getAllOrders());
```

След това използването на `th:each` e сравнително тривиално и добре описано в [документацията на thymeleaf](https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#using-theach), както посочи и [thrako](https://github.com/thrako).

Поздрави,
Л.

**Comment by ViliIlieva** [comment]
Благодаря за бързия отговор и на двама Ви! Получиха се нещата
