### ISSUE TITLE
Проблем със секюрити в проекта за финал

### ISSUE THREAD

**Issue by MariaBonkova** [luchob/softuni-feb2023#44]
Привет, вече леко отчаяна и объркана в кода си. Направих регистрацията и добавянето на нов юзър в репото като се регистрира. Обаче сега проблема ми е че паролата не се енкодва. Направих в конфиг папката трите важни неща за секюрити. Честно копирах от твоя код копирах initServise  в моят userServiseImpl с надеждата да ми се кодира паролата. Обаче възникна друг проблем с който не знам как да се оправя  Could not resolve placeholder 'app.default.password' in value "${app.default.password}" това от една страна и  Error creating bean with name 'userServiceImpl' defined in file [C:\myProject\demo\target\classes\com\example\demo\service\impl\UserServiceImpl.class]: Unexpected exception during bean creation.
Сега в мен възниква двулменето това секюрити само за логване или и за регистриране трябва. Първоначално разбрах, че при логване трябва, сега се чудя с добавянето на ролите още при регистриране и енкодването трябва ли или не и как да го направя? Също се чудя и как трябва да направя ролите да се сменят когато се извърши някакво действие по сайта . Например искам като се отвори страницата в нав бара да пише гост, но като се регистрира вече да е купувач, като иде на бутон създай продукт да стане създател. Това наистина незнам къде в кода трябва да го напиша. Почват да изникват някакви стари спомени от курса по js, но съм много объркана.
С уважение М.
https://github.com/MariaBonkova/3D-printing-project/tree/master

**Comment by MariaBonkova** [comment]
Сега се сетих и още нещо в папка RoleServiceImpl съм направила initRole където ми пълни таблицата role. Сега тази информация от този сървиз трябва ли да я ползам при регистрирането на юзър и при логването.

**Comment by thrako** [comment]
Здравейте колега,

В src/main/resources/application.properties трябва да се сетне `app.default.password = [някаква парола]`, иначе няма как `@Value("${app.default.password}")` да я открие и да я замести. Тази операция не "кодира" паролата, а взема стойността ѝ от application.properties файла. Това, което се обсъждаше по време на последната лекция е как стойността на паролата да се скрие и да не се качва в GitHub, а начинът е като се сетне в environment variable. Лъчо го обяснява доста подробно [тук](https://softuni.bg/trainings/resources/video/81398/video-13-march-2023-lachezar-balev-spring-advanced-february-2023/3971) от 2:49:00 нататък.

По отношение на ролите и по-специално за тези, които не са се логнали в Spring Security може да се зададе достъп до определени страници само за такива потребители, ето така:
```
httpSecurity
            .authorizeHttpRequests()
                .requestMatchers("/test").anonymous() 
```
Съответно в .html файла, може да се провери с Thymeleaf Security дали потребителят е логнат, ето така например:
```
<div sec:authorize="isAnonymous()">
    <a th:href="@{/login}">Login</a>
</div>

<div sec:authorize="isAuthenticated()">
    <p>Logged in as: <span sec:authentication="name">Bob</p></span>
</div>
```
Съответно може да се преработи, така че да пише `guest` за потребител, който не се е логнал, не е необходимо да се създава специална роля за това.

По отношение на останалите роли, според мен не е необходимо ролите на потребителя да се сменят в зависимост от това на коя страница се намира (съответно дали е купувач, създател и т.н.). Идеята на ролите е да определят кой потребител с какви права разполага. Ако въпросът касае това определен потребител да може да трие / променя собствената си информация (напр. обява, коментар и т.н.) или собственият си профил, то и аз, и други колеги сме питали и Лъчо е обещал да ни покаже demo по-напред как става. Иначе наивната имплементация е в съответния метод в контролера, с който се визуализира страницата, напр. "offers/8" да се извиква Principal и да се проверява дали id-то на Principal-а == id-то на автора на офертата с id 8.

П.П.
Извинявам се, че се намесвам, то е само от желание да помогна. Мисля, че е хубаво да си помагаме помежду си (утре може да сме с разменени роли), а и така пестим някакво време на Лъчо. 

Поздрави,
Траян

**Comment by luchob** [comment]
Благодаря за помощта, мисля че отговорът е много добър!

Само бих добавил че четенето на ролите на юзъра става в [UserDetailsService-a](https://github.com/luchob/softuni-feb2023/blob/main/security-demo/src/main/java/bg/softuni/security/service/ApplicationUserDetailsService.java#L36), а това кой какво вижда и може става в [SecurityConfiguration-a](https://github.com/luchob/softuni-feb2023/blob/main/security-demo/src/main/java/bg/softuni/security/config/SecurityConfiguration.java#L33) и на ниво [thymeleaf](https://github.com/luchob/softuni-feb2023/blob/main/security-demo/src/main/resources/templates/fragments/navbar.html#L21). 

Ако се налага още веднъж ще го повторим. Погледни ги внимателно, заедно с горния отговор и ако продължава да е неясно отваряй issue-s, ще се мъчим да помагаме.

Поздрави,
Л.

**Comment by MariaBonkova** [comment]
Благодаря момчета! Почвам да чета отново и отново и да осмислям написаното!БЛАГОДАРЯ!
