### ISSUE TITLE
403 CORS Error

### ISSUE THREAD

**Issue by ChrisVladimirov** [luchob/softuni-feb2023#45]
Здрасти, Лъчо!

От доста дни се мъча с правенето на заявки от фронтенда ми на реакт (**localhost:3000**) към rest api-то ми (**localhost:8080**). Всичко е наред с `GET` и `POST` заявките, но стигне ли се до `PUT`, `PATCH`, `DELETE`, хвърля 403 CORS Error "_Access to fetch at 'http://localhost:8080/admins/promote?userId=2' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled._"

През Postman всичко е наред с всеки вид заявка, но в бразузъра - гърми винаги при всякаква конфигурация.
Опитах с:
- `@CrossOrigin`(origins="http://localhost:3000") 
- CorsConfigurationSource бийн в SecurityConfig
- CorsRegistry
- имплементация на CorsFilter 
- добавяне и махане на `.cors().and()` в SecurityFilterChain бийн
- микс от различни подходи...
Но все едно и също в браузъра :(

https://pastebin.pl/view/7c6bed22 -> SecurityConfig
https://pastebin.pl/view/a99856db -> AdminController

Моля те за помощ с CORS. Честно казано, много ме отчайва вече. 
Поздрави.

**Comment by luchob** [comment]
Здравей!

Може ли да започнем от някъде :-) Например, по най простия начин - да махнем всичко cors related и да сложим една анотация 

```
@CrossOrigin(origins="http://localhost:3000")
``` 

или още по-просто дори:

```
@CrossOrigin("*")
``` 

Като следваща стъпка ми се иска да видя един preflight request и един нормален който фейлва. За целта можеш да ги експортнеш в "har" формат с dev tools-a на браузъра, ако ползваш хром.

Поздрави,
Л.

**Comment by ChrisVladimirov** [comment]
Здрасти, Лъчо!

Тук е резултатът при:
- закоментирано всичко с cors, като имаме само `@CrossOrigin("*")` на контролерите;
- `@CrossOrigin("*")` на контролерите и `cors().and().` в SecurityFilterChain.

[failing_options-patch-requests.zip](https://github.com/luchob/softuni-feb2023/files/10995087/failing_options-patch-requests.zip)(url).

При заявки с особен метод (`patch` например) липсва Access-Control-Allow-Origin header. При един от предишните злощастни опити с cors пробвах да имплементирам CorsFilter, така че ако липсва хедъра, да го слага със стойност като "*" или направо "http://localhost:3000". Тогава съвсем се чупеше всякаква заявка (`get` в това число).

**Comment by luchob** [comment]
Здравей!

За сега набързо може единствено да ти кажа, че проблемът е че сървърът не е конфигуриран да позволява неаутентициран OPTIONS request (което е нормално за web-app).

<img width="964" alt="Screenshot 2023-03-16 at 21 51 18" src="https://user-images.githubusercontent.com/10339738/225737176-9c601034-6d0f-447d-9659-2b120d6eebc6.png">

Оттам нататък няма никакви CORS headers, филтри, анотации и т.н. и резултата е ясен - гърмиш. Може би ще ми е интересно да погледна целия проект, ако е възможно.

Поздрави,
Л.

**Comment by luchob** [comment]
Здравей!

Всъщност се опитваш да конфигурираш спринг като ресурс сървър където да се логваш и в същото време сървърното приложение да обработва JWT token-a, правилно ли разбирам? Все едно тази схема но горните кутийки са 1 апп:

<img width="579" alt="Screenshot 2023-03-19 at 9 35 40" src="https://user-images.githubusercontent.com/10339738/226160750-870b9500-c172-4cd9-a60d-e7139b19c86e.png">

Интересно, с ресурс сървъра съм експериментирал веднъж само. Може да се опитам да си поиграя и аз, но не ти обещавам бърз отговор в никакъв случай :-) Може ли едно примерно `application.yaml` с локални настройки?

Поздрави,
Лл

**Comment by ChrisVladimirov** [comment]
Здрасти, Лъчо!

Стана ясно, че проблемът е от това как фронтендът (React в моя случай) подава http методите за всяка заявка. При мен явно така съм го бил написал, че те идват в lowercase (`patch` вместо `PATCH` например), докато spring ги очаква само в uppercase. Като резултат, не разпознава метода, спира да ползва моята конфигурация за cors, а избира своята по подразбиране (с `GET`, `HEAD`, `POST` като единствени позволени методи) и хвърля 403.

Сега работи в този вид:
![image](https://user-images.githubusercontent.com/84380496/226735174-c071284a-2334-422d-ae74-07644c44909d.png)

Благодаря все пак за отделеното време и извинявай, че те занимах с това.

Поздрави,
Крис.

**Comment by luchob** [comment]
Ха-ха, уау! :-) Е точно това много трудно щях да се усетя без апп-а :-)

Поздрави,
Л.
