### ISSUE TITLE
Два въпроса относно проекта 

### ISSUE THREAD

**Issue by cUserd** [luchob/softuni-feb2023#46]
Здравей Лъчо,

Имам два въпроса и мисля че ща са доста лесни :)

1. Имплементирах си качването на снимка и файл за което много благодаря, но се чудя как бих могъл да вкарам multipart file 
 в init service или с други думи когато запали приложението да си направи нови готови модели за да не седи празен сайта.  Как се задава от къде да вземе снимка статично(от папка) без да се ъплодва от форма. 

2.  в controllera имам pathvariable да кажем /detail/{id} и като се се зареди в браузера всички ресурси и фрагменти започват да се търсят от /detail вместо от стандартната локация static/.../ и доста се измъчих, но неможах да го докарам да ги търси от правилното място опитах с "../" , с абослютен път и още импровизирани варианти, но без успех.

**Comment by rd-lachezar-balev** [comment]
Здравей!

Относно първия въпрос - `MultiPartFile`-а е нещо, което описва документ в multipart request. Ако минем на HTTP ниво, изглежда ето така:

```
POST /cgi-bin/qtest HTTP/1.1
Host: aram
Content-Type: multipart/form-data; boundary=2a8ae6ad-f4ad-4d9a-a92c-6d217011fe0f
Content-Length: ...

--2a8ae6ad-f4ad-4d9a-a92c-6d217011fe0f
Content-Disposition: form-data; name="datafile1"; filename="text1.txt"
Content-Type: text/plain

Hello, world!
--2a8ae6ad-f4ad-4d9a-a92c-6d217011fe0f
Content-Disposition: form-data; name="datafile2"; filename="text2.txt"
Content-Type: text/plain

Hello world 2!
--2a8ae6ad-f4ad-4d9a-a92c-6d217011fe0f
```

Ако искаш да наливаш нещо в init по скоро ти трябва ресурс, напр:
```
Resource image = new ClassPathResource(...);
``` 
В крайна сметка в базата вкарваш byte array, а не MultiPartFile. Ако не е така имаш по-скоро нужда от малък рефакторинг :-) А в света на тестовете има `MockMultipartFile`. Всъщност самата имплементация на MultipartFile не е сложна, но мисля че за целта ти е излишна.

**Comment by luchob** [comment]
Вторият въпрос не съм сигурен дали го разбирам, но погледни [този отговор](https://github.com/luchob/softuni-feb2023/issues/17#issuecomment-1451862789).

Иначе при търсене папката в `/resources/static` играе ролята на `/` в linux ако може така да се изразя :-)

Поздрави,
Л

**Comment by cUserd** [comment]
Благодаря за отговорите. Както винаги точно в целта :)
