### ISSUE TITLE
Thyleaf/Spring security 

### ISSUE THREAD

**Issue by IvailoB** [luchob/softuni-feb2023#48]
and().
                // configure login with HTML form
                        formLogin().
                loginPage("/users/login").
                // the names of the user name, password input fields in the custom login form
                        usernameParameter("username").
                passwordParameter("password").
                // where do we go after login
                        defaultSuccessUrl("/home").//use true argument if you always want to go there, otherwise go to previous page
                failureForwardUrl("/users/login-error").
Това е кода за логване. Обаче незнам защо но при успешен вход ме праща на - > http://localhost:8080/main.js?continue
От къде може да идва проблема. 

Thymeleaf Sec
<dependency>
            <groupId>org.thymeleaf.extras</groupId>
            <artifactId>thymeleaf-extras-springsecurity5</artifactId>
            <version>3.1.1.RELEASE</version>
        </dependency>
Както лектора така и аз ползвахме това дипендънси за таймлийф. Но когато написах sec:authorize="isAuthenticated()" § sec:authorize="isAnonymous()" § sec:authorize="hasRole('ADMIN'). нищо не работи като продължавам да виждам всички бутони на навигацията. Като изкопирах навигацията от pathFinder пак без резултат.

Търсих инфо из нета с различни дипендънси.... Е ето ме пак :–)

**Comment by thrako** [comment]
Здравейте колега,

> Това е кода за логване. Обаче незнам защо но при успешен вход ме праща на - > http://localhost:8080/main.js?continue

Предполагам, че достъпът до файл: `main.js` е с достъп само за логнати потребители. Съответно при зареждане на страницата, която сочи към този файл, Spring Security препраща към login страницата. След успешен login редиректва към последната страница (преди login формата) и затова добавя `?continue` в края на пътя. Пробвайте да разрешите пътя до `main.js` файла с `.permitAll()` или да го преместите в някоя от папките, които се приемат от Spring Security  за "common locations" - като щракнете върху `atCommonLocations` в конфигурацията, може да видите кои са.

> Thymeleaf Sec
>
> org.thymeleaf.extras
thymeleaf-extras-springsecurity5
3.1.1.RELEASE

Необходима е шеста (6) версия на thymeleaf-extras-springsecurity. Най-добре да не се указва release версия (в смисъл: 3.1.1.RELEASE), Spring Boot се грижи за това.
```
<dependency>
  <groupId>org.thymeleaf.extras</groupId>
  <artifactId>thymeleaf-extras-springsecurity6</artifactId>
</dependency>
```

Пробвайте горното и ако не проработи, споделете GitHub линк към проекта.

Поздрави,
Траян

**Comment by ViliIlieva** [comment]
а в html-а най-горе поставил ли си това

lang="en"
      xmlns:th="http://www.thymeleaf.org"
      xmlns:sec="http://www.thymeleaf.org/extras/spring-security">

**Comment by luchob** [comment]
Благодаря за изчерпателния отговор на [thrako](https://github.com/thrako) :-)
