### ISSUE TITLE
Въпроси от предния модул за Лекция REST API

### ISSUE THREAD

**Issue by ViliIlieva** [luchob/softuni-feb2023#5]
1.	За какво е анотацията @RequestBody?
2.	Какво е @ResponseBody?
3.	Каква е разликата между @Controller и @RestController?
4.	Как може да контролираме HTTP response status-a на response-a, който връщаме на клиента?
5.	Какво е RestTemplate?
6.	С какво ще бъде заменен RestTemplate в бъдещи версии на Spring?

**Comment by luchob** [comment]
Здравей! 

Бих отговорил по следния начин, стараейки се отговорът да е достатъчно разбираем и опростен:

1. Анотацията `@RequestBody` казва на Spring, че тялото на HTTP заявката трябва автоматично да се преобразува до DTO (Data transfer object). Обикновено се слага пред аргумент на метод на контролер.
2. Анотацията `@ResponseBody` казва на Spring, че обектът връщан като резултат от метод/методите на контролер трябва автоматично да се сериализира до JSON (по подразбиране).
3. Както се вижда от кода, `@RestController` е `@Controller` + `@ResponseBody`

```
@Controller
@ResponseBody
public @interface RestController {
}
```
4. По най-различни начини. Например с анотация `@ResponseStatus`върху метод, ексепшън. Или връщайки `ResponseEntity` и използвайки API-то му.
5. Клас с който може да консумираме REST API в Spring приложение.
6. С WebClient.
