### ISSUE TITLE
настройки на базата?

### ISSUE THREAD

**Issue by IvailoB** [luchob/softuni-feb2023#50]
не съм сигурен дали това е настройка на базата или не, но от workshopa последния път,
когато качваме снимките на cloudinary.
При мен се появяват в профила ми но не ги виждам в базата.
А когато се опитам да запазя в базата имам следната грешка ->
object references an unsaved transient instance - save the transient instance before flushing 
.........
Та идеята ми е как от cloudinary се запазват нещата в базата. Може да съм пропуснал нещо.

**Comment by luchob** [comment]
Упс... Нека да го кажем така. Това не е от настройки на базата, нито има каквото и да е общо с cloudinary или пък с някакъв уъркшоп :-) Да забравим за тях.

Ключът е в hibernate (Spring Data) и твоите ентитита. Представи си, че имаш една такава структура:

```
@Entity
@Table(name = "parent")
public class ParentEntity {

  @OneToMany
  private List<ChildEntity> children;

}

```
Едно entity може да се намира в няколко състояния, напр:

`New`: най-обикновен клас, който никога не е бил асоцииран с хибернейт, напр ето това: `new ParentEntity()`;
`Managed`: асоцииран е с някакъв ред в ДБ и се управлява от хибернейт.
`Detached`: веднъж когато обекта спира да се следи от хибернейт.

Кога се получава грешката: _object references an unsaved transient instance - save the transient instance before flushing_

Когато например записваш ново `ParentEntity` то става managed но всяко `ChildEntity` е все още NEW. И хибернейт се сърди. Това може да се реши по различни начини, но един от тях е да се добави `CascadeType` в анотацията на асоциацията. Това ще подскаже на хибернейт че искаш да запазиш и децата в тази асоциация.

За one to many и one to one може да изглежда така:

```
@OneToOne(
    ...
    cascade = CascadeType.ALL)
@OneToMany(
    ...
    cascade = CascadeType.ALL)
```

С тази информация би трябвало да успееш да оправиш грешката, най-вече защото ще я разбереш.

Поздрави, 
Л.
