### ISSUE TITLE
Проблемите се задълбочават с финаллният проект!

### ISSUE THREAD

**Issue by MariaBonkova** [luchob/softuni-feb2023#51]
Привет, пиша, добавям, копирам код и нещата стават все по-омазани. Ако, не ми кажеш къде съм оплескала мисля, че ще затъна като свиня в собственото си блато/проект/.
1. С инициализирането на роли го промених, разбрах каква е идеята на ролите. Там пароли мароли всичко се направи.  Проблема обаче идва като добавям юзър от вън. Паролите пак не се критират, иначе юзърите се добяват хубаво в юзър репозиторито, също излизат ми грешките там където трябва да са. В бъдеще обаче ако трябва да добавя в репото някой админ или модератор не съм сигурна, че ще стане, защото в това репо се добавят и юзърите от вън. 
2.  Огромният проблем с логина. Там вече незнам от къде идва проблема. И при верен и неверен юзър нищо не се случва. В чейна мисля, че правилно съм задала настроиките, в контролера нали трябва само @GetMapping и когато  е верен юзъра секюритито оправя нещата и ме редиректва към хоума и задава сесия. Когато е грешен юзъра съм сложила @PostMapping към дефолтната страница с error.  Защо ми създава този въртел?  Другото което не разбирам, е защо не ми излизат  грешните месиджи, който съм задала в userLoginDtо, когато задам грешни данни за логване. 
3. Реших да добавя и в нав бара модератор и админ като надписи да се появяват и там отново гръмна проблем. Като кликна върху тях ми отварят логин страницата. В хоум контролера съм и задала на къде да ходят. Трябва ли още да ги конфигурирам един господ знае и най-вероятно и ти. 
Благодаря предварително М.

**Comment by MariaBonkova** [comment]
https://github.com/MariaBonkova/3D-printing-project

**Comment by luchob** [comment]
Здравей! 

Наистина е малко в повечко копирането, трябва и триене от време на време.

Въпрос 1) 

В регистрацията виждам този код:

```
if (bindingResult.hasErrors() || !this.authService.register(userRegisterDto)) {
            ...
    }
        userServiceImpl.registerUser(...)
```

Допускам, че този излишен код `this.authService.register` е остатък от pre-security ерата. Той вкарва юзъра в ДБ, разбира се не хешира (криптирам и хеширам са различни неща) паролата. След това се идва `userServiceImpl.registerUser` който се мъчи да вкара същия юзър, обаче гръмва както може да видиш в конзолата, защото имаш unique констрейнт в базата по username+useremail. Така остава записа с нехешираните пароли.

**Comment by luchob** [comment]
Относно въпрос 2 и защо не ти работи логина. Имаш бъг в `UserDetailsService`-a:

```
public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {
        return
                userRepository.
                        findUserEntityByEmail(username).
                        map(this::map).
                        orElseThrow(() -> new UsernameNotFoundException("User with name " + username + " not found!"));
    }
```
Подаваш `username` а търсиш в `email`. Това разбира се никога не работи.

**Comment by luchob** [comment]
Бих искал да си редактирам предния отговор.

Освен този бъг има и няколко други. Когато ползваш спринг буут, никога не слагай версии на стартерите, защото затова се грижи спринг буут. Ето така

```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
```

Липсва ти депендънси към:

```
        <dependency>
            <groupId>org.thymeleaf.extras</groupId>
            <artifactId>thymeleaf-extras-springsecurity6</artifactId>
        </dependency>
```

 Тук също трябва да вземеш юзър нейма, а не имейла:
```
     private UserDetails map(UserEntity userEntity) {
        return new User(
                userEntity.getUserName(),
                userEntity.getPassword(),
                extractAuthorities(userEntity)
        );
    }
```

Вече спринг секюрити се грижи за нашия логин, затова нямаш и ДТО в auth-login.html. Погледни нашия auth-login.html в security-demo. И синхронизирай с:

```
             usernameParameter(UsernamePasswordAuthenticationFilter.SPRING_SECURITY_FORM_USERNAME_KEY).
              passwordParameter(UsernamePasswordAuthenticationFilter.SPRING_SECURITY_FORM_PASSWORD_KEY).
```

Това са имената на inputs от нашата къстъм логин страничка.

Като оправиш тези неща трябва да тръгне всичко :-) Надявам се.

Поздрави!
