### ISSUE TITLE
Каква може да е причината да не ми хваща грешките

### ISSUE THREAD

**Issue by ViliIlieva** [luchob/softuni-feb2023#52]
https://github.com/ViliIlieva/MyKnitShop  
В orders.html при http://localhost:8080/orders когато добавям съобщение от най-долното поле, не ми хваща грешката че съобщението трябва да е минимум 10 символа
За html-а съм копирала директно от работеща страница със същите грешки, уж във ДТО-то също имам валидации и в пост метода в OrderControlera съм сложила @Valid MakeOrderDTO makeOrderDTO, BindingResult

От падащото меню се избират номерата само на поръчки които са Completed и все още нямат оставен коментар.
Ако може да погледнеш къде греша

Благодаря

**Comment by luchob** [comment]
Здравей!

Вероятно, защото обекта в thymeleaf се казва 

```
th:object="${messageAddDTO}"
``` 

А ти залагаш `messageDTO` в модела:

```
 redirectAttributes.addFlashAttribute("messageDTO", messageDTO);
            redirectAttributes.addFlashAttribute(
                    "org.springframework.validation.BindingResult.messageDTO", bindingResult);
```

Валидацията на сървъра работи със сигурност.

Поздрави,
Л.

**Comment by ViliIlieva** [comment]
Благодаря отново!
