### ISSUE TITLE
Продължваме логин драмата

### ISSUE THREAD

**Issue by MariaBonkova** [luchob/softuni-feb2023#53]
Привет отново, с регистрацията оправих нещата, но логина продължава да се гаври с мен. Стъпките, който ми беше изпратил ги направих добавих дипендънси, оправих в юзърдетайл сървиса имейла с юзърнейм, в конфигурацията на чейна в логина върнах параметрите. Сега проблемите са следните:
1. като логна съществуваш лузър, не ме редиректва към хоума, а ме държи отново на логина. Проверявам с инспект в кукито се появява джейсесъш ид. Също така в нав бара не ми се сменят командите да се появи логаута и да се скрият регистрация и логин. В хтмл логин мисля, че са коректни до колкото успях да разбера кое как се пише.
2. При неправилен лузър не им излизат месиджите Грешен юзърнейм или парола и тези който съм задавала в ДТО-то. 
3. Сега и тези новите бутони ми изчезнаха от навбара. Бутоните админ и модератор и най- вероятно продължва да стои проблема, че като ги кикна ме водят на логин страницата.
Благодаря за помоща М.

**Comment by luchob** [comment]
Здравей!

За да не стават грешки може да махнеш `UserLoginDTO` и да преименуваме всички `userName` на `username` за да е по безболезнено всичко. Вече всичко ще се върши от Спринг и има успешен/неуспешен логин. Успешния те прехвърля на `/home`, а неуспешния на `/users/login-error`. 

Като заговорихме за последното, мапингът `@PostMapping("/users/login-error")` е грешен, защото имаш
отгоре `@RequestMapping`. 

Вътре в логин формата трябва да имаш тези неща:


```
<input th:value="${username}" name="username" type="text" class="effect-1"  placeholder="Юзър нейм">
<input name="password"  type="password" class="effect-1" placeholder="   Парола">
```
както и проверка за `bad_credentials`. 

В `/users/login-error` редиректът е грешен, трябва да е към `redirect:/users/login`
Кодът:

```
    if (!model.containsAttribute("bad_credentials")) {
            model.addAttribute("bad_credentials", true);
        }
```

е странен :-) 

Администратор и модератор линка трябва да са невидими за нормален юзър ако всичко е ок и да водят към 403 страница за останалите.

Поздрави,
Л.
