### ISSUE TITLE
Помощ за контролери

### ISSUE THREAD

**Issue by cUserd** [luchob/softuni-feb2023#54]
Лъчо здравей, 

отново имам  питанe за проекта:

1. има ли възможност след като изтегля файл като изпозлвам  /download-model/{fileId} това кето показа във демото за изтегляне на файл да ме редирекне към същата страница за да мога да ъпдейтна информацията там от ДТО тата , понеже в момента връща HttpEntity и просто си го тегли и не се редиректва на никъде , но не съм сигурен как  и дали може стане.

всичко това се намира в /customer/web/ModelController на проекта ми ако намериш време да погледнеш ще съм благодарен

**Comment by cUserd** [comment]
2 отпадна намерих си грешката една буква бях изтървал :))

**Comment by luchob** [comment]
Здравей!

Не съм сигурен дали разбирам напълно въпросът, но това, което се връща от `/download-model/{fileId}` е един файл с `Content-Type` като `image/jpeg`, `image/png`, `application/pdf` и т.н. Ето например една картинка с url https://softuni.bg/Content/images/open-graph/university-default-og.png Какво става на ниво HTTP като я поискаш:

```
HTTP/1.1 200 OK
Server: nginx/1.18.0 (Ubuntu)
Date: Sat, 18 Mar 2023 20:13:45 GMT
Content-Type: image/png
Content-Length: 9355
Connection: keep-alive
Cache-Control: public,max-age=604800
Last-Modified: Thu, 02 Feb 2023 15:12:07 GMT
Accept-Ranges: bytes
ETag: "ed1340b71837d91:0"
X-Frame-Options: SAMEORIGIN

```
Body-то на респонсът е стрийм от байтове, които са самата картинка. Абе с две думи `/download-model/{fileId}` означава дай ми файл с ид xyz и това нещо би трябвало да връща:

- 200 + боди - картинката - ако всичко е наред
- 30х - ако картинката е на друго място или не си логнат и отиваш на логин страницата. **Нищо повече, свързано с DTO-та и подобни.**
- 401/403 - ако не си аутентициран/ауторизиран и не можеш да видиш картинката/докуметът
- 50x - ако нещо нередно се е случило на сървъра

Поздрави,
Л.

**Comment by cUserd** [comment]
Ами маи не  ме разбра  напълно :(  ... по скоро не съм се изказал какво искам да се случи както трябва.
 нека опитам отново
имам един бутон download като при кликане прави разни проверки и ако всичко е успешно те води на този ендпоинт  /download-model/{fileId} и си изтегля файла и всичко е наред. На мен ми трява при кликането освен да те заведе на този ендпоинт и да се рефрешне страницата където е бутона .. защото там имам информация която пристига от разни ДТО та 
например "фаила е изтеглен N брой пъти" и когато се изтегли отново (цъкне бутона) да се визуализира новото число (n+1). Положението сега е цъкам бутона сваля файла , но надписа си седи "фаила е изтеглен N брой пъти"  давам F5 за 
рефреш и вече става "фаила е изтеглен (n+1) брой пъти". Сега ми идват разни идеи във HTML да потърся нямаше ли нещо за рефрешване при клик на бутон.

**Comment by thrako** [comment]
Привет,

Ако правилно съм разбрал, изглежда като че ли ти е необходим location.reload(). https://stackoverflow.com/questions/3715047/how-to-reload-a-page-using-javascript

EDIT:  Ако така или иначе трябва да се използва javascript, аз не бих презареждал цялата страница (излишен трафик), а бих обновил само конкретната част от страницата. С Fetch API теглиш информацията от backend-а и с javascript манипулираш съответната част от DOM-a. 

Поздрави,
Траян

**Comment by luchob** [comment]
Здравей! Това нещо трябва да се направи с JS, няма да стане със server side код.

Поздрави,
Л.

**Comment by cUserd** [comment]
Благодаря и аз не можех да си го представя как ще стане server side :) ами явно JS
