### ISSUE TITLE
Логин драмата

### ISSUE THREAD

**Issue by MariaBonkova** [luchob/softuni-feb2023#55]
Привет, Лъчо! Оправих всичко по насоките и познай? Няма напредък. Когато логвам юзър който се е регистрирал от вън мисля че нещата стават, но не ме редиректва а стоя на логин, но и нав бара не се сменя.  Когато искам да логна Админа който съм инициализирала ми го дава грешен юзър и парола. Паролите на всички са 111 евентуално ако искаш да тестваш. Отварям инспекта да видя тези кукита и при верен и неверен ми се появяват джейсесънид. 
Мисля че в нав бара във фрагмента съм ги задала коректно. 
Извинявам ти се, че вече сигурно ставам досадна и може скоро да ме блокираш, но това трябва да го направя, че другите неща пак мен чакат. БЛАГОДАРЯ ТИ МНОГО ЗА ПОМОЩА!

**Comment by luchob** [comment]
Привет!

Исках да тествам, но паролите не са 111 а са `print`. :-) Първото, което ми се иска е да оправим проблемът с favicon, който се случва. Ако няма зададена favicon (тази малка картинка, дето се показва в таба на браузърът) той самичък си я търси на `http://localhost:8080/favicon.ico`. Погледни в Network tab-a. Предпоследната заявка след отварянето на логин иска favicon. Тази заявка идва не от теб а самоволно от браузъра. Само че, понеже favicon-a е забранена на този адрес, спринг редиректва към логин страницата и запомня това място като последно посетеното към което да те върне след логин. Оттам идва големия ти проблем и грешката след логин. 

Нека оправим този проблем като си нарисуваш някаква favicon-a и я поставиш на разрешено място, напр в `/images/favicon.ico` и после сложиш следния код на хоум страницата и на логина:

```
<link rel="icon" type="image/x-icon" th:href="@{/images/favicon.ico}">
```

След това пускаме сайта, влизаме с админ и...


<img width="1452" alt="Screenshot 2023-03-19 at 8 50 47" src="https://user-images.githubusercontent.com/10339738/226159501-8c10e986-de19-47d2-9eae-39ad29aad6fb.png">

<img width="1461" alt="Screenshot 2023-03-19 at 8 58 42" src="https://user-images.githubusercontent.com/10339738/226159485-b7f0eb1c-4c85-4f9d-9a09-b6d542763121.png">

:-)

Поздрави,
Л.
