### ISSUE TITLE
[wishlist] Authorization by Author 

### ISSUE THREAD

**Issue by thrako** [luchob/softuni-feb2023#57]
Здравей,

И аз, и други колеги са питали, как да разрешим на конкретен User да трие и променя съдържанието, което е генерирал (например автор на коментар). На workshop-а Кристиян ни показа доста наивна имплементация: при извикване на съответния метод в контролера, който мапва "/comments/delete/{id}" примерно, по id на коментара, взема автора и проверява дали Principal-a и автора съвпадат. Ясно е, че работи, но ми се струва много дървено, освен това във frontend-а имаме delete бутони на всеки коментар, а не само на коментарите, чийто автор е текущия логнат User.
Сигурен съм, че има по-елегантно решение (просто все още не зная точно какво е). Вероятно нещо през Roles или GrantedAuthorities, или някой друг клас, който се грижи за privilegies / permissions. В идеалния случай, бих искал, в Thymeleaf да мога да използвам нещо като: ``` sec:authorize="hasAuthority('WRITE_AUTHORITY')" ``` или ```sec:authorize="hasAnyRole('ROLE_AUTHOR, ROLE_MODERATOR, ROLE_ADMIN')" ``` и така да определям на кой user да визуализирам delete / update бутони. 

Поздрави,
Траян

**Comment by luchob** [comment]
О, да, има доста меко казано "гъзарско" решение. Искаш ли да го пробваш, в Спринг 3 има няколко промени. Да си представим мобилето и юзъра който може да трие единствено своите оферти (разбира се, условията може да са най-различни, например админа да трие всяка оферта и т.н. и т.н.). Трябва ни, разбира се сървис:

```
@Service
public class OfferService {

  public boolean isOwner(String userName, UUID offerUUID) {
    //todo
    return true;
  }

  public void deleteOfferByUUID(UUID uuid){
   //todo
  }

}
```

След това имплементация на `MethodSecurityExpressionOperations`, например:

```
public class OwnerSecurityExpressionRoot
    extends SecurityExpressionRoot
    implements MethodSecurityExpressionOperations {

  private final Authentication authentication;
  private final OfferService offerService;
  private Object filterObject;
  private Object returnObject;

  public OwnerSecurityExpressionRoot(Authentication authentication,
                                     OfferService offerService) {
    super(authentication);
    this.authentication = authentication;
    this.offerService = offerService;
  }

  public boolean isOwner(UUID id) {
    if (authentication.getPrincipal() == null) {
      return false;
    }

    var userName = authentication.getName();

    return offerService.isOwner(userName, id);
  }

  @Override
  public void setFilterObject(Object filterObject) {
    this.filterObject = filterObject;
  }

  @Override
  public Object getFilterObject() {
    return filterObject;
  }

  @Override
  public void setReturnObject(Object returnObject) {
    this.returnObject = returnObject;
  }

  @Override
  public Object getReturnObject() {
    return this.returnObject;
  }

  @Override
  public Object getThis() {
    return this;
  }
}
```

Тук вълшебното методче е `isOwner`, обърни му внимание, останалото е лепило.
След това, например едно MobileleSecurityExpressionHandler:

```
public class MobileleSecurityExpressionHandler extends DefaultMethodSecurityExpressionHandler {

  private final OfferService offerService;

  public MobileleSecurityExpressionHandler(OfferService offerService) {
    this.offerService = offerService;
  }

  @Override
  protected MethodSecurityExpressionOperations createSecurityExpressionRoot(Authentication authentication, MethodInvocation invocation) {

    OwnerSecurityExpressionRoot root = new OwnerSecurityExpressionRoot(authentication, offerService);

    root.setPermissionEvaluator(getPermissionEvaluator());
    root.setTrustResolver(new AuthenticationTrustResolverImpl());
    root.setRoleHierarchy(getRoleHierarchy());

    return root;
  }
}
```

Накрая една конфигурация за изкарване на тази чудесия, обърни и внимание на анонациите:

``` 
@Configuration
@EnableMethodSecurity//<-- !!!
public class MobileleMethodSecurityConfig {

  private final OfferService offerService;

  public MobileleMethodSecurityConfig(OfferService offerService) {
    this.offerService = offerService;
  }

  @Bean
  public MethodSecurityExpressionHandler createExpressionHandler() {
    return new MobileleSecurityExpressionHandler(offerService);
  }
}

```

И сега следва сладката част, контролера :-)

```
  @PreAuthorize("isOwner(#uuid)") //<--- Oh, yeah :-)
  @DeleteMapping("/offers/{id}")
  public String deleteOffer(
      @PathVariable("id") UUID uuid) {
    
    offerService.deleteOfferByUUID(uuid);

    return "redirect:/offers/all";
  }
```

:-)

**Comment by thrako** [comment]
Ооо, да! Със сигурност ще го разгледам. Само не зная дали ще е преди или след защитата на проекта, че доста изоставам. Method Security анотациите изглеждат доста удобни, но пък и доста "лепило" има зад тях. Не искам просто да препиша без да разбирам кое какво прави, а отсега си личи, че усвояването на "лепило"-то може да отнеме доста време.

Ако правилно разбирам генералната идея, по този начин въвеждаме custom Filter, който Spring Security използва още преди DispatcherServlet-а, за да определи дали да предостави достъп до анотирания метод в контролера и съответно, ако откаже достъп, това се случва на много ранен етап, което е много добре от гл.т. на оптимизация.

Не разбирам обаче как се оправяме с frontend-а? С Thymeleaf как да определя дали да визуализирам delete бутон или не?

EDIT: Мисля, че открих как в Thymeleaf да проверявам дали конкретният потребител има право да трие (или за каквото там се отнася) : 
```
<div sec:authorize-url="POST /admin">
  This will only be displayed if authenticated user can call the "/admin" URL
  using the POST HTTP method.
</div>
```
Моля да потвърдиш, че това е начина?

**Comment by luchob** [comment]
Ups, объркал съм го с с wishlist този въпрос и затова стои неотговорен :-)

Да, и това е начин и го пише в документацията -> https://github.com/thymeleaf/thymeleaf-extras-springsecurity

**Comment by luchob** [comment]
Това няма да стане толкоз мазничко в новия спринг. Описал съм алтернативно решение в #95. За съжаление е един урок, че трябва да се внимава много ако се овъррайдва неабстрактен клас. Някой ден ще гледам да драсна как сме го оправили, защото вдъхновението е черпено от един наш сървис дето трябва да се мигрира на буут 3 от 2.7.10... :|

**Comment by luchob** [comment]
В допълнение развитието в 95 стана абсолютно брутално, хвърли едно око :-)

**Comment by thrako** [comment]
Ще, ще! Аз съм абониран и чета, че има развитие по въпроса, ама много нахални клиенти :), не ме оставят да програмирам. Надявам се идните дни да си открадна малко време. Благодаря, че си се сетил да напомниш!
