### ISSUE TITLE
Как успяваш да качиш различни проекти в едно и също репо?

### ISSUE THREAD

**Issue by borisboev79** [luchob/softuni-feb2023#6]
Здрасти, Лъчо, виждам, че качваш различните проекти, с които се упражняваме, в едно репо в github, които си работят, нищо че са независими и са в едно репо. Как се прави това през IDE-то? Убих се да търся и да чета

**Comment by luchob** [comment]
Здрасти!

Ами... не съм правил нищо специално :-) Това което направих всъщност може да го опиша така:

1. Направих си празно репо
2. Клонирах си го
3. Всеки нов проект който правя с Spring initializer го слагам в root директорията на това репо и го пушвам.
4. IntelliJ се оправя доста добре. Просто като отварям проекта посочвам поддиректория. Например:

```
ROOT-REPO-FOLDER
   |
   |-----> Project1
   |-----> Project2
   |-----> Project3
  ....
```

```
File -> Open -> Project3
```

"Дясно копче" + commit :-)

Поздрави,
Л.
