### ISSUE TITLE
security problem

### ISSUE THREAD

**Issue by BibiNikolova** [luchob/softuni-feb2023#62]
Здравей, Лъчо

моля за малко помощ - не успявам да си стартирам проекта, т.к имам някакъв секюрити проблем, който не зная как да реша и не мога да си работя. Изпращам screenshot на екрана си и линк към проекта. Помолих познат да опита да го отвори и той успя, но пък стилизацията на index, login...не му зареди...
![security problem](https://user-images.githubusercontent.com/67826967/226210716-72fc90e0-53ac-469d-bb12-94c7cf019c1e.png)
[https://github.com/BibiNikolova/MyIns.git](url)

Благодаря ти!

**Comment by luchob** [comment]
Здравей!

Няколко неща може да се поправят като първа стъпка към нормализиране :-) 

1. Не използвай депендънси с версия в pom.xml към секюрити:

```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
            <version>3.0.4</version>  <-- проблем
        </dependency>
```
Причината е, че спринг управлява тези версии и като сложиш твърда такава може да се получат несъответствия между отделните библиотеки и оттам всякакви трудни за разбиране проблеми.

2. Връзките към ресурсите не са:

```
<script src="/static/js/home/OtAutoBlock.js"></script>
``` 
По скоро са:

```
<script src="/js/home/OtAutoBlock.js"></script>
```

Затова не зарежда стилизацията.

3. Същото важи за темплейтите:

Не е ок:
```
<footer th:replace="~{/templates/fragments/footer}"></footer>
```

Ok:

```
<footer th:replace="~{/fragments/footer}"></footer>
```

4. Секюрити конфигурацията има проблеми:

```
 .requestMatchers(PathRequest.toStaticResources().atCommonLocations()).permitAll()
                // the URL-s below are available for all users - logged in and anonymous
                .requestMatchers("/**", "/users/login", "/users/login/register", "/users/login-error").permitAll()
```

Това `/**` позволява достъп до всичко.
Това `PathRequest.toStaticResources().atCommonLocations()` позволява достъп до статични ресурси, които спринт счита за намиращи се на "стандартно" място, а именно `js`, `css`, `images`. При теб са други. 

Когато се оправят тези неща, ще има стъпка напред :-)

<img width="1160" alt="Screenshot 2023-03-20 at 8 05 09" src="https://user-images.githubusercontent.com/10339738/226260992-50a5ef5d-daac-4314-9518-b50004aab2fa.png">

Поздрави,
Л.

**Comment by BibiNikolova** [comment]
Здравей, Лъчо,

пооправих бъркотиите, но за жалост проблемът със секюрити-то остава и не мога да достъпя приложението:(
Помагай!
![security problem](https://user-images.githubusercontent.com/67826967/226303263-ca9ab4ef-b67d-4f57-a146-468a0b139cf6.png)
Благодаря ти!

**Comment by luchob** [comment]
Здравей!

Наличието на тази страница означава, че не ти вижда секюрити конфигурацията. Тъй като при мен работи когато го сваля на чисто, предполагам че става въпрос за този проблем - https://github.com/luchob/softuni-feb2023/issues/19

Поздрави,
Л.

**Comment by BibiNikolova** [comment]
Ам да! От спейса беше! Благодаряяяя!!!
