### ISSUE TITLE
Не разбирам защо не виждам валидационните грешки тук

### ISSUE THREAD

**Issue by borisboev79** [luchob/softuni-feb2023#63]
Привет, Лъчо,

отдавна не съм те тормозил :) 

Опитвам се да си довърша проекта като му добавя и функицоналност за редактиране на вече съществуващи юзъри и като цяло всичко си работи, макар и да съм убеден, че не е в най-оптимизирания вариант, но проблемът е, че по никакъв не мога да изкарам грешките при валидация, заложени в UserModificationDto. В UserController, в PostMapping ендпойнта имам BindingResult и приложението правилно влиза вътре, но не ми изкарва съобщенията и не знам защо. 
Предварително ти благодаря за отделеното време. Ето ми и репо-то:

https://github.com/borisboev79/CGM-Project.git

ПП: Бонус въпрос, ако остане време на лекцията днес или в сряда - едно от допълнителните изисквания за евентуалната поправка на защитата на проекта е функционалността за промяна на потребителското име. Аз съм го имплементирал по един ужасно ламерски начин, та молбата ми е ако знаеш как се прави подобна валидация, да споделиш. Проблемът е, че ако потребителят има възможност да си промени потребителското име, но не го направи, валидацията за съществуващ потребител ще се включи. Но това е само бонус въпрос, ако остане време. По-важният ми е защо не ми излизат съобщенията за грешки.

**Comment by luchob** [comment]
Привет!

Допускам, че проблемът е простичък, а именно че байндинг резултата се каза `userModificationDto`:

```
if (bindingResult.hasErrors()) {
            redirectAttributes
                    .addFlashAttribute("userModificationDto", userModificationDto)
                    .addFlashAttribute("org.springframework.validation.BindingResult.userModificationDto", bindingResult);

            String redirectString = String.format("redirect:/users/modify/%s", userId);

            return redirectString;
        }

```

а в темплейта е 

```
th:object="${user}"
```

Мисля, че трябва да са еднакви.

Поздрави,
Л.

**Comment by borisboev79** [comment]
Мерси, изравних ги, но нищо. Някакви други идеи имаш ли? :)

**Comment by luchob** [comment]
push-на ли? :-)

**Comment by borisboev79** [comment]
А, да :)

**Comment by luchob** [comment]
Еее... :-) Това е... малко по интересен случай. Тук имаш ъпдейт на съществуващ обект и затова не работи, ти преинициалицираш модела след редирект. Пробвай следното нещо. Направи 3 ендпойнта:

GET - който да попълва модела и да показва темплейта, както е до сега
GET - на който да отива редиректа след ъпдейт, с грешките
POST - ъпдейта, както е сега.

Ето един пример от миналата година, като го правихме - https://github.com/luchob/softuni-may2022/blob/main/mobilele/src/main/java/bg/softuni/mobilele/web/OfferController.java#L103

**Comment by borisboev79** [comment]
Нещо не го правя явно както трябва, сякаш не можах да се ориентирам и от репото, което ми прати.
Този вторият Get, междинният, към който пренасочвам при грешки в bindingResult, ако не е същият като първият, липсват полета. Какво трябва да съдържа?

**Comment by luchob** [comment]
Здравей!

"Междинният" GET ще получава невалидния резултат заедно с грешките. Той ще е един вид празен. Точно както е при регистрацията. Имаш един празен гет който показва празна форма, но показва и грешките нали? Е, пак като регистрацията става но с още един get който дава пълен модел без грешки към темплейта.

**Comment by borisboev79** [comment]
Добро утро, Лъчо,

Направих го така, както мислех, че трябва по последните ти насоки и пак не работи. Би би погледнал в репото? Къмитнах с последните промени. Мерси
