### ISSUE TITLE
Проблем със api

### ISSUE THREAD

**Issue by evgeniya-n-s** [luchob/softuni-feb2023#64]
Здравей, Лъчо,

От известно време не успявам да си намеря грешката, защото след зареждане на определена страница, тя се зарежда само в JSON формат.
може ли да погледнеш проекта ми: https://github.com/evgeniya-stambolova/MyProject
става въпрос за следния адрес на страницата при админ логнат потребител: http://localhost:8080/api/books

благодаря!

**Comment by luchob** [comment]
Здравей!

`BookController`-a е `RestController`. По подразбиране отговорите, които тези контролери връщат са във формат `application/json` и затова ги виждаш така и в браузъра.
```
@RestController
public class BookController {

    @GetMapping("/api/books")
    public ResponseEntity<List<BookDTO>> getAllBook() {
        return ResponseEntity.
                ok(bookService.getAllBooks());
    }

}
```

Нормалния контролер се анотира с `Controller` и би могъл да връща името на съответния thymeleaf темплейт (например, като стринг).

Поздрави,
Л.

**Comment by evgeniya-n-s** [comment]
малко съм объркана. в book-rest-server показахте, че се анотира с RestCotroller, на workshopa-a също така се показа. Освен това като променя анотацията да е Controller нищо не се променя като изглед в браузъра.

**Comment by thrako** [comment]
Здравейте колега,

> малко съм объркана. в book-rest-server показахте, че се анотира с RestCotroller, на workshopa-a също така се показа. Освен това като променя анотацията да е Controller нищо не се променя като изглед в браузъра.

REST API по дефиниция комуникира през json (> 99% от случаите) или xml. Ето [тук](https://www.seobility.net/en/wiki/REST_API) може да видите кратка дефиниция и обобщена информация. 

Съответно при използване на `@RestController` анотацията или съдържащата се в нея `@ResponseBody`, Spring връща json. Нямам достъп до проекта Ви, но ако искате да върнете html трябва да имате такъв template и да върнете String с името на файла (другият начин е да върнете ModelAndView, както правихме в първата част на курса, но със String е най-лесно), например, ако страницата Ви се казва "register.html", в контролера връщате "register" и готово. Ако "register.html" е в папка напр. "views", то трябва да върнете "views/register".

В book-**rest**-server, както е видно и от името на проекта се предполага методите да са анотирани с `@RestController` и да връщат json, именно това беше и целта на демото.

Поздрави,
Траян

**Comment by evgeniya-n-s** [comment]
Разбрах!
Много благодаря за разясненията.

Поздрави,

**Comment by evgeniya-n-s** [comment]
Здравейте,

дали ще може пак да ми помогнете. Отново става въпрос за api-то
Опитвам се при логнат админ на страница admin2 след като кликна и заредя всички категории от книги при избор на съответна категория да заредя всички книги които имам за тази категория.
Най-вероятно имам някакъв проблем при js, но не успявам да го открия.
Благодаря предварително за оказаното съдействие.
Поздрави,

**Comment by luchob** [comment]
Здравей!

Проблемът е видим на скрийншота:

<img width="783" alt="Screenshot 2023-03-26 at 9 40 35" src="https://user-images.githubusercontent.com/10339738/227759779-399c4506-f478-4831-933b-9e6ce3ddf711.png">

Имаш грешка 403. Защото заявката е POST. Не виждам причина заявката да е POST а не GET.

Следващ hint е, че грешка 403 ще получиш и при POST заявка ако правиш такава, ако не е включен CSRF token. [Тук](https://github.com/luchob/pathfinder/blob/9dc5ae639b7d674ab43048ec7b8d28779e561e36/src/main/resources/static/js/comments.js#L3) има и намек как да го вземеш.

При GET заявки CSRF token не е необходим, вижда се при феча ти, който работи.

Поздрави,
Л.

**Comment by evgeniya-n-s** [comment]
Много благодаря!
Промених заявката и сега се появява таблица, но не я пълни с данни от базата....
Опитах се сама да разреша проблема, но не успявам...

Поздрави,

**Comment by luchob** [comment]
Здравей!

Доколкото разбирам, когато натиснеш `Load all fiction books` трябва да се извика това АПИ:

```
http://localhost:8080/api/books/fiction
``` 

```
function reloadFictionBooks() {

    let fictionBooksBtn = document.getElementById("books-container")
    fictionBooksBtn.innerHTML = ''

    fetch(`http://localhost:8080/api/books/fiction`).
    then(response => response.json()).
    then(json => json.forEach(fiction => {
        let buttons = document.createElement('button')
        let genreCols = document.createElement('button')
        genreCols.textContent = fiction.genre
        tempConstant = genreCols.dataset.id = fiction.id
        buttons.appendChild(genreCols)
        fictionBooksBtn.appendChild(buttons)
        genreCols.addEventListener('click', reloadFictionGenreBooks)

    }))
}
```

С него попълваш жанровете.  Ето как изглежда отговорът от сървъра:

``` 
[
   {
     ...
   },
   {
     ...
   },
   {
      "id":9,
      "genre":"FANTASY",
      "bookDTO":[
         {
            "id":2,
            "title":"Fairy Tale",
            "price":37.99,
            "author":"Steven King",
            "shortDescription":"Legendary storyteller Stephen King goes deep into the well of his imagination in this spellbinding novel about a seventeen-year-old boy who inherits the keys to a parallel world where good and evil are at war, and the stakes could not be higher—for their world or ours.",
            "cover":"HARD",
            "year":2022,
            "category":"FICTION",
            "pages":656,
            "active":true
         },
         {
            "id":1,
            "title":"Fairy Tale",
            "price":27.99,
            "author":"Steven King",
            "shortDescription":"Legendary storyteller Stephen King goes deep into the well of his imagination in this spellbinding novel about a seventeen-year-old boy who inherits the keys to a parallel world where good and evil are at war, and the stakes could not be higher—for their world or ours.",
            "cover":"SOFT",
            "year":2022,
            "category":"FICTION",
            "pages":656,
            "active":true
         },
         {
            "id":3,
            "title":"The green mile",
            "price":17.99,
            "author":"Steven King",
            "shortDescription":"Един от най-напрегнатите, драматични, но и вдъхновяващи романи на Стивън Кинг, провокиращ читателя с мрачни надежди, ужаси и чудеса...",
            "cover":"SOFT",
            "year":2006,
            "category":"FICTION",
            "pages":400,
            "active":true
         }
      ]
   }
]
```

Дали трябва да идват и книгите вътре и как трябва да се казва самия ендпойнт - не знам :-) 

След това, доколкото разбирам идеята ти е като кликнеш на жанр е да се попълни таблицата отдолу с книгите от този жанр. Е, в `reloadFictionGenreBooks` ти извикваш същия ендпойнт и итерираш по същия масив.

По-скоро очаквах нещо от сорта на два ендпойнта, напр:

```
http://localhost:8080/api/books/fiction/genres
```

Който да връща нещо като подобен масив:

```
[
   {
      "id":9,
      "genre":"FANTASY"
   },
   {
      "id":10,
      "genre":"..."
   }
]
```

С него попълваш жанровете. Като кликнеш някой се вика такъв ендпойнт:

```
http://localhost:8080/api/books/fiction/genres/<genre-id>/books
```

Който връща нещо като:

```
[
         {
            "id":2,
            "title":"Fairy Tale",
            "price":37.99,
            "author":"Steven King",
            "shortDescription":"Legendary storyteller Stephen King goes deep into the well of his imagination in this spellbinding novel about a seventeen-year-old boy who inherits the keys to a parallel world where good and evil are at war, and the stakes could not be higher—for their world or ours.",
            "cover":"HARD",
            "year":2022,
            "category":"FICTION",
            "pages":656,
            "active":true
         },
         {
            "id":1,
            "title":"Fairy Tale",
            "price":27.99,
            "author":"Steven King",
            "shortDescription":"Legendary storyteller Stephen King goes deep into the well of his imagination in this spellbinding novel about a seventeen-year-old boy who inherits the keys to a parallel world where good and evil are at war, and the stakes could not be higher—for their world or ours.",
            "cover":"SOFT",
            "year":2022,
            "category":"FICTION",
            "pages":656,
            "active":true
         },
         {
            "id":3,
            "title":"The green mile",
            "price":17.99,
            "author":"Steven King",
            "shortDescription":"Един от най-напрегнатите, драматични, но и вдъхновяващи романи на Стивън Кинг, провокиращ читателя с мрачни надежди, ужаси и чудеса...",
            "cover":"SOFT",
            "year":2006,
            "category":"FICTION",
            "pages":400,
            "active":true
         }
      ]
```

И тук итерираш книгите. `genre-id` се попълва динамично, да речем с някакъв data-attribute както правихме на books demo-то.

Поздрави,
Л.

**Comment by evgeniya-n-s** [comment]
След 1200 опита успях да го направя.
Много благодаря за насоките/примерите и най-вече търпението.

Поздрави,
