### ISSUE TITLE
Проблемът с валидацията продължава :(

### ISSUE THREAD

**Issue by borisboev79** [luchob/softuni-feb2023#66]
Добро утро, Лъчо,

Извинявай, че отварям ново issue, но старото не ми даде да го re-open.

Направих го така, както мислех, че трябва по последните ти насоки и пак не работи. Би би погледнал в репото? Къмитнах с последните промени.

https://github.com/borisboev79/CGM-Project.git

Не искам да те тормозя с нещо толкова дребно и накрая ще го оставя без валидационните грешки, ако трябва, но по никакъв начин не намерих решение в гугъл. Пак ти благодаря за времето

**Comment by luchob** [comment]
Здравей! 

Няма проблеми да отваряш issues. Направил си почти това, което ти казах, но не съвсем :-) Нека да попреработим error endpoint-a **приблизително** така:

```
    @GetMapping("/errors/{id}")
    public String getErrorsModifying(@PathVariable Long id,
                                        @AuthenticationPrincipal CurrentUser currentUser,
                                        Model model){

        model.addAttribute("firstName", currentUser.getFirstName());

        return "users-modify";
    }
```

Забележи, няма `redirect`, това е много важно. Няма и параметър, защото е във флаш атрибут. Ще дойде и модела попълнен от формата и грешките. И... 

<img width="768" alt="Screenshot 2023-03-21 at 13 02 32" src="https://user-images.githubusercontent.com/10339738/226588546-9cd92eee-b179-4fc0-ac1d-67c7bcaedcc3.png">

Дано е полезно.

Поздрави,
Л.
