### ISSUE TITLE
Въпрос относно личния проект към софтуни

### ISSUE THREAD

**Issue by yanamet** [luchob/softuni-feb2023#67]
Здравей, Лъчо. Откакто добавих спринг към проекта си доста ме мъчи. Главният проблем, от който мисля, че идва всичко, е че исках да променям някои праймъри цветове и компоненти в буустрап и затова го включих целия с папки node_modules, assets, scss. Формите ми работят, тоест мога да правя нова регистрация и също така мога да се логвам, но проблемът е, че когато не съм логната спринг секюрити сякаш забранява достъпа до буустрап и ми се чупи целия дизайн, а също така друго, което забелязах е, че не работи и таймлийф, тоест например грешките, които трябва да дава, само когато полето е празно например, винаги стоят, а в логин въобще не се показва съобщението, което вклюва th:if="${badCredentials}", въпреки че /login-error е @PostMapping.
Наистина бих била много благодарна, ако ме насочиш какво да правя, защото вече пробвах всичко. Много благодаря предварително. Пействам малко код, за да покажа какво правя. Поставям и линк, в който съм добавила снимки как изглеждат login и register.

https://docs.google.com/document/d/1BmAOdAdZTxqbBPZ_O4GNlaxnJGpkYOY0mGRop89m794/edit?fbclid=IwAR1ovKnWBXb3E65S65IWc0AIsqJhO4mO6zng4ylSbv-0uhR19ctdoTDA7cg

    @Bean
    public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
        http
                .authorizeHttpRequests()
                .requestMatchers(PathRequest.toStaticResources().atCommonLocations()).permitAll()

                    .requestMatchers("/", "/login", "/register").permitAll()
                    .requestMatchers("/pages/admin").hasRole(RoleEnum.ADMIN.name())
                .requestMatchers("/static/scss/**", "/static/**", ["/images/**").permitAll()](url)    //тук се опитвам да дам изчирно достъп до статичните файлове
                .anyRequest().authenticated()
                    .and()
                    .formLogin()
                    .loginPage("/login")
                    .usernameParameter(UsernamePasswordAuthenticationFilter.SPRING_SECURITY_FORM_USERNAME_KEY)
                    .passwordParameter(UsernamePasswordAuthenticationFilter.SPRING_SECURITY_FORM_PASSWORD_KEY)
                .defaultSuccessUrl("/home", true)
                .failureForwardUrl("/login-error")
                     .and()
                     .logout()
                     .logoutUrl("/logout")
                     .logoutSuccessUrl("/")
                     .deleteCookies("JSESSIONID")
                     .clearAuthentication(true);

        return http.build();

    }

**Comment by yanamet** [comment]
https://github.com/yanamet/HotelAntique - линк към проекта

**Comment by luchob** [comment]
Здравей!

По първия проблем веднага виждам малки грешчици. 

1. Това нещо:

```
.requestMatchers(PathRequest.toStaticResources().atCommonLocations()).permitAll()
```
дава достъп до статични ресурси, които спринг счита че са на "нормални" локации.
От техния код това са:

```
  CSS(new String[]{"/css/**"}),
  JAVA_SCRIPT(new String[]{"/js/**"}),
  IMAGES(new String[]{"/images/**"}),
  WEB_JARS(new String[]{"/webjars/**"}),
  FAVICON(new String[]{"/favicon.*", "/*/icon-*"});
```
Тук няма `scss` и т.н.

2. URL-то на което тези неща са достъпни като си логната не е `/static/scss/**`, 
а е `/scss/**`. Това `static` не участва в URL-та.

**Comment by luchob** [comment]
Относно валидацията, оправих горните неща и мисля, че всичко е наред. Закачам снимки на:

1. Начално състояние 
2. Празно име и събмит
3. Правилно име и събмит

<img width="494" alt="Screenshot 2023-03-21 at 16 48 40" src="https://user-images.githubusercontent.com/10339738/226644262-2d8e05da-4fd5-4c2b-86ed-b30a57d2877f.png">
<img width="560" alt="Screenshot 2023-03-21 at 16 48 49" src="https://user-images.githubusercontent.com/10339738/226644283-3b7d5050-5601-46ee-8c2d-7dc6a07558be.png">
<img width="502" alt="Screenshot 2023-03-21 at 16 48 58" src="https://user-images.githubusercontent.com/10339738/226644310-3c18b7e9-731a-4b3d-a27f-eda29fff1169.png">

**Comment by luchob** [comment]
Относно логин страницата. Не виждам никаква функционалност свързана с thymelef вътре. Например:

```
<div class="form-group">
                    <div class="label-holder text-white ">
                        <label for="username" class="h3 mb-2">Username</label>
                    </div>
                    <input
                            type="text"
                            class="form-control"


                            id="username"
                            name="username"/>
                </div>
                <small class="bg-danger text-light rounded">Username must be between 3 and 20 symbols</small>

```

Това... винаги показва грешка. Като рефърънс може да посоча нашето security-demo. Напомням, че там няма DTO, няма логин ендпойнт, всичко се движи от спринг секюрити.

Поздрави,
Л.
