### ISSUE TITLE
проблем с Rest API

### ISSUE THREAD

**Issue by ViliIlieva** [luchob/softuni-feb2023#68]
https://github.com/ViliIlieva/MyKnitShop
Да помоля за помощ с Rest API, опитвам се да го направя и гледам подробно всичко в Workshop-а с Крис, но явно нещо пропускам дава ми грешка    getOutputStream() has already been called for this response

в HomeControler съм махнала модел атрибута от където преди зареждах съобщенията, в секюритито добавих разрешението /api/** да е разрешено за всички, в html добавих пътя към js/ папката и направих restControler с анотация, поставих и id-то на класа в който съм поставила линка, но явно нещо оплесквам някъде

**Comment by luchob** [comment]
Здравей!

След основен тест не получавам такава грешка, така че вероятно ми трябват повече детайли. Най-малкото пълен стек трейс.

<img width="574" alt="Screenshot 2023-03-21 at 17 21 38" src="https://user-images.githubusercontent.com/10339738/226654383-4de27ac5-f03c-4d95-b5de-4180f3ed9aff.png">


Поздрави,
Л.

**Comment by ViliIlieva** [comment]
Бутнах секюрити файла, опростих резултата който се получава от MessageView и нещата май се получиха

**Comment by ViliIlieva** [comment]
а в Inspect ми дава че уж зарежда js файла 

![image](https://user-images.githubusercontent.com/100292906/226701458-1064dfd6-25ce-4509-8a83-134738517869.png)
