### ISSUE TITLE
Проблем със sec:authorize

### ISSUE THREAD

**Issue by NIvanov17** [luchob/softuni-feb2023#69]
Здравей, Лъчо!
Използвам sec:authorize, за да скрия бутоните от навигацията, които не трябва да се виждат, ако не си логнат, ако не си админ и тн. Когато стартирам проекта няма промяна от default-та навигация. Извинявам се за безпокойствието и благодаря предварително.
`<!DOCTYPE html>
<html lang="en" xmlns:th="http://www.thymeleaf.org"
      xmlns:sec="http://www.thymeleaf.org/extras/spring-security">

<head>

    <th:block th:fragment="head">
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="_csrf" th:content="${_csrf.token}"/>
        <meta name="_csrf_header" th:content="${_csrf.headerName}"/>
        <title>Bri4ka</title>
        <link rel="icon" type="image/x-icon" th:href="@{/img/favicon.ico}">
        <link rel="stylesheet" th:href="@{/css/bootstrap.min.css}">
        <link rel="stylesheet" th:href="@{/css/reset-css.css}">
        <link rel="stylesheet" type="text/css" th:href="@{/css/index.css}"/>
    </th:block>
</head>

<body>

<th:block th:fragment="nav">
    <div class="container-fluid banner">
        <div class="row">
            <div class="col-md-12">
                <nav class="navbar navbar-md">
                    <a class="navbar-brand" href="/home">Bri4ka</a>

                    <ul class="nav">

                        <li class="nav-item" sec:authorize="isAuthenticated()">
                            <a class="nav-link" href="/home">HOME</a>
                        </li>

                        <li class="nav-item" sec:authorize="isAuthenticated()">
                            <a class="nav-link" href="/add-offer">ADD OFFER</a>
                        </li>

                        <li class="nav-item" sec:authorize="isAuthenticated()">
                            <a class="nav-link" href="/all-offers">OFEERS</a>
                        </li>

                        <li class="nav-item" sec:authorize="!isAuthenticated()">
                            <a class="nav-link" href="/about-us">ABOUT US</a>
                        </li>

                        <li class="nav-item" sec:authorize="isAuthenticated()">
                            <a class="nav-link" href="/liked-offers">LIKED OFFERS</a>
                        </li>

                        <li class="nav-item" sec:authorize="hasRole('ADMIN')">
                            <a class="nav-link" href="/admin">ADMIN</a>
                        </li>

                        <li class="nav-item" sec:authorize="!isAuthenticated()">
                            <a class="nav-link" href="/login">LOG IN</a>
                        </li>
                        <li class="nav-item" sec:authorize="!isAuthenticated()">
                            <a class="nav-link" href="/register">REGISTER</a>
                        </li>

                        <li class="nav-item" sec:authorize="isAuthenticated()">
                            <form th:method="POST" th:action="@{/logout}">
                                <input class="btn btn-light " type="submit" value="Logout">
                            </form>
                        </li>
                    </ul>
                </nav>
            </div>
</th:block>

<th:block th:fragment="footer">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
    <footer class="footer bg-transparent  py-2">
        <div class="container-fluid text-center">
            <div class="footer-background h5 text-dark fixed-bottom">
                &copy; SoftUni Student 2022. All rights reserved.
            </div>
        </div>
    </footer>
</th:block>

</body>
</html>`

`<header th:replace="fragments/commons::nav"></header>`

**Comment by luchob** [comment]
Здравей!

Няма линк към проекта ти, но допускам е [това](https://github.com/NIvanov17/MyFirstProject). В депендънситата има нередности. Не слагай версии на спринг стартерите, спринг се грижи за това и ако ти им слагаш вероятността нещо просто да не работи е голяма. 

```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
            <version>3.0.4</version> <--- NOOOO
        </dependency>
```

`sec:authorize` оживява благодарение на `thymeleaf-extras-springsecurity`, който си сложил също с версия. Само че има и допълнителен проблем.

`thymeleaf-extras-springsecurity5` работи само със Spring Boot 2.x. С Spring 3.x не е съвместим и няма да работи. Там трябва да използваш `thymeleaf-extras-springsecurity6`, нещо такова:

```
        <dependency>
            <groupId>org.thymeleaf.extras</groupId>
            <artifactId>thymeleaf-extras-springsecurity6</artifactId>
        </dependency>
```

Като оправиш проекта ако има драми пиши пак.

Поздрави,
Л.

**Comment by NIvanov17** [comment]
Много благодаря!
