### ISSUE TITLE
Въпрос за индивидуалните проекти

### ISSUE THREAD

**Issue by PlamenPeev** [luchob/softuni-feb2023#7]
Здравей Лъчо!
Имам идея за моя проект, но не знам дали е ок за самата защита, възможно ли е да те питам за насоки, когато имаш време. Тук  може ли да разискваме теми свързани с проектите или към кого да се обърна за насоки?
Благодаря предварително,
Поздрави и успех с нас :) !

**Comment by luchob** [comment]
Здравей!

За това можеш да попиташ Softuni и съответните ментори които имате там. Тук смятам че е по-скоро подходящо за въпроси структурирани по следния начин :-)

**Проблем:** 20-30 думи
**Проект:** github link
**Ексепшън:** optional
**Стъпки за репродуциране:** ...

Пзодрави!
