### ISSUE TITLE
environment variables question 

### ISSUE THREAD

**Issue by toshko89** [luchob/softuni-feb2023#70]
Добър ден ,

На скоро ми се наложи да сменя изцяло машината и предполагах, че ще трябва да си попълня наново environment variables-илите когато клонирам репото. Само че всичко работеше и бяха попълнени след клониране. Имам .gitignor, не ги намирам в репото и не разбирам как работи на новият компютър? Къде ги запазва ? 

Това е линк към проекта https://github.com/toshko89/food-corner-v2-java 
Ще съм много благодарен, ако може да го погледнете какво съм объркал 

Поздрави и лек ден  

PS.

Имам още едно питане, опитвам се да хостна Rest-a в Heroku, но поради някаква причина не недига базата правилно, всичко минава уж добре, но не прави таблици orders and comments. Всики други ги създава вярно. Въпроса ми е по принип мога ли да разчитам на JPA/Hibernate да ги създаде или трябва да си направя schema.sql файл ?

**Comment by luchob** [comment]
Добър да бъде!

По принцип, ако си ги настройваш от IntelliJ специфично за проект би трябвало да ги пази в .idea папката. Но как са попаднали отново на твоя нов компютър нямам представа. Единственото, което знам, че не е от репозиторито ти.

Поздрави,
Л.

**Comment by thrako** [comment]
Здравей и от мен,

И аз рових в repository-то и не ги открих никъде. [Very Long Shot] Да не би IntelliJ да пазят remotely някакви данни, свързани с настройката на IDE-то ти и след това като са засекли инсталация със същите credentials, да са импортнали настройките на новата машина?

Продължавам да следя с интерес. Моля да пишеш тук, ако разкриеш как се е случило?

Поздрави,
Траян
