### ISSUE TITLE
Последен проблем с извеждането на validation errors :)

### ISSUE THREAD

**Issue by borisboev79** [luchob/softuni-feb2023#71]
Привет, 

мисля, че благодарение на този проблем и твоите търпеливи обяснения, най-после разбрах как функционира Binding Results.

Почти всичко работи вече, с изключение на едно, което опитвах два-три часа да оправя сам, но пак прибягвам до теб, обещавам, за последно с този тъп проблем
![Problem](https://user-images.githubusercontent.com/83350776/226860271-a2df0f1f-9bb6-435d-bc67-54ee1355d443.png)

Всичко си зарежда както трябва, но ако махна отметката от всички роли, и опитам да събмитна, ми мята грешка 500, ВЪПРЕКИ че самият BindingResult си хваща грешката. Виж:

Field error in object 'userModificationDto' on field 'roles': rejected value [null]; codes [NotNull.userModificationDto.roles,NotNull.roles,NotNull.java.util.List,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [userModificationDto.roles,roles]; arguments []; default message [roles]]; default message [There should be at least one role selected!]

Обаче следва:

org.thymeleaf.exceptions.TemplateInputException: An error happened during template parsing (template: "class path resource [templates/users-modify.html]")
Caused by: org.attoparser.ParseException: Exception evaluating SpringEL expression: "roles.contains('USER')" (template: "users-modify" - line 80, col 32)
Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1011E: Method call: Attempted to call method contains(java.lang.String) on null context object

При формата за регистрация няма проблем - ако махна отметките, си ми се показва съобщението, че трябва да е избрана поне една роля.

Какво дребно ми убягва пак? Явно нещо важно не се пренася с bindingResults или?

https://github.com/borisboev79/CGM-Project.git

Благодаря!

**Comment by luchob** [comment]
Здрасти! 

Много зор тези дни, но не съм те забравил. Докато те помня и нищо не върша :-) Погледни това нещо, може би ще ти е интересно -> https://github.com/luchob/softuni-feb2023/issues/72

**Comment by luchob** [comment]
Привет! 

Въпреки, че си променил малко така... хитро дизайна :-) може да ти обясня какъв е бил проблема.

Имаш:
```
    @NotNull(message = "There should be at least one role selected!")
    private List<String> roles;
```
Като нямаш нито една роля, този лист е `null`, нали? Binding result-a го хваща и те насочва към темплейта. Там обаче има проблем:

```
th:checked="*{roles.contains('USER')}" type="radio" name="roles"
```

E да де, но roles e null. Викаш `null.contains('USER')` и thymeleaf ти казва:
``
Attempted to call method contains(java.lang.String) on null context object
```

Туй то :-)

Поздрави,
Л.

**Comment by borisboev79** [comment]
Еххх, мамка му, супер елементарно е било :) Въртях се някъде около идеята и ми бягаше.

![Screenshot 2023-03-23 195156](https://user-images.githubusercontent.com/83350776/227300523-a4703cf5-ed2d-4177-8135-9503a619a1a8.png)

Тези добавени проверчици оправиха нещата. 

Малкото ми "хитро измъкване" беше просто застраховка, в случай, че не се справя. Все пак приложението ТРЯБВА да работи :)) Сега съм доволен, защото е както беше замислено. Искрени благодарности за помощта.

По отношение на темата, която ми даде за четене - ами то е безобразно логично, само че при мен всичко си работи, не мога да ти кажа как. При изтриване на потребител, се изтриват и записите в мапинг таблицата, но нито има опити да трие ролите, нито пък има грешки.

Както и да е, ще го имам предвид. Сега продължавам с тестовете, че нещо хич не ми се получават. Осъзнах, че никак не разбирам точната функция и приложението на този ArgumentCaptor :(

Дано Кристиян в понеделник успее да направи още няколко. Иначе сега ще чета из нета да видим дали ще си помогна.

Лека вечер и пак благодаря!

Поздрави,
Боби
