### ISSUE TITLE
Проблем с тестовете

### ISSUE THREAD

**Issue by KristiyanVasilev96** [luchob/softuni-feb2023#72]
Здравей, получавам следния проблем:Caused by: org.hibernate.PersistentObjectException: detached entity passed to persist: project.laptop.model.entity.UserRoleEntity преди това работеше теста за офертите сега обаче се бъгяса нещо :D
във релацията @ManyToMany(fetch = FetchType.EAGER,cascade = CascadeType.ALL)
    private List<UserRoleEntity> userRoles=new ArrayList<>();
 пробвах със merge ,persist и т.н но не се получаваха нещата, ако имаш време да удариш един поглед.

**Comment by luchob** [comment]
Здравей!

_пробвах със merge ,persist и т.н но не се получаваха нещата_ 

Звучи ми като "пермутационно програмиране" :-)

Нека да разгледаме какво се случва в ДБ.

![user-role-many-to-many](https://user-images.githubusercontent.com/10339738/226928518-ff619294-3dbb-4e5b-991a-4e53ea430573.png)

От една страна имаш роли, например ADMIN/USER. Те са 2 и никога не се променят. Т.е. трябва да ги има там още при стартирането на сървиса. И при добавянето на нов админ пак да си стоят там и да са само 2 с вечните си id-та. От другата имаш юзър и там за всеки юзър има ред. Свързващата таблица се ползва да асайне роля (те са само 2!) на юзър. Например:

```
Roles
1 -> ADMIN
2 -> USER
```

```
Users
100 -> Admin adminov
200 -> User userov
``` 

```
Relation User ->Role
100 -> 1
100 -> 2
200 -> 1
```

Какво означава `CascadeType.ALL`? Означава, че ако изтриеш юзър X става гафче - хибернейт ще се опита да изтрие и ролите. А какво става с юзър Y тогава?

Затова удачен тип на релацията е само MERGE. Ето какво става като теста ти създава админ юзър:

```
select count(*) from user_roles u1_0                          // <-- Дали да инициализирам ролите? 

select u1_0.id,u1_0.user_role from user_roles u1_0  // Дай ми всички роли

insert into users (email, first_name, image_url, last_name, password) values (?, ?, ?, ?, ?) // вкарай юзъра

insert into users_user_roles (user_entity_id, user_roles_id) values (?, ?) // оправи релацията - добави АДМИН ролята
insert into users_user_roles (user_entity_id, user_roles_id) values (?, ?) // оправи релацията - добави USER ролята
```

Обаче, ако смениш на MERGE ще забележиш веднага проблем - ще трябва да си оправиш регистрацията да работи по същия начин, както и тестовете. Хубво че имаш тест, който да гръмне :-) Лошото е, че все още не ползваш in-memory-db.

Поздрави,
Л.
