### ISSUE TITLE
Проблем при тестчетата

### ISSUE THREAD

**Issue by IvailoB** [luchob/softuni-feb2023#74]
------when(userService.getUserByUsername("admin"))
                .thenReturn(testUser);

не би ли трябвало този код да казва когато се извика този метод да ми върнеш този резултат без да се проверява какво прави метода.... което прави тази грешка неразбираема за мен :D 

Cannot invoke "com.example.carweb.repo.UserRepository.findByUsername(String)" because "this.userRepository" is null

Защото репозитори използвам вътре в този метод. Опитах се да сетъпна репозитори ноо бързо се отказах :D

------Също така трябва когато добавя продукт успешно би трябвало да ме върне в product/detail/{id}
а ме праща да се логвам. трябва ли и в теста да вкарам вече логнат потребител и как? :) Благодаря
 Expected :product-detail/1
Actual   :http://localhost/users/login
Moже би някъде бъркам защото когато променя така - 
                .andExpect(status().is3xxRedirection())
                .andExpect(redirectedUrl("http://localhost/users/login"));
тестът минава но coverage не се променя... а създавам нов продукт правя perform на  mockMvc... и нищо

**Comment by luchob** [comment]
А кой е проектът?

**Comment by IvailoB** [comment]
https://github.com/IvailoB/SoftUni-Java-WEB/tree/main/CarWeb/CarWeb
Като също имам затруднения с тестването в UserControllerIt при profile -> GetMapping v controlera

**Comment by luchob** [comment]
Здравей, относно неразбираемата грешка.

За да може на мястото на това репозитори да се inject-не фалшив мок:

```
  @Mock
  private UserRepository userRepository;
```

Трябва да анотираш теста така:

```
@ExtendWith(MockitoExtension.class)
public class UserDetailServiceTest
```

Иначе `userRepository` си остава null и тогава въпросната грешка: `because "this.userRepository" is null` става съвсем разбираема. Освен това, когато имаш мок, този код става странен или излишен:

```
  @Mock
  private UserService userService;

  @BeforeEach
  void setUp() {
    userService = new UserService(
        userRepository,
        roleRepository,
        passwordEncoder
    );

  }
```

Тъй като `userService` вече е мок. Добра практика е ако имаш мок обект Х да го кръстиш mockX в теста. Например:


```
  @Mock
  private UserRepository mockUserRepository;
```

**Comment by luchob** [comment]
`трябва ли и в теста да вкарам вече логнат потребител и как? :) `

Да, трябва. Един от начините е чрез анотацията `WithMockUser`. Давам пример:


```
  @Test
  @WithMockUser(
      username = "admin@example.com",
      roles = {"ADMIN", "USER"}
  )
  void testDeleteByAdmin() throws Exception {
    mockMvc.perform(delete("/offers/{id}", testOffer.getId()).
            with(csrf())
        ).
        andExpect(status().is3xxRedirection()).
        andExpect(view().name("redirect:/offers/all"));
  }
```

**Comment by luchob** [comment]
Относно следващата грешка:

```
mockMvc.perform(get("/profile"));
```

В проекта нямаш мапинг `/profile`. Имаш `/users/profile`. Оттам съвсем резонно ще ти върне 404.

Поздрави,
Л.
