### ISSUE TITLE
Проблем при login form

### ISSUE THREAD

**Issue by Alexanski13** [luchob/softuni-feb2023#75]
Привет искам да попитам, когато си правя login formata със security filter chain, при записване на username и password ми излиза в конзолата select db query, но в url само излиза login?error и не се логва, нито redirectva към index html. :(

Link to repo:

https://github.com/Alexanski13/My-Gym-Shop

**Comment by luchob** [comment]
Здравей!

Не работи нищо, защото `ApplicationUserDetailsService` не е изкаран като spring bean. Пример -> https://github.com/luchob/softuni-feb2023/blob/main/security-demo/src/main/java/bg/softuni/security/config/SecurityConfiguration.java#L64

Поздрави,
Л.

**Comment by Alexanski13** [comment]
Здравейте опитах го това вече но нз какво стана с последния commit сега го updatenah с expose като Bean но същия проблем.

**Comment by luchob** [comment]
Здравей, ъпдейтнах ти току що проекта и го пуснах отново.

<img width="1241" alt="Screenshot 2023-03-23 at 19 42 22" src="https://user-images.githubusercontent.com/10339738/227294725-b1c2f7ad-9be3-4161-86af-7610a9cb0a04.png">
<img width="1679" alt="Screenshot 2023-03-23 at 19 40 03" src="https://user-images.githubusercontent.com/10339738/227294783-587b499a-1afc-4389-9b60-c87110edf3d2.png">

Не откривам проблеми и всичко работи... :( Опитай да изчистиш сесията и да го пуснеш на чисто. Надявам се, логваш се с имейл, а не с username. В.ж. скрийншотите. Нямам идея как да ти помогна иначе.

Поздрави,
Л.

**Comment by Alexanski13** [comment]
Благодаря, от невнимание случват се такива неща. I found the error in my ways and cheers!
