### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by MihaylovaL** [luchob/softuni-feb2023#77]
Привет, Лъчо!

За съжаление имам проблем с login-а. 

Може ли да погледнеш и да ми дадеш насоки къде бъркам и какво пропускам?

Все още не съм мърджнала бранча по който работя върху register и login, защото логина не работи.

линк:  https://github.com/MihaylovaL/YarnShop.git

бранч: "adding-spring-security"

**Comment by luchob** [comment]
Здравей!

Според мен, всичко е наред с логина ти. С изключение на две наглед странични неща:

1. Нямаш favicon. Говорили сме за това защо се сдухват нещата без тази икона. Ако не си спомняш може да погледнеш https://github.com/luchob/softuni-feb2023/issues/55.  Сложи си някаква, най-лесно ще е в static папката. Това ще я разреши:

```
                requestMatchers(PathRequest.toStaticResources().atCommonLocations()).permitAll().
```

2. Имаш грешен ендпойнт в секюрити конфига:

```
                defaultSuccessUrl("/index").
```

В проекта ти няма контролер с такъв ендпойнт, въпреки че имаш index.html. Сложи си някакъв контролер друг и редиректвай натам.

Освен това, всичко е ОК с логина.

Поздрави,
Л.
