### ISSUE TITLE
Проблем при създаване на оферта

### ISSUE THREAD

**Issue by MariaBonkova** [luchob/softuni-feb2023#78]
Привет Лъчо, опитвам се да сложа оферта обаче нещо не става. Започвам обяснението от далеко. Работя по сайта например влезаш в някой каталог и там има бутон създай собствен предмет. Цъкаш и влизаш във страница където може да си дадеш заявка за предмет. В лявата част се попълва и след натискане на бутон потвърди поръчката трябва в картичката в дясно да се появи име на предмета и цена. И после като натисне направи поръчка да се запази в репото. Писах, кодих, мислих и това което виждаш сътворих в createrOfferController , MaterialServiceImpl, направих dto,view, мъчих някакви сметки /в сметката за цената не знам как да добавя количеството към цената на килограм/.  Там става и чудене като натисна първия бутон потвърди поръчка гетМапинг или постМапинг. 

ПС. На предният модул това също не би беше много ясно като логика.
Благодаря ти М.
https://github.com/MariaBonkova/3D-printing-project

**Comment by luchob** [comment]
Здравей!

Трябва да започнем от някъде... Малко ми е трудно да разбера - какво прави това?

```
createOfferService.totalProductPrice(createOfferDto().getMaterialComposition().name())
```

Аз виждам, че създава някакъв празен обект, взема null през `getMaterialComposition`и гръмва с NPE...

Поздрави,
Л.

**Comment by MariaBonkova** [comment]
Мъча се да направя калкулация на крайната цена. Тоест през  сайта юзъра си вкарва материала,  от който иска да му е продукта, задава килограми и аз накрая трябва да изкарам крайната цена за продукта.  За всеки материал имам цена на килограм-където със switch ги инициализирам в таблица materials иначе кода му е в materialServiceImpl. 
Правя някви отчаяни опити да умножа едното с другото, но интелиджей ми казва, че така не става. Реших да го закоментирам и да видя дали поне може на сайта да изкарам еденичната цена, че после да мисля крайната. 
В materialRepositry правя опит чрез куери заявка която в mysql ми връща еденичната цена на продукта по дошло от вън име, но като го шляпна в репото и светва. И може би от тук тръгва нулата. Тъпото, е че като почна да дебъгвам ми излиза съобщение, че интелиджей става критично бавен и локалхоста умира на място и нито с цъкане нито с рефреш се съживява. 
Поздрави М.

**Comment by MariaBonkova** [comment]
Друго се сетих което също най-вероятно ще го мъча и то мен. Като си задава юзъра инфото за желания предмет има и да си качи снимка на това което желае и идеята е тази снимка да я сложа в картичката в дясно на мястото на кучетата ако прави за животни респективно на другите. Но първо да оприм горния казус, пък за  това ще го поблъскам преди да викам за помощ.

**Comment by luchob** [comment]
Здравей!  

Първо, събмита на формата с поръчката трябва да е през POST а не през GET:

<img width="854" alt="Screenshot 2023-03-24 at 18 54 29" src="https://user-images.githubusercontent.com/10339738/227590687-68f59d58-3cc5-4564-82a0-cce192ea10f3.png">

Оттам трябва да имаш правилно създадено и валидирано ДТО (нещо като при регистрацията). След това трябва да се направи един сървис и да му се делегира създаването на поръчка с някакви properties. На този момент виждам едно репозитори, което му се дава едно моделче:

```
createOfferRepository.save (modelMapper.map(createOfferDto, CreateOfferEntity.class));
```

Дай като някаква първа стъпка да се случи това, после ще решаваме един по един проблемите. Днес Кристиан каза, че на workshop-a ще повтори CRUD операции на разни обекти. Наблюдавай го какво прави, имаме и регистрационна форма (create user) която работи на същия принцип както създаване на поръчка.

Поздрави,
Л.

**Comment by luchob** [comment]
_Правя някви отчаяни опити да умножа едното с другото, но интелиджей ми казва, че така не става._ 

Не става, защото не работиш с примитив (напр int) или wrapper (напр Integer) а с BigDecimal, който има метод `multiplyBy`. Например:

```
BigDecimal price = materialEntitiesByPrice.multiply(dtoQuantity);
```

**Comment by luchob** [comment]
To be continued in #82 :-)
