### ISSUE TITLE
Имам проблем със стартирането на проекта ми.

### ISSUE THREAD

**Issue by GeorgiPetrov4400** [luchob/softuni-feb2023#8]
Здравей, 
Проекта който смятам да правя е за прогнози за ФОРЕКС и се казва Trading Forecasts. Прогнозите ще бъдат за валутните двойки евро/долар, евро/паунд, злато и индексите Dax, Dow Jones и Nasdaq които са в ентити Category което от своя страна се състои от енъм. Всяка една прогноза ще бъде или дълга позиция (long) или къса позиция (short) които са също енъми. Имам и енъми за UserRole и накрая когато се опитам да стартирам проекта си ми излиза грешка "The dependencies of some of the beans in the application context form a cycle:" и че трябва да направя това "Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle between beans. As a last resort, it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true."
Четох в Baeldung, че това се получава, защото имам много навързани bean-ове и когато имаме Constructor injection, Spring се чуди при стартиране кое да инициализира първо :)  Пробвах с това "spring.main.allow-circular-references=true"  което сложих в application.properties, но проблема си оставаше и затова когато добавих @Lazy в Конструктора на ForecastServiceImpl и приложението ми тръгна :)
Вчера те питах в началото на лекцията дали това би било проблем за моето приложение и ти ми каза да напиша issue тук за да ми помогнеш :)
Благодаря ти предварително за отделеното време!

Github URL: https://github.com/GeorgiPetrov4400/Trading-Forecasts/tree/main/TradingForecasts/TradingForecasts

**Comment by luchob** [comment]
Здравей!

Това нещо няма как да работи нормално :-)

```
@Service
public class ForecastServiceImpl implements ForecastService {

    private final ForecastService forecastService;

    public ForecastServiceImpl(ForecastService forecastService) {
        this.forecastService = forecastService;
    }
}
```

Всъщност дори не разбирам каква ти е идеята тук - имаш `ForecastService`, който се нуждае от... `ForecastService`(от себе си) като депендънси. :-)

Поздрави,
Л.
