### ISSUE TITLE
redirect:/register

### ISSUE THREAD

**Issue by BibiNikolova** [luchob/softuni-feb2023#80]
Здравей, Лъчо,
не успявам да се справя със следните проблеми:
1. при регистрация на нов юзър с грешни данни, влиза в if проверката, но по някаква причина не остава на същата страница, а  зарежда login страницата
2. при регистрация с коректни данни не записва юзъра в базата
3. не мога да отварям твоите проекти с gradle, прилагам скрийн шот

<img width="960" alt="2023-03-24" src="https://user-images.githubusercontent.com/67826967/227490199-89091ea6-5f2e-420b-8700-e31200797a65.png">
[https://github.com/BibiNikolova/MyIns](url)

Благодаря ти!

**Comment by luchob** [comment]
Здравей!

Относно 1) При мен пък не отива в логин страницата, а вместо това отива на home страницата. Това е заради този редирект:
```
@PostMapping("/register")
    public String postRegister(@Valid UserRegisterFormDto userRegisterFormDto,
                               BindingResult bindingResult,
                               RedirectAttributes redirectAttributes){
        if(bindingResult.hasErrors()){
            redirectAttributes.addFlashAttribute("userRegisterFormDto", userRegisterFormDto);
            redirectAttributes.addFlashAttribute(
                    "org.springframework.validation.BindingResult.registrationDTO", bindingResult);

            return "redirect:/"; // <- Ако е грешна регистрацията, отиди на хоум страницата.
        }

...
    }
```

**Comment by luchob** [comment]
2. По-скоро го записва, но ти си мислиш, че данните са коректни а те не са. 

Имаш такава валидация:

```
    @NotBlank
    @Size(min = 9, max = 9)
    private String phone;
```

А фронтенда слага някакви дупки в 9-те цифри, можеш да ги видиш лесно в Network tab-a. Оттам валидацията не минава. Като оправиш 1) това ще стане очевидно.

**Comment by luchob** [comment]
Относно 3, допускам причината е в този ред:

https://github.com/luchob/softuni-feb2023/blob/main/mobilele/build.gradle#L8

sourceCompatibility = '17'

Може би нямаш подходящото JDK. Смени номера със своето, по желание >=17

Поздрави,
Л.
