### ISSUE TITLE
Проблеми със сърч бара

### ISSUE THREAD

**Issue by MilenaDimova** [luchob/softuni-feb2023#81]
Здравей, Лъчо! Гледам от преданата инстанция как сте направили сърча, но при мен нещо не сработва и не мога да разбера защо не ми прави филтрацията. 
В offerEntity имам четири релации с други ентитита, които от своя страна са енъми - https://github.com/MilenaDimova/real-estate-project/blob/main/src/main/java/bg/softuni/myrealestateproject/model/entity/OfferEntity.java

Направих си OfferSpecification клас - https://github.com/MilenaDimova/real-estate-project/blob/main/src/main/java/bg/softuni/myrealestateproject/repository/OfferSpecification.java , а в репозиторито екстендвам JpaSpecificationExecutor<OfferEntity>.

Имам SearchOfferBindingModel, но забеляазвам че след като мина през офър контролера и стигна до сървиса ми се връщат всички оферти без да са филтрирани.

Може ли малко насоки къде бъркам? 

Поздрави и лека вечер!

**Comment by luchob** [comment]
Здравей!

По-скоро проблемът е в мен :-) 

Насоките са тук -> https://github.com/luchob/softuni-feb2023/issues/34

Поздрави,
Л.

**Comment by MilenaDimova** [comment]
Благодаря! Всичко сработи :)
