### ISSUE TITLE
Проблем с офертите

### ISSUE THREAD

**Issue by MariaBonkova** [luchob/softuni-feb2023#82]
Привет Лъчо. Един от преподавателите беше казал напредък е когато успееш да промениш грешката. Е аз май това правя. Имам dto, creatOfferService, , repo i CreateOfferController. В контролера наших постове, гетове в изобилие. Мисля че в сървиза създавох оферта, но лошото е че не тръгва. Когато скрия Гет заявката на create-item-form/view и оставя постМапинг почва да църка org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'GET' is not supported. 
Като му го включа и него църка че getId is null. 
И друг проблем е че не мога да дебъгвам защото забива всичко.  Излиза ми съобщение че в режим дебъг става критично бавен и локалхоста умира. За това някакъв лек има ли?

**Comment by luchob** [comment]
Допускам, че ще се ускори ако отвориш менюто с брейкпойнтите и деселектираш стопа при any exception.

<img width="575" alt="Screenshot 2023-03-26 at 9 48 30" src="https://user-images.githubusercontent.com/10339738/227760139-1e85d27f-67b4-4c92-8da6-88f7a46686da.png">

**Comment by luchob** [comment]
Не виждам нищо в репозиторито, вероятно не си направила push. Последният комит е преди 2 дни.

Поздрави,
Л.

**Comment by luchob** [comment]
To be continued in https://github.com/luchob/softuni-feb2023/issues/90
