### ISSUE TITLE
Login проблем

### ISSUE THREAD

**Issue by cUserd** [luchob/softuni-feb2023#83]
Лъчо здравей, 

Значи всичко си ми е готово и си тествам за последно и изведнъж security почва да ми прави някакъв странен проблем.
при Login като цъкна логин  и ми тегли картинка?!? втори клик и ми дава error page а в същото време  като дам назад и съм логнат. Това ми прилича на онзи странният проблем с fav iconata, но си имам вече.

Бих бил много благодарен ако успееш да погледнеш и дадеш някаква насока от какво може да е това чудо.

става върпос за customer login
https://github.com/cUserd/finalProject_softUni_Model3d

**Comment by luchob** [comment]
Здрасти! В Network tab-a има ли нещо подозрително? Най-вече 404/401/403.

**Comment by cUserd** [comment]
При първият клик когато тегли картинката не. При вторият дава POST //localhost//8080/login 403

и всичко се оправя когато махна anyRequest().authenticated() na anyRequest().permitall()

както и като подам defaultSuccessUrl("/",true)

**Comment by luchob** [comment]
Адски странно. При мен при клик на login отива на логин страницата без грешка.

<img width="939" alt="Screenshot 2023-03-26 at 13 35 49" src="https://user-images.githubusercontent.com/10339738/227770202-2dd2a387-8cd0-4a1a-a19f-e2785134f813.png">

След това, при логин с user:user@example.com/pass:user прави правилен POST и редиректва към хоум страницата, както е показано долу:

<img width="1118" alt="Screenshot 2023-03-26 at 13 36 34" src="https://user-images.githubusercontent.com/10339738/227770240-6c1d8c49-6887-499b-ad96-d2ef8c5a46f7.png">

Финално съм на хоум страницата:

<img width="749" alt="Screenshot 2023-03-26 at 13 39 28" src="https://user-images.githubusercontent.com/10339738/227770312-cabd9e59-921a-41b3-9c19-6f8ee8fce331.png">


Може ли да пробваш да разрешиш експлицитно в конфикураията ендпоинта /login
Увери се, че минава логина и с csrf тоукън, например това е при мен.
```
_csrf=2MWjJtdmoA6-FJZ1vzcWVlg8Qr1sApQxW-nxiKS39v8PPa5P7qGbQuBXk2yTcK4RixoiYmxfb4VfN6YcOIvA6pWFxsltX8p4&back=my-account&username=user%40example.com&password=user&submitLogin=1
```

Ако вземеш CSRF тоукъна и опиташ с POSTMAN? Какво имаш в бодито на този ПОСТ който фейлва с 403?

**Comment by cUserd** [comment]
Ами достигнах до следният извод .  Когато дирeктно въведа URL  localhost8080/login  тогава не го прави този проблем , но когато 
през менюто отида на логин и го прави. Иначе опитах и през edge както и през incognito и все същото . 
опитах и експлицитно да го сложа , но разлика няма
През POSTMAN нещо не мога да се оправя с този токън . слагам го където трябва и всичко си е ок привидно, но накрая 
ми дава 
{
    "timestamp": "2023-03-26T11:36:24.904+00:00",
    "status": 403,
    "error": "Forbidden",
    "path": "/login"
}

Единствено го прави ако през навбара се опитам да се логна което е доста странно защото ме редиректва на същата страница и всичко си е същото.

като единствено проявявам съмнение че до този линк за логин се стига през  sec:authorize="isAnonymous()" и може би това да го бърка нещо

ъпдейт: .... така както мистеризно от нищото започна да го прави ... още по мистериозно за мен и спря да го прави... 

Благодаря за отделеното време Лъчо ... нямам обяснение какво се случи ... но изведнъж си заработи както трябва ... 
не мисля че е ок за едно приложение да се държи по този начин , но сигурно си има някаква причина.
Благодаря
