### ISSUE TITLE
проблем с thymeleaf 

### ISSUE THREAD

**Issue by StefanPYordanov** [luchob/softuni-feb2023#84]
Здравейте,

При опит да покажа options в add book не ми се показва нищо. Това което се опитвам да направя е при add book, да имам Име което се пише, да имам автор който да бъде избран от вече съществуващите такива в базата, както и жанра да бъде избран от вече съществуващите в енъма. Опитах по няколко начина които намерих, но не се получава. Ще Ви бъда благодарен ако погледнете когато имате време.
Поздрави,
Стефан

https://github.com/StefanPYordanov/BookLibrary

**Comment by luchob** [comment]
Здравей!

За жанровете има грешка:

```
${T(com.example.Library.model.enums.GenreTypeEnum.values()}
```
Липсва една скоба:
```
${T(com.example.Library.model.enums.GenreTypeEnum).values()}
```

Като се добави се появяват:

<img width="836" alt="Screenshot 2023-03-26 at 13 51 31" src="https://user-images.githubusercontent.com/10339738/227770943-1aa6fe8c-cc3e-468d-a7ae-c552cc8e253e.png">

За авторите, тях изобщо ги няма в модела, т.е. няма от къде да се попълнят:

```
    @GetMapping("/addbook")
    public String addbook(){
        return "addbook";
    }
```

В DTO-тата не бива да има ентитита.

Поздрави,
Л.
