### ISSUE TITLE
56% coverage

### ISSUE THREAD

**Issue by IvailoB** [luchob/softuni-feb2023#86]
https://github.com/IvailoB/SoftUni-Java-WEB/tree/main/CarWeb

все още имам проблем с 2 теста. 
Знам че проблема е в мен не в тестовете, но все пак колко ги мъчих и нищо.

**Comment by luchob** [comment]
Здравей!

Относно първият тест. 

``` 
    @Test
    void testAddConfirm() throws Exception {
        mockMvc.perform(MockMvcRequestBuilders.post("/cars/add"))
                .andExpect(MockMvcResultMatchers.status().isOk())
                .andExpect(MockMvcResultMatchers.view().name("redirect:/cars/details/{id}"));
    }
```

Пускаш POST request с празно body. Контролерът обаче очаква нещо съвсем друго. Някакво DTO + principal,
няма и BindingResult след него:

```
    @PostMapping("/add")
    public String addConfirm(@Valid AddCarDTO addCarDTO,
                             Principal principal) throws IOException {
    }
```

В такъв случай спринг връща грешка 400 - рекуестът е невалиден:

```    
java.lang.AssertionError: Status expected:<200> but was:<400>
Expected :200
Actual   :400
```

Как се емулира POST request -> [Тук](https://github.com/luchob/softuni-feb2023/blob/main/mobilele/src/test/java/com/softuni/mobilele/web/RegistrationControllerIT.java#L52). 

Как се слага тестов юзър заради спринг секюрити -> [Тук](https://github.com/luchob/softuni-may2022/blob/85f878a9586ce9d598e02bfd80100fc00d88765b/mobilele/src/test/java/bg/softuni/mobilele/web/OfferControllerIT.java#L61).

**Comment by luchob** [comment]
Относно вторият тест:

``` 
    @Mock
    private UserService mockUserService;
``` 

Това е мокито мок. Т.е. това е нещо, което може да правиш в юнит тестове, а не в интегрейшън. В интегрейшън тестовете има една анотация `@MockBean`, която не ти е необходима тук.

Това което ти е необходимо, например е `WithMockUser` & Co. Виж предния ми отговор и започни оттам. 

Ако продължават грижите, ще помагаме :-)

Поздрави,
Л.
