### ISSUE TITLE
Смяната на езика в навигацията

### ISSUE THREAD

**Issue by AtanasKaloyanov** [luchob/softuni-feb2023#88]
Здравей, Лъчо,

В приложението си конфигурирам 3 @Bean-а: LocaleResolver, LocaleChangeInterceptor, както и MessageSource, за да мога да сменя езиците в навигацията си. Нещо обаче със сигурност ми убягва, защото смяната не се случва.

Това е линкът към проекта ми - https://github.com/AtanasKaloyanov/Libra

Поздрави и лека вечер!
:)

**Comment by luchob** [comment]
Здравей! 

Учудвам се леко, защото при мен работи:

<img width="1247" alt="Screenshot 2023-03-27 at 12 53 58" src="https://user-images.githubusercontent.com/10339738/227908223-0a92e64a-d6de-448c-b32a-1f67fbd8a12a.png">
<img width="1256" alt="Screenshot 2023-03-27 at 12 54 07" src="https://user-images.githubusercontent.com/10339738/227908243-0791255e-09bf-4ee0-b193-dc7169eec0bf.png">

Не виждам и нищо нередно в конфигурацията, честно казано. 

Обаче виждам нередност в самите properties files. Тези с българския език ми се струват, че са с енкодинг ISO-8859-1, което противоречи на конфигурацията и въобще на кирилицата :-)

```
        @Bean
        public MessageSource messageSource() {
...
            resourceBundleMessageSource.setDefaultEncoding("UTF-8");
...
        }
```

Трябва да си настроиш IntelliJ да ги обработва с UTF-8 и да ги запишеш така. Мисля, че там би могло да е "заровено кучето".

<img width="312" alt="Screenshot 2023-03-27 at 12 58 41" src="https://user-images.githubusercontent.com/10339738/227909341-4a5ab1c2-7b9a-4284-b93b-d833b02d4f7f.png">

Поздрави,
Л.

**Comment by AtanasKaloyanov** [comment]
Здравей отново,

От setting -> file encoding зададох на default encoding for properties files: UTF-8, последвано от apply. След това написаното  в messages_bg.properties започна да ми излиза на кирилица вместо като йероглифи и долу вдясно на средата за разработка ми излезе UTF-8 вместо ISO-8859-1

![Screenshot 2023-03-27 191628](https://user-images.githubusercontent.com/102095904/228002542-eba1cd1a-537a-4bb0-ba25-87a44d152702.png)

Оказа се. че отново не могат да се сменят езиците. Независимо от задаване на English или Български написаното в навигацията си остава на български (както в приложените снимки)

![Screenshot 2023-03-27 192419](https://user-images.githubusercontent.com/102095904/228004643-5d63baa9-137d-48bb-9687-da3b09184183.png)
![Screenshot 2023-03-27 192539](https://user-images.githubusercontent.com/102095904/228004648-673a10d6-584d-42a8-9a06-a3943a06e496.png)

Опитах и други възможни комбинации при  настройките на file-encoding-a: default-ни или UTF-8 на Project Encoding и Global Encoding, със или без Bom и т.н, но резултатът си остана същия. При изтегляне на mobilele от предишния курс (май 2022 година) отново навигацията е по-същия начин, както в снимките (само на кирилица и при двата зададени езика English и Български), а не би трябвало, защото на теб ти работи перфектно на лекцията, в която го показваш.

Имаш ли идея как може да се излезе от тази ситуация? :)

Поздрави и Благодаря!

**Comment by ggrotseva** [comment]
Здравейте,

И при мен езика не се сменя. Не знам дали е същия проблема, но установих, че lang=en_US не се изпраща като Cookie по някаква причина. Сякаш не се прихваща lang параметъра в URL и CookieLocaleResolver-a реално не си върши работата.
Също съм на Windows.

Поздрави!

**Comment by luchob** [comment]
Привет!

Очевидно има нещо специфично, тъй като при мен обикновено работи. Може ли с Network таба да извадите един пълен reqest/response при смяна на езика?

Поздрави,
Л.

**Comment by ggrotseva** [comment]
Привет!

![image](https://user-images.githubusercontent.com/120377275/228542935-b277771c-9a20-4bdf-8edf-0a2b0e7510a7.png)
![image](https://user-images.githubusercontent.com/120377275/228543012-4e45302d-707a-434b-b04c-d99b6e647cd6.png)

Ето ги моите Request/Response.

Edited: Ето и Payload-a:
![image](https://user-images.githubusercontent.com/120377275/228549565-37c78aac-932a-4945-a419-3be93aaaf9d3.png)


Поздрави!

**Comment by luchob** [comment]
Много интересно, сякаш действително не сетва кууки. Бих предложил една дебъг сесия лесно е. За начало да видим какво става в кода на интерсептора:

``` 
@Override
	public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler)
			throws ServletException {

		String newLocale = request.getParameter(getParamName());
		if (newLocale != null) {
			if (checkHttpMethod(request.getMethod())) {
				LocaleResolver localeResolver = RequestContextUtils.getLocaleResolver(request);
				if (localeResolver == null) {
					throw new IllegalStateException(
							"No LocaleResolver found: not in a DispatcherServlet request?");
				}
				try {
					localeResolver.setLocale(request, response, parseLocaleValue(newLocale));
				}
				catch (IllegalArgumentException ex) {
					if (isIgnoreInvalidLocale()) {
						if (logger.isDebugEnabled()) {
							logger.debug("Ignoring invalid locale value [" + newLocale + "]: " + ex.getMessage());
						}
					}
					else {
						throw ex;
					}
				}
			}
		}
		// Proceed in any case.
		return true;
	}
``` 

А после и в кода на кууки локейл резолвъра.

```
@Override
	public void setLocale(HttpServletRequest request, @Nullable HttpServletResponse response, @Nullable Locale locale) {
		setLocaleContext(request, response, (locale != null ? new SimpleLocaleContext(locale) : null));
	}

	@Override
	public void setLocaleContext(HttpServletRequest request, @Nullable HttpServletResponse response,
			@Nullable LocaleContext localeContext) {

		Assert.notNull(response, "HttpServletResponse is required for CookieLocaleResolver");

		Locale locale = null;
		TimeZone timeZone = null;
		if (localeContext != null) {
			locale = localeContext.getLocale();
			if (localeContext instanceof TimeZoneAwareLocaleContext) {
				timeZone = ((TimeZoneAwareLocaleContext) localeContext).getTimeZone();
			}
			addCookie(response,
					(locale != null ? toLocaleValue(locale) : "-") + (timeZone != null ? '/' + timeZone.getID() : ""));
		}
		else {
			removeCookie(response);
		}
		request.setAttribute(LOCALE_REQUEST_ATTRIBUTE_NAME,
				(locale != null ? locale : determineDefaultLocale(request)));
		request.setAttribute(TIME_ZONE_REQUEST_ATTRIBUTE_NAME,
				(timeZone != null ? timeZone : determineDefaultTimeZone(request)));
	}
```

Интересно е наистина, т.к. при мен работи а на уиндоуска машина - явно не.

**Comment by thrako** [comment]
Здравейте,
Може и да няма връзка, но и не пречи да се опита: Chrome наскоро въведоха по-сурова политика срещу third-party cookies, може в процеса да са пипали нещо и по локацията, та... някой пробва ли с друг браузър?
Поздрави,
Траян

**Comment by luchob** [comment]
С моя хром работи, а той е последен...

Освен това незеависимо от всякакви браузъри и политики, съдя по скрийншота на @ggrotseva че сървъра изобщо не връща кууки, което ме учудва много.

Поздрави,
Л.

**Comment by thrako** [comment]
Я да видим: 
![1](https://user-images.githubusercontent.com/101820581/228766025-b2e2d60b-fe0c-4fc2-8ce4-0fb7c77d9c92.jpg)

Може би, ако WebConfig се анотира с @Configuration ще проработи и на Windows :)

Поздрави,
Траян

**Comment by ggrotseva** [comment]
@thrako, ти да видиш, какви големи неща пропускаме докато се взираме в малките :D 
Да, така работи, браво. Надявам се и на @AtanasKaloyanov да е разрешен проблема също.

Поздрави и благодаря!

**Comment by luchob** [comment]
@thrako Еее... не. Тези обикновено ги виждам :-) Неговият е анотиран.

https://github.com/AtanasKaloyanov/Libra/blob/main/libra/src/main/java/bg/softuni/libra/config/WebConfig.java#L8

Ако липсва анотация няма да работи и при мен. А сорса на @ggrotseva не го бях гледал. Признавам :-)

**Comment by AtanasKaloyanov** [comment]
Здравейте,

Интересното е, че при  @luchob приложението ми работи, а при мен все още не => е локален проблемът. Преинсталирах и средата за разработка, пак не става. Опитах и с приложението на @ggrotseva, не сменя езиците по същия начин, както и при мен (след като сложих конфигурацията).

![Screenshot 2023-03-30 130926](https://user-images.githubusercontent.com/102095904/228804138-36fed1c4-3260-41eb-a4ec-8a5b5e8f5138.png)
![Screenshot 2023-03-30 130938](https://user-images.githubusercontent.com/102095904/228804152-59c93bfe-ff77-483e-b1a4-da39e6b57f9c.png)

Ето и request/response от проблемното преминаване от български на английски от моя проект:


![Screenshot 2023-03-30 134250](https://user-images.githubusercontent.com/102095904/228813156-75b5dff3-b1ea-48b8-b29e-d0559a938b4a.png)
![Screenshot 2023-03-30 134314](https://user-images.githubusercontent.com/102095904/228813168-45ce9fd7-d1a9-4d05-afc8-32772a4b13b9.png)
![Screenshot 2023-03-30 132953](https://user-images.githubusercontent.com/102095904/228813182-5992b70a-7e42-4024-bdb5-08735785e297.png)
![Screenshot 2023-03-30 134332](https://user-images.githubusercontent.com/102095904/228813194-9bbc44b0-3221-476b-99f9-4cfea1dc7b54.png)

Хубав ден!

**Comment by thrako** [comment]
@luchob Е добре... на единият проблема го разрешихме, половин бира ще черпиш :D на някои Java бири.

Sent from Trayan's phone.
________________________________

**Comment by luchob** [comment]
@AtanasKaloyanov От любопитство - работи ли ти този линк? -> http://localhost:8000/?lang=bg

**Comment by AtanasKaloyanov** [comment]
@luchob Не, когато натисна линка виждам ето това:

![Screenshot 2023-03-30 172344](https://user-images.githubusercontent.com/102095904/228867964-c462eebc-6aa6-4898-adca-2ff5e0ebdbc1.png)

**Comment by luchob** [comment]
Имах предвид ако сменяш така езиците:

 http://localhost:8000/?lang=bg
  http://localhost:8000/?lang=en

Да не е bg_BG и en_US. След това пробвай и с bg-BG и en-US може би това не му харесва, т.к. има два стандарта, от които този с underscore е стария.

**Comment by Alexanski13** [comment]
Здравейте!

Изглежда и аз се сблъсках с този lang interceptor проблем. Ако може да ми помогнете да разбера защо не се сменя езика.

Имам web config, locale controller , navbar form за смяната, ползвам  UTF-8 на intellij също.

https://github.com/Alexanski13/My-Gym-Shop/tree/main/my-gym-shop/src/main

**Comment by AtanasKaloyanov** [comment]
@luchob  Опитах с en-US, а после само с en стойност. За съжаление отново не се получиха нещата. В първи случай дори не ми изписва en-US в url-то:

![Screenshot 2023-03-31 170014](https://user-images.githubusercontent.com/102095904/229142079-2a0b3c98-adf1-4d82-bac5-d71e0db28172.png)
![Screenshot 2023-03-31 165733](https://user-images.githubusercontent.com/102095904/229142097-3352e2db-b3bc-43af-b485-e7c363ba32fd.png)

**Comment by luchob** [comment]
Привет!

Много странен проблем наистина! Още повече че винаги излиза на български, който не е default. Следващ опит. Може в application.yaml да пуснем дебъг режима на thymeleaf. Така:

```
logging:
  level:
    org.thymeleaf: TRACE
```

След това при смяна на езика се вижда нещо от сорта в конзолата:
```
2023-04-01 07:34:22.819 TRACE 18728 --- [nio-8000-exec-1] org.thymeleaf.TemplateEngine             : [THYMELEAF][http-nio-8000-exec-1] STARTING PROCESS OF TEMPLATE "index" WITH LOCALE bg_BG
```

Интересно е, дали се сменя локала, за да знаем къде да търсим.

Поздрави,
Л.

**Comment by luchob** [comment]
Тръсим и подобен лог:


```
2023-04-01 07:34:22.883 TRACE 18728 --- [nio-8000-exec-1] o.t.s.expression.MessageExpression       : [THYMELEAF][http-nio-8000-exec-1] Evaluating message: "#{navbar_all_brands}"
2023-04-01 07:34:22.883 TRACE 18728 --- [nio-8000-exec-1] o.t.s.expression.GenericTokenExpression  : [THYMELEAF][http-nio-8000-exec-1] Evaluating generic token: "navbar_all_brands"
2023-04-01 07:34:22.883 TRACE 18728 --- [nio-8000-exec-1] o.t.s.m.SpringMessageResolver            : [THYMELEAF][http-nio-8000-exec-1] Resolving message with key "navbar_all_brands" for template "fragments/navbar" and locale "bg_BG". Messages will be retrieved from Spring's MessageSource infrastructure.
2023-04-01 07:34:22.883 TRACE 18728 --- [nio-8000-exec-1] o.t.e.springsecurity5.auth.AuthUtils     : [THYMELEAF][http-nio-8000-exec-1] Obtaining authentication object.
```

**Comment by lamenco** [comment]
Здравейте, този проблем ми писна да го мисля още преди месец, какво ли не правих. Днес се върнах към драмата и просто промених името на 
messages.properties на messages_en.properties, както е и файла за български  messages_bg.properties и се получи.
Поздрави!

**Comment by luchob** [comment]
Ах! @lamenco - OS-a на компютърът ти е с български локал by default?

Лелееее.... Съжалявам че не се усетих :-)
