### ISSUE TITLE
Проблем с индивидуалният ми проект

### ISSUE THREAD

**Issue by MariaBonkova** [luchob/softuni-feb2023#9]
Привет, реших да направя темплейти на head, navbar and footer. Но когато ги риплейснат на index стрницата и ми я счупи по този начин по, който излиза. Пробвах варианти, но незнам от къде дойде това нещо. Ще съм благодарна за помоща ви!
https://github.com/MariaBonkova/3D-printing-project/tree/master

**Comment by luchob** [comment]
Здравей!

Погледни Network таба си, когато се зарежда сайта. Сваляш css от: localhost:8080/static/css/...
Там няма нищо, правилния адрес на статичните ресурси е localhost:8080/css/...

<img width="1211" alt="Screenshot 2023-02-23 at 17 17 17" src="https://user-images.githubusercontent.com/10339738/220948799-275ac0f8-3782-4d12-807f-af61150567b6.png">

Поздрави,
Л!

**Comment by MariaBonkova** [comment]
![Screenshot_20230224_012309](https://user-images.githubusercontent.com/120118418/221054052-1c38b1d2-34ce-46e7-86a9-1ac66c65b0b8.png)
Привет имаш предвид да изтрия на ред 15 и 16 /static. 
Страното е , че когато си върна хеда и навбара в хтмл-а на index страицата си работи тоест вижда се всичко както трябва. Пробвах да сложа само хеда в хтмлл. В браузера пак текста в страницата излиза като непознати букви и без css. Като натисна произволлен бутон от навбара и ми хвърля в network таба 404.

**Comment by MariaBonkova** [comment]
![Screenshot_20230224_013347](https://user-images.githubusercontent.com/120118418/221055379-d22588bf-e7d5-4198-a158-af5d7adbe720.png)

Така ми излизат като непознати символи .  

![Screenshot_20230224_013455](https://user-images.githubusercontent.com/120118418/221055488-38e37dd9-7789-4241-8b88-0252e1704762.png)
Тук освен home също login и register ми светват с 404 и си мисля че няма да е само от сss

**Comment by luchob** [comment]
Привет! 

Доколкото виждам, опитваш се да покажеш темплейтите без да пускаш спринг приложението (съдя по localhost:63342, което е уеб сървъра на IntelliJ). Т.е. отваряш ги така:

<img width="222" alt="Screenshot 2023-02-24 at 7 55 39" src="https://user-images.githubusercontent.com/10339738/221103157-88f8850d-f9ba-4ec2-8cd3-b5540a5d6427.png">

А не като пуснеш спринг:

<img width="301" alt="Screenshot 2023-02-24 at 7 56 41" src="https://user-images.githubusercontent.com/10339738/221103280-1cface15-13d3-4179-a860-cfe99ef6bd19.png">

Това ли искаш? Да ги гледаш като статичен content или да пуснеш спринг и да заредиш приложението си?

Л.

**Comment by MariaBonkova** [comment]
По принцип искам да работи, но явно съм се забутала и правя някакви неадекватни неща. Сега си го рънах и видях както ти си ми показал на първия коментар за буутстрап и css. ОПРАВИХ нещата. 
Може ли и малко насоки относно архитектурата на ентитита ми и някой изисквания по проекта.  
1.В изискванията на проекта пише като условие юзъра да има роля админ и модератор, но в моят проект си го представям юзъра да има роли като:
 гост/само гледа/,
 като купувач/гледа и купува/ тука рови в каталозите и купува
 и като създател/тук той си дава размери и описание какво иска да му направим с притера/ реално тук излиза нова хтмл страница да си въведе оферта.
Ролята купувач се отваря като се регистрира.
Допълнително ролята купувач и създател отваря опция да направи подарък на приятел.
Идеята ми е в навбара има текст  който ще се променя в зависимост от ролята.
Това с ролите адекватно ли ще е на заданието което се изисква от нас.

2. Относно архитектурата направих на пейнт нещо като диаграма с връзките, но някак си ми се иска да ги изкоментирам защото не съм сигурна кое ще е функционално. Удачно ли е да направя енъм клас продукти като в него да нашвакам продуктите който ще произваждам/къщи, домашни потреби, музикални инструменти и за домашни любимци/. И отделно като отделни класове да сложа къщи, музикални и за любимци. Или да махна енъм класа и да жуля направо тези класове където ще ги произваждам.

3.  За материалите също съм в чуденка. Тях като енъм клас ли да ги направя и отделно в клас производствени характеристик да сложа полета:
-.  състав на материала/който идва от енъма/, 
-. цена,
-.  количество 
-. и да направя връзка с продукт и юзър. Или ако ти се сещаш някакъв по-удачен начин.
Тук трябва да заложа за всеки материал твърда цена на 1 килограм. Така го четох из сайтовете и да направя някаква логика за изчисляване взависимост от размера на поръчаният продукт.
Извинявам се за дългото писмо, но тъй като казахте ако имаме проблеми да пише!
[diagrama 3DProject](https://user-images.githubusercontent.com/120118418/221227137-e698389a-5eca-4ec8-b5e7-2e44538e91cf.jpg)
 Благодаря предварително!
М.

**Comment by luchob** [comment]
1) Вярвам, че е ок но по-добре питай съпорта на софтуни за да няма после драми.
2) Според мен е удачно да пазиш продуктите в ДБ, в таблица products и да ги достъпраш с ProductEntity/ProductRepository :-)
3) Може би материала също би могъл да бъде продукт, но да има връзка с табличка за състава на продукта. Product Compound - many to many relation, напр. Както User/UserRole в това дето го правихме.

Има много варианти, давай смело, ако не работи - преработва се и докато проработи.

Поздрави,
Л.
