### ISSUE TITLE
Integration Test моля за помощ

### ISSUE THREAD

**Issue by ViliIlieva** [luchob/softuni-feb2023#91]
https://github.com/ViliIlieva/MyKnitShop
Здрасти отново,
пак зациклих на едни тест OrderControllerIT, при опит да създам данни които да получа в последствие като model().attributeExists() не откривам точно как да ги върна като модел
Дава ми че 'cartCashProduct' does not exist

**Comment by luchob** [comment]
Здравей!

Първо да припомня, че когато пускаш някакъв интеграционен тест вече не работиш с MySQL, а с in-memory база данни. Затова понякога нещата не работят на 100% както преди. Ако разчетеш ексепшъните от твоя тест, ще видиш че си попаднала в един такъв случай. Имаш поле(та) които се казват SUM.

```
public class ChoseProducts extends BaseEntity{
    
    @Column
    private BigDecimal sum;
}
```

За съжаление, не може да имаш такава колонка в hsql тъй като SUM е служебна думичка и не може да служи за име на колонка.

Поздрави,
Л.
