### ISSUE TITLE
Въпрос относно функционалността за добавяне на резервация

### ISSUE THREAD

**Issue by yanamet** [luchob/softuni-feb2023#92]
Здравей, Лъчо. От няколко дни се чудя как във формата ми данните да са предварително попълнени. Малко по-подробно -> за да резервирам, първо трябва да проверя за свободни стаи (RESERVE в навбар). След като сърчнем за свободни стаи по тип, избираме някоя с точен номер. Искам да резервирам точно тази стая, затова, когато кликна на нея, ме редиректва към /reservations/add/{id}, като id е идентификаторът на стаята, която съм кликнала. В самата форма искам вече полетата checkIn, checkOut и roomType да бъдат вече попълнени, но единствено успях за roomType. Въпросът ми е как да пренеса данните от сърча (тоест датите, които търся) във формата и също така при натискане на reserve с грешни данни (празни) не ме редиректва правилно обратно. Мисля, че това е заради id в  url. Все още не съм направила изцяло логиката за запазването на резервацията, защото първо исках да се подсигуря, че потребителят няма да въведе различни данни от тези, за които вече е проверил наличността.

линк към проекта -> https://github.com/yanamet/HotelAntique

**Comment by luchob** [comment]
Здравей!

На първия въпрос, най-лесно е разбира се да ги предадеш като query param-s. Още като показваш сърч резултата, там имаш датите и ще ги пуснеш като query params в линка, ще стане нещо от сорта на:
```
/reservations/add/...?from=...&to...
```
В thymeleaf добавянето на куери параметри е елементарно, провери в документацията.

Относно втория въпрос - да, правилно си се ориентирала - заради id-то е. Може да го добавиш в th:action

Поздрави,
Л.
