### ISSUE TITLE
Проблем с триенето на обекти от базата при тестване

### ISSUE THREAD

**Issue by NicoleNG18** [luchob/softuni-feb2023#93]
Здравей, Лъчо. Имам проблем при тестовете. Когато стартирам този тест си минава, но когато стартирам всички тестове в класа -  фейлва. Трябва да му подам id = 6, за да мине заедно с другите два. Явно в setUp метода ми има грешка.

  @Test
    @WithMockUser(username = "user1", roles = "USER")
    void testAddingProductToCart_WorksCorrectly() throws Exception {

        mockMvc.perform(MockMvcRequestBuilders.patch("/cart/add/2").with(csrf())
                        .param("id", "2"))
                .andExpect(status().is3xxRedirection())
                .andExpect(redirectedUrl("/menu/pizza"));

    }

Ако си разбрал къде греша и изобщо какво те питам, че ми е доста объркано всичко това, моля за помощ.

Оставям линк към репозиторито тук: https://github.com/NicoleNG18/FoodDelivery

Поздрави,
Никол

**Comment by luchob** [comment]
Добро утро!

Всъщност - защо реши, че трябва да е 2 или 6 или нещо друго? id-то е autoincrement колонка и колкото повече тестове минават, толкова повече id-то ще нараства. Въпреки че това не е точно, представяй си ги как вървят един след друг на пуснатия ти истински сървър. 

Ако минат 3 преди твоя пицата ти би могла да е номер 4. Още по-лошо (или по-добре) ти не определяш в какъв ред да се изпълнят. Затова трябва да модифицираш теста с нещо подобно:

```
    @Test
    @WithMockUser(username = "user1", roles = "USER")
    void testAddingProductToCart_WorksCorrectly() throws Exception {

        mockMvc.perform(MockMvcRequestBuilders.patch("/cart/add/{id}", pizzaOne.getId())
                .with(csrf()))
                .andExpect(status().is3xxRedirection())
                .andExpect(redirectedUrl("/menu/pizza"));

    }
```

Поздрави,
Л.

**Comment by NicoleNG18** [comment]
Благодаря!
