### ISSUE TITLE
Помощ за Fetch

### ISSUE THREAD

**Issue by Maria-Pavlova** [luchob/softuni-feb2023#94]
Здравей Лъчо,
Моля за помощ. Не съм учила още Js и не успявам да се справя преизползвайки показаното от теб. Считам, че е подходящо да показвам messages по този начин. Направила съм за сега дървена имплементация на съобщения между Users. С нормален контролер всичко работи -  от navbar-a логнатия user вижда таблица с получените съобщения.. Направих RestController, чрез които получавам коректно съобщенията но в чист json на бял фон. Не знам дали неправилно направя връзката с Js  или самия Js не ми е правилен.
Линк към проекта: https://github.com/Maria-Pavlova/HomeExchange_SimpleVersion

**Comment by luchob** [comment]
Здравей!

Накратко - премести `messages-rest.html` в `templates` от `static`. Или пък съдържанието му да замени нормалния  `messages.html`. От контролера се зарежда този темплейт => ще се зареди и `js`-a ти. И там вече може да си сложиш `load` бутон и да го направиш като в книгите. Може и без load но съм сигурен, че така ще ти е по-лесно.

За съжаление в Spring частта всичко ти е наред, остава писането на JavaScript :-)

Поздрави,
Л.
