### ISSUE TITLE
Проблем с логин error message visualization и смяна на user visualization в navbar  fragment.

### ISSUE THREAD

**Issue by Alexanski13** [luchob/softuni-feb2023#97]
Привет Лъчо, когато въвеждам грешни данни за логин ме връща пак към логин с cleared fields за нов логин но не показва грешката за invalid user or pass.

Също ако може да ми помогнеш да разбера как да сменя Welcome (email) с Welcome (username) в navbar fragmenta.

**Comment by luchob** [comment]
Привет!

Относно първия ти въпрос може да отбележа, че проблема е че самата `/users/login-error` е забранена. Като стане грешка и се опиташ да я достъпиш, то не дава и те редиректва... към логин страницата :-) Може да я разрешиш:

```
requestMatchers("/", "/users/login", "/users/login-error", "/users/register", "/users/profile").permitAll().
```

**Comment by Alexanski13** [comment]
Малките детайли ме измъчват явно, търсех причината поне едно 20 мин преди да се предада след няколко опита да рефакторирам кода >.< . Благодаря, ако можеш да ми помогнеш и с оправянето на welcome съобщението ще е перфе защото не намерих начин да го изкарам.

**Comment by luchob** [comment]
Привет, мога!

```
<p th:text="${#authentication.principal.fullName}"/>
```

Обръщам внимание, че `#authentication.principal` е нищо повече от твоя собствен `AppUserDetails`. Каквото и да сложиш вътре ще имаш достъп в темплейта.

Поздрави,
Л.
