### ISSUE TITLE
Fetch API

### ISSUE THREAD

**Issue by GeorgiPetrov4400** [luchob/softuni-feb2023#98]
Здравей отново :)

Buy бутона за купуване на forecast-и си го оправих, но сега се опитвам да си направя free forecast. Зарежда ми правилните json-и, но когато се опитвам да ги направя с fetch да излизат през html не се получава и ако може да ми кажеш къде ми е грешката понеже аз съм от тези които не са минали през Javascript курса и ми е малко сложно това и не разбирам къде ми е проблема.
Това е линк към гитхъб профила ми: 
https://github.com/GeorgiPetrov4400/Trading-Forecasts/tree/main/TradingForecasts/TradingForecasts

Поздрави

**Comment by luchob** [comment]
Здравей!

Ами то почти работи :-)

<img width="967" alt="Screenshot 2023-03-31 at 16 03 34" src="https://user-images.githubusercontent.com/10339738/229127882-8f2ab673-bef3-4d94-b744-cade6382a8a7.png">

Само че не става много добре, наистина. Това, което трябва да направиш е да си отвориш JSON-a и HTML-a и JS и да гледаш:

``` 
[
   {
      "id":1,
      "category":{
         "id":2,
         "category":"EurGbp"
      },
      "forecastType":"Long",
      "description":"dsdsd",
      "pictureUrl":"sdsdsds",
      "price":null,
      "created":"2023-03-31T15:58:00.766768",
      "closed":null,
      "active":true
   }
]


<div class="container bg-blur rounded mt-1 mb-4">
        <h3>Free Forecasts</h3>
        <button id="loadForecasts">LOAD FREE FORECASTS</button>

        <div class="active-forecast" style="height: 30vh; overflow: auto" id="forecast-container">

         <tr>
            <td>[object Object]</td>
            <td></td>
            <td></td> 
            <td>dsdsd</td>
         </tr>
      </div>
</div>
```
В колонка едно слагаш  `forecast.category` Е да, ама това е обект:

``` 
"category":{
         "id":2,
         "category":"EurGbp"
      },
``` 

Може би искаш да кажеш `forecast.category.category`?

След това имаш `forecast.type` ама в JSON-a имаш `forecastType` а не `type`... -> празно. Може би опитай с `forecast.forecastType`.

В JSON също няма `forecast.picture`. И т.н. 

В крайна сметка с JS-a  генерираш един HTML. Трябва да го гледаш как става и какво има в JSON-a. Ако имаш грешка в JS-a ще я видиш в конзолата на dev tools-a на браузъра. Там ти е новото "IDE" :-) И другото е създаване на елементи с ванила JS и добавянето им/триенето им от DOM дървото. В нета е зарито с милиони примери. Може би няма нещо, за което има толкова въпроси и примери някои добре отлежали на над 15 години :-)

Поздрави,
Л.
